import { render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,describe,expect,it,vi } from "vitest";
import OperationalExecutionSection from "@/components/OperationalExecutionSection";
const api=vi.hoisted(()=>({preview:vi.fn(),milestones:vi.fn(),progress:vi.fn(),events:vi.fn(),conditions:vi.fn(),reasons:vi.fn(),initialize:vi.fn(),transition:vi.fn(),reopen:vi.fn(),verify:vi.fn(),createCondition:vi.fn(),resolveCondition:vi.fn()}));
vi.mock("@/lib/api",async()=>{const actual=await vi.importActual<typeof import("@/lib/api")>("@/lib/api");return {...actual,getExecutionPreview:api.preview,listExecutionMilestones:api.milestones,getExecutionProgress:api.progress,listExecutionEvents:api.events,listExecutionConditions:api.conditions,listExecutionReasons:api.reasons,initializeExecution:api.initialize,transitionExecutionMilestone:api.transition,reopenExecutionMilestone:api.reopen,verifyExecutionEvent:api.verify,createExecutionCondition:api.createCondition,resolveExecutionCondition:api.resolveCondition}});
const milestone={public_id:"11111111-1111-4111-8111-111111111111",sequence:1,milestone_type:"CUSTOMS",milestone_type_snapshot:{fa_name:"ترخیص",en_name:"Customs",code:"CUSTOMS"},expected_point_snapshot:null,status:"PENDING" as const,verification_state:"planned",version:1};
beforeEach(()=>{vi.clearAllMocks();api.preview.mockResolvedValue({data:{initialized:true,existing_count:1,milestones:[],findings:[],confirmation_allowed:false}});api.milestones.mockResolvedValue({data:[milestone]});api.progress.mockResolvedValue({data:{initialized:true,total:1,counts:{PENDING:1,READY:0,IN_PROGRESS:0,COMPLETED:0,SKIPPED:0,CANCELLED:0,BLOCKED:0},current_milestone:milestone,completion_percentage:0,completion_rule:"rule",active_delay_count:0,active_exception_count:0}});api.events.mockResolvedValue({data:[]});api.conditions.mockResolvedValue({data:[]});api.reasons.mockResolvedValue({data:[]});api.transition.mockResolvedValue({data:{...milestone,status:"READY",version:2}})});
describe("Operational Execution section",()=>{it("renders progress, empty conditions and bounded transition controls",async()=>{const user=userEvent.setup();render(<OperationalExecutionSection shipmentPublicId="11111111-1111-4111-8111-111111111110" shipmentVersion={1}/>);expect(await screen.findByText(/0% complete/)).toBeInTheDocument();expect(screen.getByText(/ترخیص/)).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"READY"}));await waitFor(()=>expect(api.transition).toHaveBeenCalledWith(expect.any(String),milestone,"READY",undefined));expect(screen.queryByText(/Evidence/i)).not.toBeInTheDocument();expect(screen.queryByText(/Dashboard/i)).not.toBeInTheDocument()});it("is read-only when requested",async()=>{render(<OperationalExecutionSection shipmentPublicId="11111111-1111-4111-8111-111111111110" shipmentVersion={1} readOnly/>);await screen.findByText(/ترخیص/);expect(screen.queryByRole("button",{name:"READY"})).not.toBeInTheDocument()})});
