import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,describe,expect,it,vi} from "vitest";
import OrganizationGlobalNetworkTab from "@/components/OrganizationGlobalNetworkTab";

const api=vi.hoisted(()=>({listOrganizationGlobalPoints:vi.fn(),addOrganizationGlobalPointToNetwork:vi.fn(),
 updateOrganizationGlobalPointAdoption:vi.fn(),transitionOrganizationGlobalPointAdoption:vi.fn()}));
vi.mock("@/lib/api",()=>api);
const adoption={public_id:"adoption-opaque",status:"ACTIVE",version:2,global_point_public_id:"global-opaque",platform_lifecycle_status:"ACTIVE",display_label:"Local",materialization:{state:"NOT_MATERIALIZED",logistics_point_public_id:null,version:null}};
const point=(state:string,adopt:unknown=null)=>({public_id:"global-opaque",immutable_code:"XZ-PORT",fa_name:"بندر",en_name:"Port",
 point_type:{code:"PORT",fa_name:"بندر",en_name:"Port"},country:{code:"XZ",fa_name:"کشور",en_name:"Country"},
 geography:{city:"City"},supported_modes:["SEA"],corridor_tags:[],organization_state:state,adoption:adopt});

describe("Organization Global Network",()=>{
 beforeEach(()=>{vi.clearAllMocks();vi.spyOn(window,"confirm").mockReturnValue(true);api.listOrganizationGlobalPoints.mockResolvedValue({items:[point("AVAILABLE")],page:1,pages:1,total:1});api.addOrganizationGlobalPointToNetwork.mockResolvedValue({item:{logistics_point_public_id:"tenant-point",adoption_public_id:"adoption-opaque",global_point_public_id:"global-opaque",created:true}});api.updateOrganizationGlobalPointAdoption.mockResolvedValue({item:{...adoption,version:3}});api.transitionOrganizationGlobalPointAdoption.mockResolvedValue({item:{...adoption,status:"INACTIVE",version:3}})});
 it("filters and adds a reference point directly to the organization network",async()=>{render(<OrganizationGlobalNetworkTab/>);await screen.findByText(/XZ-PORT/);expect(screen.getByText(/مستقیماً به شبکهٔ عملیاتی سازمان افزوده شود/)).toBeInTheDocument();fireEvent.change(screen.getByLabelText("کشور نقطه مرجع"),{target:{value:"XZ"}});await waitFor(()=>expect(api.listOrganizationGlobalPoints).toHaveBeenLastCalledWith(expect.objectContaining({country:"XZ"})));fireEvent.click(screen.getByText(/XZ-PORT/));fireEvent.change(screen.getByLabelText("برچسب نمایشی سازمان"),{target:{value:"My Port"}});fireEvent.click(screen.getByRole("button",{name:"افزودن به شبکهٔ سازمان"}));await waitFor(()=>expect(api.addOrganizationGlobalPointToNetwork).toHaveBeenCalledWith("global-opaque",expect.objectContaining({display_label:"My Port"})))});
 it("updates with adoption version and deactivates",async()=>{api.listOrganizationGlobalPoints.mockResolvedValue({items:[point("ADOPTED",adoption)],page:1,pages:1,total:1});render(<OrganizationGlobalNetworkTab/>);await screen.findByText(/XZ-PORT/);fireEvent.click(screen.getByText(/XZ-PORT/));fireEvent.click(screen.getByRole("button",{name:"ذخیره اطلاعات سازمان"}));await waitFor(()=>expect(api.updateOrganizationGlobalPointAdoption).toHaveBeenCalledWith(adoption,expect.any(Object)));fireEvent.click(screen.getByRole("button",{name:"غیرفعال‌سازی برای سازمان"}));await waitFor(()=>expect(api.transitionOrganizationGlobalPointAdoption).toHaveBeenCalledWith(adoption,"deactivate"))});
 it("completes an existing active adoption through the same add action",async()=>{api.listOrganizationGlobalPoints.mockResolvedValue({items:[point("ADOPTED",adoption)],page:1,pages:1,total:1});render(<OrganizationGlobalNetworkTab/>);await screen.findByText(/XZ-PORT/);fireEvent.click(screen.getByText(/XZ-PORT/));expect(screen.getByText(/وضعیت اتصال سازمان: آماده افزودن/)).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"افزودن به شبکهٔ سازمان"}));await waitFor(()=>expect(api.addOrganizationGlobalPointToNetwork).toHaveBeenCalledWith("global-opaque",expect.any(Object)))});
 it("shows the resulting operational link and no create action",async()=>{const done={...adoption,materialization:{state:"MATERIALIZED",logistics_point_public_id:"tenant-point",version:1}};api.listOrganizationGlobalPoints.mockResolvedValue({items:[point("ADOPTED",done)],page:1,pages:1,total:1});render(<OrganizationGlobalNetworkTab/>);await screen.findByText(/XZ-PORT/);fireEvent.click(screen.getByText(/XZ-PORT/));expect(screen.getByText("مشاهده مکان عملیاتی سازمان")).toBeTruthy();expect(screen.queryByRole("button",{name:"افزودن به شبکه عملیاتی سازمان"})).toBeNull()});
 it.each([["INACTIVE_FOR_ORGANIZATION","فعال‌سازی برای سازمان"],["PLATFORM_DEPRECATED",null]])("renders %s lifecycle safely",async(state,button)=>{api.listOrganizationGlobalPoints.mockResolvedValue({items:[point(state,{...adoption,status:"INACTIVE"})],page:1,pages:1,total:1});render(<OrganizationGlobalNetworkTab/>);await screen.findByText(/XZ-PORT/);fireEvent.click(screen.getByText(/XZ-PORT/));if(button)expect(screen.getByRole("button",{name:button})).toBeTruthy();else{expect(screen.getByText(/منسوخ شده است/)).toBeTruthy();expect(screen.queryByRole("button",{name:"فعال‌سازی برای سازمان"})).toBeNull()}});
 it("uses a distinct retryable network error state",async()=>{api.listOrganizationGlobalPoints.mockRejectedValueOnce(new TypeError("offline"));render(<OrganizationGlobalNetworkTab/>);expect(await screen.findByRole("alert")).toHaveTextContent(/ارتباط با سرویس/);expect(screen.getByRole("button",{name:"تلاش مجدد"})).toBeInTheDocument()});
});
