import {beforeEach,describe,expect,it,vi} from "vitest";
import {fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import ProjectConfiguration from "@/components/ProjectConfiguration";

const api=vi.hoisted(()=>({list:vi.fn(),services:vi.fn(),documents:vi.fn(),milestones:vi.fn(),points:vi.fn(),create:vi.fn(),update:vi.fn(),active:vi.fn(),reorder:vi.fn()}));
vi.mock("@/lib/api",()=>({listProjectConfiguration:api.list,listProjectServiceTypes:api.services,listProjectDocumentDefinitions:api.documents,listMilestoneTypes:api.milestones,listProjectLogisticsPointSelectors:api.points,createProjectConfiguration:api.create,updateProjectConfiguration:api.update,setProjectConfigurationActive:api.active,reorderProjectMilestones:api.reorder}));
vi.mock("@/components/ProjectLogisticsNetwork",()=>({default:()=> <div>Network 1.7.0 create update lifecycle reorder</div>}));
const page=(items:unknown[]=[])=>({items,page:1,per_page:100,total:items.length,pages:items.length?1:0});
const service={public_id:"ps-public",service_type_public_id:"svc-public",is_active:true,version:2,is_primary:false,is_required:true,display_order:3,display_label:"Freight",notes:"note"};
const document={public_id:"pd-public",document_definition_public_id:"doc-public",document_definition_title:"Bill",is_active:true,version:1,requirement_level:"OPTIONAL",display_order:2,notes:"doc note"};
const milestone={public_id:"pm-public",milestone_type_public_id:"mil-public",milestone_type_code:"DELIVERY",is_active:true,version:4,sequence:1,is_required:true,project_logistics_point_public_id:"point-public",target_duration_value:2,warning_duration_value:3,duration_unit:"HOUR",notes:"mil note"};

describe("Release 1.8.0 Project Configuration acceptance",()=>{
  beforeEach(()=>{vi.clearAllMocks();api.list.mockResolvedValue(page());api.services.mockResolvedValue(page([{public_id:"svc-public",fa_name:"حمل",immutable_code:"FREIGHT"}]));api.documents.mockResolvedValue(page([{public_id:"doc-public",title:"Bill",code:"BOL"}]));api.milestones.mockResolvedValue(page([{public_id:"mil-public",fa_name:"تحویل",immutable_code:"DELIVERY"}]));api.points.mockResolvedValue(page([{public_id:"point-public",display_label:"Port"}]));api.create.mockResolvedValue({item:{}});api.update.mockResolvedValue({item:{}});api.active.mockResolvedValue({item:{}});api.reorder.mockResolvedValue({items:[]})});

  it("loads, creates, edits and changes lifecycle for governed services",async()=>{const u=userEvent.setup();api.list.mockResolvedValue(page([service]));render(<ProjectConfiguration projectId="project-public"/>);expect(await screen.findByText("Freight")).toBeInTheDocument();expect(screen.getByRole("option",{name:/FREIGHT/})).toHaveValue("svc-public");expect(screen.queryByRole("textbox",{name:/identity/i})).not.toBeInTheDocument();await u.click(screen.getByRole("button",{name:"Edit Services item"}));expect(screen.getByLabelText("Primary")).not.toBeChecked();expect(screen.getByLabelText("Required")).toBeChecked();await u.click(screen.getByLabelText("Primary"));await u.clear(screen.getByLabelText("Display order"));await u.type(screen.getByLabelText("Display order"),"5");await u.click(screen.getByRole("button",{name:"Save changes"}));expect(api.update).toHaveBeenCalledWith("project-public","services",service,expect.objectContaining({is_primary:true,is_required:true,display_order:5,display_label:"Freight",notes:"note"}));await u.click(screen.getByRole("button",{name:"Deactivate"}));expect(api.active).toHaveBeenCalledWith("project-public","services",service,false)});
  it("creates service flags and surfaces duplicate, primary and optimistic conflicts with refresh",async()=>{const u=userEvent.setup();render(<ProjectConfiguration projectId="p"/>);await screen.findByRole("option",{name:/FREIGHT/});fireEvent.change(screen.getByLabelText("Governed type"),{target:{value:"svc-public"}});await u.click(screen.getByLabelText("Primary"));await u.click(screen.getByLabelText("Required"));api.create.mockRejectedValueOnce(new Error("Duplicate association or one active primary conflict"));await u.click(screen.getByRole("button",{name:"Add"}));expect(await screen.findByRole("alert")).toHaveTextContent(/Duplicate.*primary conflict/);api.create.mockRejectedValueOnce(new Error("VERSION_CONFLICT"));await u.click(screen.getByRole("button",{name:"Add"}));expect(await screen.findByRole("button",{name:"Refresh"})).toBeInTheDocument()});
  it("supports document opaque create/edit/lifecycle and conditional-only description",async()=>{const u=userEvent.setup();api.list.mockImplementation((_p,r)=>Promise.resolve(page(r==="document-requirements"?[document]:[])));render(<ProjectConfiguration projectId="p"/>);await u.click(screen.getByRole("tab",{name:"Documents"}));expect(await screen.findByRole("option",{name:/BOL/})).toHaveValue("doc-public");expect(document).not.toHaveProperty("document_definition_id");fireEvent.change(screen.getByLabelText("Governed type"),{target:{value:"doc-public"}});fireEvent.change(screen.getByLabelText("Requirement level"),{target:{value:"CONDITIONAL"}});await u.type(screen.getByLabelText("Conditional description"),"When needed");await u.click(screen.getByRole("button",{name:"Add"}));expect(api.create).toHaveBeenCalledWith("p","document-requirements",expect.objectContaining({document_definition_public_id:"doc-public",conditional_description:"When needed"}));await u.click(screen.getByRole("button",{name:"Edit Documents item"}));fireEvent.change(screen.getByLabelText("Requirement level"),{target:{value:"REQUIRED"}});expect(screen.queryByLabelText("Conditional description")).not.toBeInTheDocument();await u.click(screen.getByRole("button",{name:"Save changes"}));expect(api.update).toHaveBeenCalledWith("p","document-requirements",document,expect.objectContaining({conditional_description:null}));await u.click(screen.getByRole("button",{name:"Deactivate"}));expect(api.active).toHaveBeenCalled()});
  it("supports milestone fields, point editing, validation, lifecycle and mixed-state reorder",async()=>{const u=userEvent.setup();const inactive={...milestone,public_id:"inactive",is_active:false,sequence:99};const second={...milestone,public_id:"second",sequence:2};api.list.mockImplementation((_p,r)=>Promise.resolve(page(r==="milestone-definitions"?[milestone,inactive,second]:[])));render(<ProjectConfiguration projectId="p"/>);await u.click(screen.getByRole("tab",{name:"Milestones"}));expect(await screen.findByText("Project configuration does not create operational milestones.")).toBeInTheDocument();await u.click(screen.getAllByRole("button",{name:"Edit Milestones item"})[0]);expect(screen.getByLabelText("Project logistics point")).toHaveValue("point-public");fireEvent.change(screen.getByLabelText("Target duration"),{target:{value:"5"}});fireEvent.change(screen.getByLabelText("Warning duration"),{target:{value:"4"}});await u.click(screen.getByRole("button",{name:"Save changes"}));expect(await screen.findByRole("alert")).toHaveTextContent(/greater than or equal/);fireEvent.change(screen.getByLabelText("Warning duration"),{target:{value:"6"}});fireEvent.change(screen.getByLabelText("Duration unit"),{target:{value:"DAY"}});await u.click(screen.getByRole("button",{name:"Save changes"}));expect(api.update).toHaveBeenCalledWith("p","milestone-definitions",milestone,expect.objectContaining({target_duration_value:5,warning_duration_value:6,duration_unit:"DAY",project_logistics_point_public_id:"point-public"}));await u.click(screen.getAllByRole("button",{name:"Move milestone down"})[0]);expect(api.reorder).toHaveBeenCalledWith("p",[second,milestone]);expect(api.reorder.mock.calls[0][1]).not.toContainEqual(expect.objectContaining({public_id:"inactive"}));await u.click(screen.getByRole("button",{name:"Activate"}));expect(api.active).toHaveBeenCalledWith("p","milestone-definitions",inactive,true)});
  it("shows selector loading and empty states",async()=>{let resolve!: (v:ReturnType<typeof page>)=>void;api.services.mockReturnValueOnce(new Promise(r=>{resolve=r}));render(<ProjectConfiguration projectId="p"/>);expect(await screen.findByRole("option",{name:"Loading options…"})).toBeDisabled();resolve(page());expect(await screen.findByRole("option",{name:"No active options"})).toBeInTheDocument()});
  it("shows selector errors and a reload action",async()=>{api.services.mockRejectedValueOnce(new Error("selector failed"));render(<ProjectConfiguration projectId="p"/>);expect(await screen.findByRole("alert")).toHaveTextContent("selector failed");expect(screen.getByRole("button",{name:"Refresh"})).toBeInTheDocument()});
  it("renders read-only without mutating actions",async()=>{render(<ProjectConfiguration projectId="p" canManage={false}/>);expect(await screen.findByText("Read-only access")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Add"})).not.toBeInTheDocument()});
  it.each([[390,"fa","rtl"],[412,"fa","rtl"],[1280,"en","ltr"]] as const)("is responsive at %ipx with %s direction",async(width,locale,dir)=>{Object.defineProperty(window,"innerWidth",{value:width,configurable:true});const {container}=render(<ProjectConfiguration projectId="p" locale={locale}/>);const section=container.querySelector("section")!;expect(section).toHaveAttribute("dir",dir);expect(section).toHaveClass("overflow-x-hidden");expect(await screen.findByRole("button",{name:"Add"})).not.toHaveAttribute("tabindex","-1");expect(within(section).getByRole("tab",{name:"Network"})).toHaveAccessibleName()});
  it("preserves the single existing network component",async()=>{const u=userEvent.setup();render(<ProjectConfiguration projectId="p"/>);await u.click(screen.getByRole("tab",{name:"Network"}));expect(await screen.findByText(/Network 1.7.0 create update lifecycle reorder/)).toBeInTheDocument();expect(screen.getAllByText(/Network 1.7.0/)).toHaveLength(1)});
});
