#requires -Version 5.1
<#! Immutable-runtime deployment entrypoint. It is inert without both switches. #>
[CmdletBinding()]
param([switch]$Execute,[switch]$ConfirmDeployment,[Parameter(Mandatory=$true)][string]$ApplicationZip,[Parameter(Mandatory=$true)][string]$ApplicationManifest,[Parameter(Mandatory=$true)][string]$RuntimeZip,[Parameter(Mandatory=$true)][string]$RuntimeManifest,[Parameter(Mandatory=$true)][string]$ProductionRoot,[Parameter(Mandatory=$true)][string]$RuntimeRoot,[Parameter(Mandatory=$true)][string]$PreflightEvidencePath,[Parameter(Mandatory=$true)][string]$BackupEvidencePath,[string]$TaskName='Forwarder Backend Production',[string]$SiteName='forwarder',[int]$Port=5101,[string]$PsqlPath='')
$ErrorActionPreference='Stop'
$Candidate='S7-RC-a257669-rg1-frozen';$Source='a2576690364fcaf58ca7ddc6c57143c3084bbb00';$AppHash='aca7a147cad97edf0e3f03d763c63471c283f62021a23a4e6a47b5e59aa88534';$RuntimeId='Forwarder-Windows-Runtime-S7-RC-a257669-r4';$TargetHead='20260908_governed_international_geography'
function Stop([string]$m){throw "DEPLOYMENT_STOP: $m"}; function Need([bool]$ok,[string]$m){if(-not $ok){Stop $m}}; function Hash([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Listener([string]$release,[switch]$AllowAbsent){$c=@(Get-NetTCPConnection -LocalAddress 127.0.0.1 -LocalPort $Port -State Listen -ErrorAction SilentlyContinue);if($c.Count -eq 0 -and $AllowAbsent){return $null};Need ($c.Count -eq 1) 'listener is not singular';$p=Get-CimInstance Win32_Process -Filter "ProcessId=$($c[0].OwningProcess)"; $python=Join-Path $release 'runtime\python.exe';Need ($p.CommandLine -like "*$python*") 'listener does not belong to governed runtime';Need ($p.CommandLine -match '(?i)-m\s+waitress') 'listener is not waitress';return $p}
function StopExact([string]$release){Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;$p=Listener $release -AllowAbsent;if($null -ne $p){Stop-Process -Id ([int]$p.ProcessId) -Force;Write-Output "STOPPED_EXACT_PID=$($p.ProcessId)"}}
function VerifyRuntime([string]$root){$python=Join-Path $root 'runtime\python.exe';Need (Test-Path -LiteralPath $python -PathType Leaf) 'candidate runtime python.exe absent';$out=& $python -c "import psycopg2,waitress,alembic;print('RUNTIME_MODULES=PASS')" 2>&1;Need ($LASTEXITCODE -eq 0 -and ($out -join "`n") -match 'RUNTIME_MODULES=PASS') 'runtime module proof failed';return $python}
Need ($Execute -and $ConfirmDeployment) 'explicit -Execute -ConfirmDeployment is required';Need (Test-Path $PreflightEvidencePath) 'approved read-only preflight evidence absent';Need (Test-Path $BackupEvidencePath) 'approved backup evidence absent';$preflight=Get-Content -Raw $PreflightEvidencePath|ConvertFrom-Json;Need ($preflight.database.alembic_revision -eq '20260907_direct_shipment_responsibility') 'DB predecessor Alembic mismatch';Need ($preflight.database.database -eq 'forwarder_prod_20260728_161711') 'DB identity mismatch';Need ((Hash $ApplicationZip) -eq $AppHash) 'application ZIP hash mismatch';Need (Test-Path $ApplicationManifest) 'application manifest absent';Need (Test-Path $RuntimeManifest) 'runtime manifest absent';$rm=Get-Content -Raw $RuntimeManifest|ConvertFrom-Json;Need ($rm.runtime_id -eq $RuntimeId) 'runtime ID mismatch';Need ((Hash $RuntimeZip) -eq $rm.artifact_sha256) 'runtime ZIP hash mismatch';Need ($rm.python_version -eq '3.12.6') 'runtime Python version mismatch'
$target=Join-Path $ProductionRoot ('release-'+$Candidate);Need (-not (Test-Path $target)) 'target path collision';Import-Module WebAdministration -ErrorAction Stop;$previous=[string](Get-ItemProperty "IIS:\Sites\$SiteName" -Name physicalPath).physicalPath;Need (Test-Path $previous) 'previous IIS release absent';$taskXml=Export-ScheduledTask -TaskName $TaskName;Need ($taskXml -match [regex]::Escape($previous)) 'task does not reference previous release';$old=Listener $previous
Write-Output 'PRECHECK_COMPLETE';Write-Output 'READY_FOR_FIRST_MUTATION'
$taskBackup=Join-Path $RuntimeRoot ("$TaskName.$Candidate.rollback.xml");$iisBackup=$previous
try {Export-ScheduledTask -TaskName $TaskName|Set-Content -LiteralPath $taskBackup -Encoding UTF8;Expand-Archive -LiteralPath $ApplicationZip -DestinationPath $target -ErrorAction Stop;Expand-Archive -LiteralPath $RuntimeZip -DestinationPath (Join-Path $target 'runtime') -ErrorAction Stop;$releaseManifest=Get-Content -Raw (Join-Path $target 'release-manifest.json')|ConvertFrom-Json;Need ($releaseManifest.application_source_commit -eq $Source) 'source SHA mismatch';Need ($releaseManifest.migration_head -eq $TargetHead) 'Alembic head mismatch';$python=VerifyRuntime $target;Push-Location $target;try{& $python -m alembic upgrade $TargetHead;Need ($LASTEXITCODE -eq 0) 'candidate runtime migration failed'}finally{Pop-Location};StopExact $previous;$newXml=$taskXml.Replace($previous,$target);Need ($newXml -match [regex]::Escape($python)) 'task does not reference candidate runtime';Register-ScheduledTask -TaskName $TaskName -Xml $newXml -Force|Out-Null;Set-ItemProperty "IIS:\Sites\$SiteName" -Name physicalPath -Value (Join-Path $target 'dist');Start-ScheduledTask -TaskName $TaskName;Start-Sleep -Seconds 2;Listener $target|Out-Null;Write-Output 'DEPLOYED_AND_VERIFIED'}catch {Register-ScheduledTask -TaskName $TaskName -Xml (Get-Content -Raw $taskBackup) -Force|Out-Null;Set-ItemProperty "IIS:\Sites\$SiteName" -Name physicalPath -Value $iisBackup;StopExact $target;Start-ScheduledTask -TaskName $TaskName;Listener $previous|Out-Null;Write-Output 'ROLLBACK=PREVIOUS_APPLICATION_RUNTIME;DB=UPGRADED_NO_DOWNGRADE';throw}
