import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
const password=process.env.FORWARDER_E2E_PASSWORD, fixturePath=process.env.FORWARDER_E2E_FIXTURE_PATH;
if(!password||!fixturePath)throw new Error("Party Role qualification must be launched by its local runner.");
const fixture=JSON.parse(readFileSync(fixturePath,"utf8")) as Record<string,string|number>;
type Evidence={console:string[];page:string[];failed:string[];normal:string[];protected:string[]};
function observe(page:Page){const e:Evidence={console:[],page:[],failed:[],normal:[],protected:[]};page.on("console",m=>{if(m.type()==="error"&&!m.text().includes("favicon"))e.console.push(m.text())});page.on("pageerror",x=>e.page.push(x.message));page.on("requestfailed",r=>e.failed.push(`${r.method()} ${r.url()}`));page.on("response",r=>{if(r.url().includes("/api/")&&r.status()>=400){const v=`${r.status()} ${r.request().method()} ${r.url()}`;(r.url().includes("operational-roles")?e.protected:e.normal).push(v)}});return e}
function clean(e:Evidence){expect(e.console).toEqual([]);expect(e.page).toEqual([]);expect(e.failed).toEqual([]);expect(e.normal).toEqual([])}
async function login(page:Page,persona="operator"){await page.goto("/");await page.getByRole("button",{name:"ورود به سامانه"}).first().click();await page.getByLabel("نام کاربری").fill(`shared_transport_e2e_${persona}`);await page.getByLabel("رمز عبور").fill(password!);await page.getByRole("dialog").getByRole("button",{name:"ورود",exact:true}).click();await expect(page).not.toHaveURL(/\/$/)}
async function headers(page:Page){return page.evaluate(()=>({Authorization:`Bearer ${localStorage.getItem("expert_token")||""}`}))}
async function roles(page:Page){await page.goto("/admin");await page.goto("/admin/customers");await expect(page.getByRole("heading",{name:"مشتریان و صلاحیت‌های عملیاتی"})).toBeVisible()}
const role=(p:Page,n:string)=>p.locator(`input[aria-label="کریر / حمل‌کننده برای [SHARED-E2E] ${n}"]`);
async function setRole(p:Page,n:string,on:boolean){const b=role(p,n);if(on)await expect(b).not.toBeChecked();else await expect(b).toBeChecked();const saved=p.waitForResponse(r=>r.request().method()==="PUT"&&r.url().includes("/operational-roles/carrier"));await b.click();expect((await saved).status()).toBe(200);if(on)await expect(b).toBeChecked();else await expect(b).not.toBeChecked()}
async function unit(p:Page){await p.goto(`/operations/projects/${fixture.project_a}/units`);await p.getByRole("button",{name:"مشاهده"}).first().click();await expect(p.getByLabel("انتخاب کریر")).toBeVisible()}
async function track(p:Page){const r=await p.request.get(`/api/internal/operational-shipments/${fixture.shipment_a}/transport-tracking`,{headers:await headers(p)});expect(r.status()).toBe(200);return r.json() as Promise<{tracking:{units:Array<{carrier:string|null}>}}>}
async function carrier(p:Page,label:string){await p.getByLabel("انتخاب کریر").selectOption(label?{label}:"");await p.getByRole("button",{name:"ذخیره کریر"}).click()}
async function allocate(p:Page){const s=p.getByLabel("انتخاب بار قابل تخصیص");const value=await s.locator("option").filter({hasText:"Cargo A"}).getAttribute("value");expect(value).toBeTruthy();await s.selectOption(value!);await p.getByRole("button",{name:"تخصیص بار"}).click()}

test.describe.serial("PR-02 complete browser qualification",()=>{
test("R — Organization Admin role lifecycle, persistence, and language",async({page})=>{const e=observe(page);await login(page);await roles(page);await expect(role(page,"Customer A")).not.toBeChecked();await expect(role(page,"Customer B")).toBeChecked();await expect(role(page,"Customer C")).toBeChecked();const text=await page.locator("main").innerText();for(const x of ["CARRIER","role_code","CustomerRoleAssignment","database"])expect(text).not.toContain(x);await setRole(page,"Customer A",true);await page.reload();await expect(role(page,"Customer A")).toBeChecked();await roles(page);await expect(role(page,"Customer A")).toBeChecked();await setRole(page,"Customer A",false);await page.reload();await expect(role(page,"Customer A")).not.toBeChecked();await roles(page);await setRole(page,"Customer A",true);await page.reload();await expect(role(page,"Customer A")).toBeChecked();clean(e)});
test("ND + selector — removal preserves history and filters new choices",async({page})=>{const e=observe(page);await login(page);await unit(page);await allocate(page);await carrier(page,"[SHARED-E2E] Customer B");await page.reload();await unit(page);await expect(page.getByText(/کریر:.*Customer B/)).toBeVisible();await roles(page);await setRole(page,"Customer B",false);await page.reload();await expect(role(page,"Customer B")).not.toBeChecked();const optionPath=`/api/v2/projects/${fixture.project_a}/execution-units/${fixture.unit}/carrier-options`;const direct=await page.request.get(`${optionPath}?qualification=${Date.now()}`,{headers:await headers(page)});expect(direct.status()).toBe(200);const directIds=(await direct.json() as {data:Array<{id:number}>}).data.map(x=>x.id);expect(directIds).not.toContain(fixture.owner_b_id);const network=page.waitForResponse(r=>r.url().includes(`/execution-units/${fixture.unit}/carrier-options`));await unit(page);const browserIds=(await (await network).json() as {data:Array<{id:number}>}).data.map(x=>x.id);expect(browserIds).not.toContain(fixture.owner_b_id);const choices=(await page.getByLabel("انتخاب کریر").locator("option").allTextContents()).join(" ");for(const x of ["Customer B","Customer D","Foreign Carrier"])expect(choices).not.toContain(x);expect(choices).toContain("Customer A");expect(choices).toContain("Customer C");await expect(page.getByText(/کریر:.*Customer B/)).toBeVisible();expect((await track(page)).tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({carrier:"[SHARED-E2E] Customer B"})]));await roles(page);await setRole(page,"Customer B",true);clean(e)});
test("dual role, carrier lifecycle, Tracking, and Cargo Owner regression",async({page})=>{const e=observe(page);await login(page);await unit(page);const choices=(await page.getByLabel("انتخاب کریر").locator("option").allTextContents()).join(" ");expect(choices).toContain("Customer B");expect(choices).toContain("Customer C");await carrier(page,"[SHARED-E2E] Customer B");await page.reload();await unit(page);expect((await track(page)).tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({carrier:"[SHARED-E2E] Customer B"})]));await carrier(page,"[SHARED-E2E] Customer C");await page.reload();await unit(page);await expect(page.getByText(/کریر:.*Customer C/)).toBeVisible();expect((await track(page)).tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({carrier:"[SHARED-E2E] Customer C"})]));await page.goto(`/operations/shipments/${fixture.shipment_c}`);const cargo=page.getByRole("article").filter({hasText:"Cargo C"});await expect(cargo).toContainText("Customer C");const owners=(await cargo.getByLabel("Cargo owner line 1").locator("option").allTextContents()).join(" ");expect(owners).toContain("Customer A");expect(owners).toContain("Customer C");await unit(page);await carrier(page,"");await page.reload();expect((await track(page)).tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({carrier:null})]));clean(e)});
test("Expert denial has no eager protected fetch and retains normal operations",async({page})=>{const e=observe(page);await login(page,"restricted");await page.goto("/admin/customers");await expect(page.getByRole("heading",{name:"مشتریان و صلاحیت‌های عملیاتی"})).toHaveCount(0);expect(e.protected).toEqual([]);const r=await page.request.put(`/api/crm/customers/${fixture.owner_a_id}/operational-roles/carrier`,{headers:await headers(page),data:{eligible:true}});expect(r.status()).toBe(403);await unit(page);await expect(page.getByLabel("انتخاب کریر")).toBeVisible();clean(e)});
test("business_expert is a legacy role, not a canonical runtime authority",async({page})=>{const e=observe(page);await login(page,"restricted");const user=await page.evaluate(()=>JSON.parse(localStorage.getItem("expert_user")||"{}"));expect(user.authority).toBe("EXPERT");expect(user.role).toBe("expert");await page.goto("/admin/customers");expect(e.protected).toEqual([]);clean(e)});
test("Platform Admin has no tenant role-management journey or tenant leakage",async({page})=>{const e=observe(page);await login(page,"platform");await page.goto("/admin/customers");await expect(page.getByRole("heading",{name:"مشتریان و صلاحیت‌های عملیاتی"})).toHaveCount(0);expect(e.protected).toEqual([]);const r=await page.request.put(`/api/crm/customers/${fixture.owner_a_id}/operational-roles/carrier`,{headers:await headers(page),data:{eligible:true}});expect(r.status()).toBe(403);expect(await r.text()).not.toContain("Customer A");await page.goto("/operations/shipments");await expect(page.getByText("[SHARED-E2E] Customer A")).toHaveCount(0);clean(e)});
test("tenant isolation denies mutation without data leakage",async({page})=>{const e=observe(page);await login(page);await roles(page);expect(await page.locator("main").innerText()).not.toContain("Foreign Carrier");const r=await page.request.put(`/api/crm/customers/${fixture.foreign_carrier_id}/operational-roles/carrier`,{headers:await headers(page),data:{eligible:false}});expect([403,404]).toContain(r.status());expect(await r.text()).not.toContain("Foreign Carrier");clean(e)});
test("Shipment List, Work Queue, and Control Tower reality regressions",async({page})=>{const e=observe(page);await login(page);const api=await page.request.get("/api/operational-shipments",{headers:await headers(page)});expect(api.status()).toBe(200);const payload=await api.json() as {data:Array<{public_id:string}>};expect(payload.data.some(x=>x.public_id===fixture.shipment_a)).toBeTruthy();await page.goto("/operations/shipments");const cards=page.getByRole("link",{name:/مشاهده محموله عملیاتی/});await expect(cards).toHaveCount(payload.data.length);expect(await cards.count()).toBeGreaterThan(0);await page.reload();await expect(cards).toHaveCount(payload.data.length);await expect(page.getByText("محموله عملیاتی منطبق با فیلترها یافت نشد. فیلترها را پاک کنید یا نخستین محموله عملیاتی را ایجاد کنید.")).toHaveCount(0);clean(e);const restricted=await page.context().newPage();const re=observe(restricted);await login(restricted,"restricted");await restricted.goto("/operations/shipments");await expect(restricted.getByRole("link",{name:"صف کار برج کنترل"})).toHaveCount(0);expect(re.normal.filter(x=>x.includes("work-queue")||x.includes("attention"))).toEqual([]);clean(re);await restricted.close();const tower=await page.context().newPage();const te=observe(tower);await login(tower);await tower.goto("/operations/control-tower");const text=await tower.locator("main").innerText();for(const x of ["PARTIAL_DIMENSION_COVERAGE","semantic_version","query_kind","metric_keys","dimension_keys","coverage_percent","eligible_count"])expect(text).not.toContain(x);clean(te);await tower.close()});
});
