import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";
const password = process.env.FORWARDER_E2E_PASSWORD;
const fixturePath = process.env.FORWARDER_E2E_FIXTURE_PATH;
if (!password || !fixturePath) throw new Error("P3-08 requires an owned synthetic fixture");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as { p304_shipment: string; p305_cargo: string; p308_cargo_b: string; p308_status: string };
test.setTimeout(180_000);

async function openDeliveries(page: Page) {
  await page.getByRole("link", { name: "پرونده‌های عملیاتی حمل", exact: true }).click();
  await page.locator(`a[href="/operations/shipments/${fixture.p304_shipment}"]`).click();
  await page.locator("summary", { hasText: "تحویل کالاها" }).click();
  return page.getByRole("region", { name: "تحویل کالاها" });
}

test("P3-08 normal Chrome partial delivery, correction, exact evidence, excess and reopen", async ({ page }) => {
  await page.route("https://fonts.googleapis.com/**", route => route.fulfill({ status: 200, contentType: "text/css", body: "" }));
  await page.route("https://fonts.gstatic.com/**", route => route.fulfill({ status: 204, body: "" }));
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "ورود به سامانه" }).first().click();
  await page.getByLabel("نام کاربری").fill("shared_transport_e2e_restricted");
  await page.getByLabel("رمز عبور").fill(password!);
  await page.getByRole("dialog").getByRole("button", { name: "ورود", exact: true }).click();
  let delivery = await openDeliveries(page);
  const token = await page.evaluate(() => localStorage.getItem("expert_token"));
  const headers = { Authorization: `Bearer ${token}` };
  const before = await page.request.get(`/api/operational-shipments/${fixture.p304_shipment}`, { headers });
  expect(before.status()).toBe(200);
  const beforeShipment = (await before.json()).data;
  let firstId = "";
  for (const quantity of ["60", "35"]) {
    await delivery.getByRole("button", { name: "تحویل تازه برای قطعات موتور", exact: true }).click();
    await delivery.getByLabel("مقدار تحویل", { exact: true }).fill(quantity);
    await delivery.getByLabel("مقصد تحویل", { exact: true }).fill("انبار مشتری اول");
    await delivery.getByLabel("زمان وقوع تحویل").fill("2026-09-21T10:30");
    const saved = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/deliveries"));
    await delivery.getByRole("button", { name: "ثبت تحویل", exact: true }).click();
    const response = await saved; expect(response.status()).toBe(201);
    if (!firstId) firstId = (await response.json()).public_id;
    await expect(delivery.getByRole("status")).toHaveText("تحویل ثبت شد؛ وضعیت پرونده حمل تغییری نکرد.");
  }
  await expect(delivery.locator(`[data-delivery-cargo="${fixture.p305_cargo}"]`)).toContainText("۹۵ کارتن");
  await expect(delivery.getByText(/۵ کارتن هنوز تحویل ثبت‌شده ندارد/)).toBeVisible();
  await expect(delivery.locator(`[data-delivery-cargo="${fixture.p308_cargo_b}"]`)).toContainText("هنوز تحویلی ثبت نشده است.");
  await delivery.locator(`[data-delivery-id="${firstId}"]`).getByRole("button", { name: "اصلاح تحویل", exact: true }).click();
  await delivery.getByLabel("مقدار تحویل", { exact: true }).fill("58");
  await delivery.getByLabel("دلیل اصلاح تحویل").fill("بازشماری رسید");
  const corrected = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/deliveries"));
  await delivery.getByRole("button", { name: "ثبت اصلاح تحویل", exact: true }).click();
  const correctionResponse = await corrected; expect(correctionResponse.status()).toBe(201);
  const correctedId = (await correctionResponse.json()).public_id;
  await expect(delivery.getByText(/۷ کارتن هنوز تحویل ثبت‌شده ندارد/)).toBeVisible();
  let current = delivery.locator(`[data-delivery-id="${correctedId}"]`);
  await current.locator("summary", { hasText: "افزودن مدرک تحویل" }).click();
  const bytes = Buffer.from("%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF");
  await current.getByLabel("فایل مدرک تحویل").setInputFiles({ name: "delivery-receipt.pdf", mimeType: "application/pdf", buffer: bytes });
  const uploaded = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/documents"));
  await current.getByRole("button", { name: "ثبت مدرک تحویل", exact: true }).click();
  const uploadResponse = await uploaded; expect(uploadResponse.status()).toBe(201);
  const document = (await uploadResponse.json()).data;
  expect(document.context.type).toBe("DELIVERY"); expect(document.context.target_public_id).toBe(correctedId);
  expect(document.version).toBe(1); expect(document.context.visibility).toBe("INTERNAL");
  await expect(current.getByRole("button", { name: "دریافت مدرک" })).toBeVisible();
  const downloaded = page.waitForEvent("download");
  await current.getByRole("button", { name: "دریافت مدرک" }).click();
  const download = await downloaded; expect(download.suggestedFilename()).toBe("delivery-receipt.pdf");
  expect(readFileSync((await download.path())!)).toEqual(bytes);
  await delivery.getByRole("button", { name: "تحویل تازه برای قطعات موتور", exact: true }).click();
  await delivery.getByLabel("مقدار تحویل", { exact: true }).fill("9");
  await delivery.getByLabel("مقصد تحویل", { exact: true }).fill("انبار مشتری اول");
  await delivery.getByLabel("زمان وقوع تحویل").fill("2026-09-22T10:30");
  await delivery.getByRole("button", { name: "ثبت تحویل", exact: true }).click();
  await expect(delivery.getByRole("alert")).toContainText("۲ کارتن بیش از مقدار واقعی شناخته‌شده");
  delivery = await openDeliveries(page);
  await expect(delivery.getByRole("alert")).toContainText("۲ کارتن بیش از مقدار واقعی شناخته‌شده");
  await delivery.locator("summary", { hasText: "سابقه تحویل‌های اصلاح‌شده" }).click();
  await expect(delivery.locator(`[data-delivery-id="${firstId}"]`)).toContainText("۶۰ کارتن");
  current = delivery.locator(`[data-delivery-id="${correctedId}"]`);
  await expect(current).toContainText("۵۸ کارتن"); await expect(current).toContainText("دلیل اصلاح: بازشماری رسید");
  await expect(current.getByRole("button", { name: "دریافت مدرک" })).toBeVisible();
  await expect(delivery.locator(`[data-delivery-cargo="${fixture.p308_cargo_b}"]`)).toContainText("۲۵ کارتن");
  const response = await page.request.get(`/api/operational-shipments/${fixture.p304_shipment}`, { headers });
  expect(response.status()).toBe(200);
  const shipment = await response.json();
  expect(shipment.data.status).toBe(beforeShipment.status);
  expect(shipment.data.version).toBe(beforeShipment.version);
  await delivery.evaluate(node => node.scrollIntoView({ block: "start" })); await page.evaluate(() => window.scrollBy(0, -180));
  await page.screenshot({ path: test.info().outputPath("cargo-delivery-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await delivery.evaluate(node => node.scrollIntoView({ block: "start" })); await page.evaluate(() => window.scrollBy(0, -180));
  await page.screenshot({ path: test.info().outputPath("cargo-delivery-mobile.png") });
  expect(errors).toEqual([]);
});
