import { expect, test, type Page } from "@playwright/test";
import { readFileSync } from "node:fs";

const password = process.env.FORWARDER_E2E_PASSWORD;
const fixturePath = process.env.FORWARDER_E2E_FIXTURE_PATH;
if (!password || !fixturePath) throw new Error("Shared Transport qualification must be launched by its local runner.");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));
type Evidence = { console: string[]; page: string[]; network: string[] };
type SharedTransportAllocation = { public_id: string; description: string; shipment_public_id: string; project: { public_id: string }; cargo_owner: { public_label: string } | null };
type SharedTransportResponse = { data: { allocations: SharedTransportAllocation[]; summary: { cargo_owner_count: number; classification: string } } };
function observe(page: Page): Evidence { const e: Evidence={console:[],page:[],network:[]}; page.on("console",x=>{if(x.type()==="error"&&!x.text().includes("favicon"))e.console.push(x.text())}); page.on("pageerror",x=>e.page.push(x.message)); page.on("response",x=>{if(x.url().includes("/api/")&&x.status()>=400)e.network.push(`${x.status()} ${x.url()}`)}); return e; }
function clean(e: Evidence) { expect(e.console,"console errors").toEqual([]); expect(e.page,"page errors").toEqual([]); expect(e.network,"failed normal requests").toEqual([]); }
async function login(page: Page, persona="operator") { await page.goto("/"); await page.getByRole("button",{name:"ورود به سامانه"}).first().click(); await page.getByLabel("نام کاربری").fill(`shared_transport_e2e_${persona}`); await page.getByLabel("رمز عبور").fill(password!); await page.getByRole("dialog").getByRole("button",{name:"ورود",exact:true}).click(); await expect(page).not.toHaveURL(/\/$/); }
function headers(page: Page) { return page.evaluate(()=>({Authorization:`Bearer ${localStorage.getItem("expert_token")||""}`})); }
async function api(page: Page, method:"GET"|"POST"|"PATCH"|"DELETE", path:string, data?:unknown, project=fixture.project_a, unit=fixture.unit) { return page.request.fetch(`/api/v2/projects/${project}/execution-units/${unit}${path}`,{method,headers:await headers(page),data}); }
async function openUnit(page: Page, project=fixture.project_a, code?:string) { await page.goto(`/operations/projects/${project}/units`); const button=code?page.getByRole("row").filter({hasText:code}).getByRole("button",{name:"مشاهده"}):page.getByRole("button",{name:"مشاهده"}); await button.click(); await expect(page.getByText("بارهای اجرای مشترک")).toBeVisible(); }
async function reopenUnit(page: Page, code?:string) { await page.reload(); const button=code?page.getByRole("row").filter({hasText:code}).getByRole("button",{name:"مشاهده"}):page.getByRole("button",{name:"مشاهده"}); await button.click(); await expect(page.getByText("بارهای اجرای مشترک")).toBeVisible(); }
async function shipment(page: Page,id:string) { await page.goto(`/operations/shipments/${id}`); await expect(page.getByText("کالا و وسایل حمل")).toBeVisible(); }
async function body(page: Page) { return page.locator("body").innerText(); }
async function tracking(page: Page, shipmentId: string) {
  return (await page.request.get(`/api/internal/operational-shipments/${shipmentId}/transport-tracking`, {headers: await headers(page)})).json() as Promise<{tracking:{units:Array<{source:string;unit_code:string;allocated_cargo:Array<{cargo_name:string;cargo_owner:string}>}>}}>;
}
async function allocate(page: Page, cargoId: string) {
  const selector = page.getByLabel("انتخاب بار قابل تخصیص");
  await selector.selectOption(cargoId);
  const cargoLabel = (await selector.locator("option:checked").textContent())?.trim();
  if (!cargoLabel) throw new Error(`Allocation candidate ${cargoId} has no rendered label.`);
  const cargoDescription = cargoLabel.split("·", 1)[0].trim();
  const responsePromise = page.waitForResponse(response => {
    const request = response.request();
    if (request.method() !== "POST" || !new URL(response.url()).pathname.endsWith("/allocations")) return false;
    try { return request.postDataJSON()?.cargo_public_id === cargoId; }
    catch { return false; }
  });

  await page.getByRole("button", {name: "تخصیص بار"}).click();
  const response = await responsePromise;
  expect(response.status(), `Allocation mutation failed for ${cargoId}: ${await response.text()}`).toBe(201);

  // The mutation refresh replaces this subtree. Reacquire locators and require
  // Cargo-specific evidence from both refreshed surfaces before returning.
  await expect(
    page.getByLabel("انتخاب بار قابل تخصیص").getByRole("option", {name: cargoLabel, exact: true}),
    `Allocated Cargo ${cargoId} remained eligible after the mutation`,
  ).toHaveCount(0);
  await expect(
    page.getByRole("listitem").filter({hasText: cargoDescription}),
    `Allocated Cargo ${cargoId} did not appear in the execution allocation list`,
  ).toBeVisible();
}

test.describe.serial("Shared Transport A-I executable acceptance",()=>{
 test("PR01 - seeded accessible shipments appear in the operational list",async({page})=>{const e=observe(page);await login(page);const response=await page.request.get("/api/operational-shipments",{headers:await headers(page)});expect(response.status()).toBe(200);const result=await response.json() as SharedTransportResponse & {data:Array<{public_id:string}>};expect(result.data.some(row=>row.public_id===fixture.shipment_a)).toBeTruthy();await page.goto("/operations/shipments");await expect(page.getByRole("link",{name:/Customer A/})).toBeVisible();clean(e);});
 test("A - legacy compatibility",async({page})=>{const e=observe(page);await login(page);await shipment(page,fixture.legacy_only_shipment);const legacyA1=page.getByRole("article").filter({hasText:"SHARED-E2E-LEGACY-A1"});await expect(legacyA1).toBeVisible();await expect(legacyA1.getByText("سابقه حمل")).toBeVisible();await page.reload();await expect(page.getByRole("article").filter({hasText:"SHARED-E2E-LEGACY-A1"})).toBeVisible();await shipment(page,fixture.legacy_canonical_shipment);await expect(page.getByRole("article").filter({hasText:"SHARED-E2E-LEGACY-A2"})).toHaveCount(0);await expect(page.getByRole("article").filter({hasText:"SHARED-E2E-LEGACY-CURRENT"})).toBeVisible();await expect(page.getByText("اجرای جاری")).toBeVisible();await page.reload();await expect(page.getByRole("article").filter({hasText:"SHARED-E2E-LEGACY-CURRENT"})).toBeVisible();clean(e);});
 test("B - multi-shipment same owner",async({page})=>{const e=observe(page);await login(page);expect(fixture.cargo_a).not.toBe(fixture.scenario_b_same_owner_cargo);expect(fixture.shipment_a).not.toBe(fixture.scenario_b_same_owner_shipment);expect(fixture.owner_a_id).toBe(fixture.scenario_b_same_owner_customer_id);await openUnit(page);await allocate(page,fixture.cargo_a);await allocate(page,fixture.scenario_b_same_owner_cargo);await expect(page.getByRole("listitem").filter({hasText:"[SHARED-E2E] Cargo A"})).toBeVisible();await expect(page.getByRole("listitem").filter({hasText:"[SHARED-E2E] Scenario B Same Owner Cargo"})).toBeVisible();await expect(page.getByText("چند بار با یک صاحب کالا")).toBeVisible();await expect(page.getByText("multi_cargo_same_owner")).toHaveCount(0);const data=await(await api(page,"GET","/shared-transport")).json() as SharedTransportResponse;expect(data.data.allocations).toHaveLength(2);expect(new Set(data.data.allocations.map((x)=>x.shipment_public_id))).toEqual(new Set([fixture.shipment_a,fixture.scenario_b_same_owner_shipment]));expect(data.data.summary.cargo_owner_count).toBe(1);expect(data.data.summary.classification).toBe("multi_cargo_same_owner");const [a,b]=await Promise.all([tracking(page,fixture.shipment_a),tracking(page,fixture.scenario_b_same_owner_shipment)]);for(const result of [a,b])expect(result.tracking.units.some(u=>u.source==="canonical_execution"&&u.unit_code==="SHARED-E2E-UNIT")).toBeTruthy();await page.reload();await reopenUnit(page);await expect(page.getByRole("listitem").filter({hasText:"[SHARED-E2E] Scenario B Same Owner Cargo"})).toBeVisible();clean(e);const direct=await page.request.get(`/api/v2/projects/${fixture.project_a}/configuration/services?page=1&per_page=100`,{headers:await headers(page)});expect(direct.status()).toBe(403);});
 test("C - multi-project multi-customer and same-name identity",async({page})=>{const e=observe(page);await login(page);await openUnit(page);for(const id of [fixture.cargo_a,fixture.cargo_b])await allocate(page,id);await expect(page.getByText("تجمیع بار چند مشتری")).toBeVisible();await expect(page.getByText("multi_customer_groupage")).toHaveCount(0);let data=await(await api(page,"GET","/shared-transport")).json() as SharedTransportResponse;expect(new Set(data.data.allocations.map(x=>x.project.public_id)).size).toBe(2);expect(data.data.allocations.find(x=>x.description.includes("Cargo A"))).toMatchObject({project:{public_id:fixture.project_a},shipment_public_id:fixture.shipment_a});expect(data.data.allocations.find(x=>x.description.includes("Cargo B"))).toMatchObject({project:{public_id:fixture.project_b},shipment_public_id:fixture.shipment_b});expect(data.data.summary.cargo_owner_count).toBe(2);for(const id of [fixture.cargo_x,fixture.cargo_y])await allocate(page,id);await expect(page.getByRole("listitem").filter({hasText:"[SHARED-E2E] Cargo Y"})).toBeVisible();data=await(await api(page,"GET","/shared-transport")).json() as SharedTransportResponse;expect(data.data.summary.cargo_owner_count).toBe(4);expect(fixture.owner_x_id).not.toBe(fixture.owner_y_id);const sameName=data.data.allocations.filter(x=>x.description.includes("Cargo X")||x.description.includes("Cargo Y"));expect(sameName).toHaveLength(2);expect(sameName.map(x=>x.description).sort()).toEqual(["[SHARED-E2E] Cargo X","[SHARED-E2E] Cargo Y"]);expect(sameName.map(x=>x.cargo_owner?.public_label)).toEqual([fixture.same_owner_name,fixture.same_owner_name]);for(const [cargo,shipmentId] of [["Cargo A",fixture.shipment_a],["Cargo B",fixture.shipment_b],["Cargo X",fixture.shipment_x],["Cargo Y",fixture.shipment_y]] as const){const result=await tracking(page,shipmentId);const unit=result.tracking.units.find(u=>u.source==="canonical_execution"&&u.unit_code==="SHARED-E2E-UNIT");expect(unit).toBeTruthy();expect(unit!.allocated_cargo.some(row=>row.cargo_name.includes(cargo))).toBeTruthy()}await page.reload();await reopenUnit(page);await expect(page.getByRole("listitem").filter({hasText:"[SHARED-E2E] Cargo Y"})).toBeVisible();clean(e);});
 test("D - mixed UOM",async({page})=>{const e=observe(page);await login(page);await openUnit(page);for(const id of [fixture.cargo_a,fixture.cargo_b,fixture.cargo_c])await allocate(page,id);for(const value of ["20.000000 PALLET","8.000000 TON","350.000000 CARTON"])await expect(page.getByRole("listitem").filter({hasText:value})).toBeVisible();const data=await(await api(page,"GET","/shared-transport")).json() as SharedTransportResponse & {data:{allocations:Array<SharedTransportAllocation & {allocated_quantity:string;quantity:string;uom:{code:string}}>}};expect(data.data.allocations.map(x=>`${x.allocated_quantity} ${x.uom.code}`).sort()).toEqual(["20.000000 PALLET","350.000000 CARTON","8.000000 TON"].sort());expect(await body(page)).not.toContain("378");await page.reload();await reopenUnit(page);for(const value of ["20.000000 PALLET","8.000000 TON","350.000000 CARTON"])await expect(page.getByRole("listitem").filter({hasText:value})).toBeVisible();expect(await body(page)).not.toContain("378");clean(e);});
 test("E - cargo owner lifecycle",async({page})=>{const e=observe(page);await login(page);await openUnit(page);await allocate(page,fixture.cargo_a);await shipment(page,fixture.shipment_a);const cargo=page.getByRole("article").filter({hasText:"[SHARED-E2E] Cargo A"}).first(),owner=cargo.getByLabel("Cargo owner line 1");await expect(owner).toHaveValue(String(fixture.owner_a_id));const opts=await owner.locator("option").allTextContents();expect(opts).toContain("[SHARED-E2E] Customer B");expect(opts).not.toContain("[SHARED-E2E] Foreign Customer");await owner.selectOption({label:"[SHARED-E2E] Customer B"});await cargo.getByRole("button",{name:/ذخیره/}).click();await expect(cargo).toContainText("[SHARED-E2E] Customer B");await page.reload();await expect(page.getByRole("article").filter({hasText:"[SHARED-E2E] Cargo A"}).first()).toContainText("[SHARED-E2E] Customer B");const denied=await page.request.patch(`/api/v2/operational-shipments/${fixture.shipment_a}/cargo-items/${fixture.cargo_a}`,{headers:await headers(page),data:{cargo_owner_customer_id:fixture.foreign_owner_id,quantity:"20",version:2}});expect([403,404,422]).toContain(denied.status());expect(await denied.text()).not.toContain("Foreign Customer");await openUnit(page);await expect(page.getByRole("listitem").filter({hasText:"[SHARED-E2E] Cargo A"})).toContainText("[SHARED-E2E] Customer B");expect(JSON.stringify(await tracking(page,fixture.shipment_a))).toContain("[SHARED-E2E] Customer B");await reopenUnit(page);await shipment(page,fixture.shipment_null_owner);await expect(page.getByRole("article").filter({hasText:"Cargo NULL Owner"}).first()).toContainText("نامشخص / ثبت نشده");await expect(page.getByText("وضعیت و پیگیری حمل")).toBeVisible();const historical=await tracking(page,fixture.shipment_null_owner);const historicalUnit=historical.tracking.units.find(unit=>unit.source==="historical_legacy"&&unit.unit_code==="SHARED-E2E-LEGACY-NULL-OWNER");expect(historicalUnit).toBeTruthy();expect(historicalUnit!.allocated_cargo).toEqual(expect.arrayContaining([expect.objectContaining({cargo_name:"[SHARED-E2E] Cargo NULL Owner",cargo_owner:null})]));await expect(page.getByRole("article").filter({hasText:"SHARED-E2E-LEGACY-NULL-OWNER"})).toBeVisible();await page.reload();await expect(page.getByRole("article").filter({hasText:"SHARED-E2E-LEGACY-NULL-OWNER"})).toBeVisible();e.network=[];clean(e);});
 test("F - shipment list route contract",async({page})=>{const e=observe(page);await login(page);const response=await page.request.get("/api/operational-shipments",{headers:await headers(page)});expect(response.status()).toBe(200);const result=await response.json() as {data:Array<{public_id:string}>};expect(result.data.some(row=>row.public_id===fixture.shipment_a)).toBeTruthy();await page.goto("/operations/shipments");await expect(page.getByRole("link",{name:/Customer A/})).toBeVisible();clean(e);});
 test("F-CARRIER - carrier lifecycle",async({page})=>{const e=observe(page);await login(page);await openUnit(page);const carrier=page.getByLabel("انتخاب کریر");await expect(carrier).toHaveValue("");const options=await carrier.locator("option").allTextContents();expect(options).toContain("[SHARED-E2E] Carrier X");expect(options).toContain("[SHARED-E2E] Carrier Y");expect(options).not.toContain("[SHARED-E2E] Foreign Customer");await allocate(page,fixture.cargo_a);await carrier.selectOption({label:"[SHARED-E2E] Carrier X"});await page.getByRole("button",{name:"ذخیره کریر"}).click();await expect(page.getByText(/کریر:.*Carrier X/)).toBeVisible();await reopenUnit(page);await expect(page.getByLabel("انتخاب کریر")).toHaveValue(String(fixture.carrier_id));await expect(page.getByText(/کریر:.*Carrier X/)).toBeVisible();await shipment(page,fixture.shipment_a);await expect(page.getByText(/کریر:.*Carrier X/)).toBeVisible();expect((await tracking(page,fixture.shipment_a)).tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({source:"canonical_execution",unit_code:"SHARED-E2E-UNIT",carrier:"[SHARED-E2E] Carrier X"})]));await openUnit(page);await page.getByLabel("انتخاب کریر").selectOption({label:"[SHARED-E2E] Carrier Y"});await page.getByRole("button",{name:"ذخیره کریر"}).click();await expect(page.getByText(/کریر:.*Carrier Y/)).toBeVisible();await reopenUnit(page);await expect(page.getByLabel("انتخاب کریر")).toHaveValue(String(fixture.carrier_y_id));await expect(page.getByText(/کریر:.*Carrier Y/)).toBeVisible();await shipment(page,fixture.shipment_a);await expect(page.getByText(/کریر:.*Carrier Y/)).toBeVisible();expect((await tracking(page,fixture.shipment_a)).tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({source:"canonical_execution",unit_code:"SHARED-E2E-UNIT",carrier:"[SHARED-E2E] Carrier Y"})]));const denied=await api(page,"PATCH","/carrier",{carrier_customer_id:fixture.foreign_customer_id});expect([403,404]).toContain(denied.status());expect(await denied.text()).not.toContain("Foreign Customer");await openUnit(page);await page.getByLabel("انتخاب کریر").selectOption("");await page.getByRole("button",{name:"ذخیره کریر"}).click();await reopenUnit(page);await expect(page.getByLabel("انتخاب کریر")).toHaveValue("");await expect(page.getByText(/کریر: انتخاب نشده/)).toBeVisible();await shipment(page,fixture.shipment_a);await expect(page.getByText(/کریر:/)).toHaveCount(0);expect((await tracking(page,fixture.shipment_a)).tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({source:"canonical_execution",unit_code:"SHARED-E2E-UNIT",carrier:null})]));e.network=[];clean(e);});
 test("G - restricted actor",async({page})=>{const e=observe(page);await login(page,"restricted");
  // ProjectAccess governs Project-derived data. Carrier/owner selectors are tenant-scoped
  // and deliberately have no G-negative assertion.
  const projects=await page.request.get("/api/operations/selectors/projects?limit=100",{headers:await headers(page)});expect(projects.status()).toBe(200);const projectText=await projects.text();expect(projectText).toContain(fixture.project_a);expect(projectText).not.toContain(fixture.project_b);
  await openUnit(page);const text=await body(page),choices=(await page.getByLabel("انتخاب بار قابل تخصیص").locator("option").allTextContents()).join(" ");expect(text).toContain("Cargo A");expect(choices).toContain("Cargo A");expect(choices).not.toContain("Cargo B");expect(text).not.toContain("Cargo B");
  await allocate(page,fixture.cargo_a);await expect(page.getByRole("listitem").filter({hasText:"Cargo A"})).toBeVisible();await shipment(page,fixture.shipment_a);await expect(page.getByRole("article").filter({hasText:"Cargo A"}).first()).toBeVisible();expect((await tracking(page,fixture.shipment_a)).tracking.enabled).toBeTruthy();
  clean(e); // The authorized browser journey must not eagerly fetch hidden Project B data.
  const forbidden=[
    await page.request.get(`/api/operational-shipments/${fixture.shipment_b}`,{headers:await headers(page)}),
    await page.request.get(`/api/internal/operational-shipments/${fixture.shipment_b}/cargo-items/${fixture.cargo_b}`,{headers:await headers(page)}),
    await page.request.get(`/api/internal/operational-shipments/${fixture.shipment_b}/transport-tracking`,{headers:await headers(page)}),
    await api(page,"GET","/shared-transport",undefined,fixture.project_b,fixture.unit),
    await api(page,"POST","/allocations",{cargo_public_id:fixture.cargo_b,allocated_quantity:"1"}),
    await page.request.patch(`/api/internal/operational-shipments/${fixture.shipment_b}/cargo-items/${fixture.cargo_b}`,{headers:await headers(page),data:{quantity:"1",version:1}}),
    await page.request.post(`/api/operational-shipments/${fixture.shipment_b}/route-plans`,{headers:await headers(page),data:{}})
  ];for(const response of forbidden){expect([403,404]).toContain(response.status());const leak=await response.text();for(const protectedValue of ["Cargo B","Customer B","SHARED-E2E-B",fixture.project_b,fixture.shipment_b,fixture.cargo_b])expect(leak).not.toContain(protectedValue);}
  const after=await api(page,"GET","/shared-transport");expect(after.status()).toBe(200);expect(await after.text()).not.toContain("Cargo B");
 });
 test("H - cross-tenant isolation",async({page})=>{const e=observe(page);await login(page);await openUnit(page);const text=await body(page);expect(text).toContain("Cargo A");expect(text).not.toContain("Tenant B Cargo");expect(text).not.toContain("Foreign Customer");expect(text).not.toContain("Foreign Carrier");expect(text).not.toContain("SHARED-E2E-FOREIGN");const choices=(await page.getByLabel("انتخاب بار قابل تخصیص").locator("option").allTextContents()).join(" ");expect(choices).not.toContain("Tenant B Cargo");const carrierChoices=(await page.getByLabel("انتخاب کریر").locator("option").allTextContents()).join(" ");expect(carrierChoices).not.toContain("Foreign Customer");expect(carrierChoices).not.toContain("Foreign Carrier");const authorized=await tracking(page,fixture.shipment_a);expect(authorized.tracking.enabled).toBeTruthy();clean(e);const forbidden=[await page.request.get(`/api/operational-shipments/${fixture.tenant_b_shipment}`,{headers:await headers(page)}),await page.request.get(`/api/internal/operational-shipments/${fixture.tenant_b_shipment}/cargo-items/${fixture.tenant_b_cargo}`,{headers:await headers(page)}),await page.request.get(`/api/internal/operational-shipments/${fixture.tenant_b_shipment}/transport-tracking`,{headers:await headers(page)}),await api(page,"GET","/shared-transport",undefined,fixture.tenant_b_project,fixture.foreign_unit),await api(page,"POST","/allocations",{cargo_public_id:fixture.tenant_b_cargo,allocated_quantity:"1"}),await api(page,"PATCH","/carrier",{carrier_customer_id:fixture.foreign_carrier_id}),await api(page,"PATCH","/carrier",{carrier_customer_id:fixture.foreign_customer_id})];for(const response of forbidden){expect([403,404]).toContain(response.status());const leak=await response.text();for(const secret of ["Tenant B Cargo","Foreign Customer","Foreign Carrier","SHARED-E2E-FOREIGN",fixture.tenant_b_project,fixture.tenant_b_shipment,fixture.tenant_b_cargo])expect(leak).not.toContain(secret);}});
 test("I - canonical mutation consistency",async({page},testInfo)=>{const e=observe(page);await login(page);await openUnit(page,fixture.project_i,"SHARED-E2E-I-X");
  const list=async(unit:string)=>await(await api(page,"GET","/shared-transport",undefined,fixture.project_i,unit)).json() as SharedTransportResponse;
  const canonical=async(unit:string)=>{const data=await list(unit);return data.data.allocations.filter(x=>x.description.includes("Cargo I"));};
  const current=async()=>tracking(page,fixture.shipment_i);
  // Fixture contract: I begins eligible and has no canonical allocation on either target.
  expect(await canonical(fixture.unit_i_x)).toHaveLength(0);expect(await canonical(fixture.unit_i_y)).toHaveLength(0);
  expect((await page.getByLabel("انتخاب بار قابل تخصیص").locator("option").allTextContents()).join(" ")).toContain("Cargo I");
  const createX=page.waitForResponse(r=>r.request().method()==="POST"&&r.url().includes("/allocations")&&r.status()===201);
  await allocate(page,fixture.cargo_i);const createXResponse=await createX;const firstId=(await createXResponse.json()).data.public_id as string;
  expect(firstId).toBeTruthy();expect(firstId).not.toBe(fixture.cargo_i);expect(await canonical(fixture.unit_i_x)).toEqual([expect.objectContaining({public_id:firstId})]);
  await expect(page.getByRole("listitem").filter({hasText:"Cargo I"})).toBeVisible();
  await shipment(page,fixture.shipment_i);let state=await current();expect(state.tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({source:"canonical_execution",unit_code:"SHARED-E2E-I-X"})]));
  await page.reload();expect((await current()).tracking.units.some(x=>x.source==="canonical_execution"&&x.unit_code==="SHARED-E2E-I-X")).toBeTruthy();await shipment(page,fixture.shipment_i);await expect(page.getByText("SHARED-E2E-I-X")).toBeVisible();
  await openUnit(page,fixture.project_i,"SHARED-E2E-I-X");const deleteRequest=page.waitForRequest(r=>r.method()==="DELETE"&&r.url().endsWith(`/allocations/${firstId}`));const deleteResponse=page.waitForResponse(r=>r.request().method()==="DELETE"&&r.url().endsWith(`/allocations/${firstId}`));
  await page.getByRole("listitem").filter({hasText:"Cargo I"}).getByRole("button",{name:"حذف"}).click();expect((await deleteRequest).url()).toContain(firstId);expect((await deleteResponse).status()).not.toBe(404);await expect(page.getByRole("listitem").filter({hasText:"Cargo I"})).toHaveCount(0);expect(await canonical(fixture.unit_i_x)).toHaveLength(0);
  await shipment(page,fixture.shipment_i);state=await current();expect(state.tracking.units.some(x=>x.source==="canonical_execution"&&x.unit_code==="SHARED-E2E-I-X")).toBeFalsy();await page.reload();expect((await current()).tracking.units.some(x=>x.source==="canonical_execution"&&x.unit_code==="SHARED-E2E-I-X")).toBeFalsy();await shipment(page,fixture.shipment_i);await expect(page.getByText("SHARED-E2E-I-X")).toHaveCount(0);
  await openUnit(page,fixture.project_i,"SHARED-E2E-I-Y");const createY=page.waitForResponse(r=>r.request().method()==="POST"&&r.url().includes("/allocations")&&r.status()===201);await allocate(page,fixture.cargo_i);const secondId=(await (await createY).json()).data.public_id as string;
  expect(secondId).toBeTruthy();expect(secondId).not.toBe(firstId);expect(secondId).not.toBe(fixture.cargo_i);expect(await canonical(fixture.unit_i_x)).toHaveLength(0);expect(await canonical(fixture.unit_i_y)).toEqual([expect.objectContaining({public_id:secondId})]);
  await shipment(page,fixture.shipment_i);state=await current();expect(state.tracking.units).toEqual(expect.arrayContaining([expect.objectContaining({source:"canonical_execution",unit_code:"SHARED-E2E-I-Y"})]));expect(state.tracking.units.some(x=>x.unit_code==="SHARED-E2E-I-X"&&x.source==="canonical_execution")).toBeFalsy();await page.reload();expect((await current()).tracking.units.some(x=>x.source==="canonical_execution"&&x.unit_code==="SHARED-E2E-I-Y")).toBeTruthy();await shipment(page,fixture.shipment_i);await expect(page.getByText("SHARED-E2E-I-Y")).toBeVisible();await testInfo.attach("I-allocation-identities.json",{body:Buffer.from(JSON.stringify({first_allocation_id:firstId,second_allocation_id:secondId},null,2)),contentType:"application/json"});clean(e);
 });
});
