import { useCallback, useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router";
import { FileText, LogOut, Plus, RefreshCw } from "lucide-react";
import CustomerPortalLayout from "@/components/CustomerPortalLayout";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { CustomerPortalApiError, fetchCustomerRequests, fetchCustomerSession, logoutCustomer, type CustomerRequestList } from "@/lib/customerPortalApi";
import { useI18n } from "@/i18n";

export default function CustomerPortalRequests(){const {t,locale,statusLabel,shippingTypeLabel}=useI18n();const navigate=useNavigate(),location=useLocation();const [page,setPage]=useState(1),[data,setData]=useState<CustomerRequestList|null>(null),[csrf,setCsrf]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const session=await fetchCustomerSession();if(!session.authenticated||!session.csrf_token){navigate("/customer",{replace:true,state:{from:location.pathname}});return;}setCsrf(session.csrf_token);setData(await fetchCustomerRequests(page));}catch(e){if(e instanceof CustomerPortalApiError&&(e.status===401||e.code==="ACCOUNT_DISABLED")){navigate("/customer",{replace:true,state:{from:location.pathname}});return;}setError(e instanceof Error?e.message:t("common.error"));}finally{setLoading(false);}},[location.pathname,navigate,page,t]);useEffect(()=>{void load();},[load]);
 const logout=async()=>{try{await logoutCustomer(csrf);navigate("/customer",{replace:true});}catch(e){setError(e instanceof Error?e.message:t("common.error"));}};
 return <CustomerPortalLayout privateNav><section className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{t("customer.requests")}</h1><p className="text-sm text-muted-foreground">{data?.customer.email}</p></div><div className="flex gap-2"><Button asChild><Link to="/"><Plus className="h-4 w-4"/>{t("customer.newRequest")}</Link></Button><Button variant="outline" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>{t("common.refresh")}</Button><Button variant="ghost" onClick={()=>void logout()}><LogOut className="h-4 w-4"/>{t("common.logout")}</Button></div></section>
 {error&&<p role="alert" className="mb-4 rounded bg-destructive/10 p-3 text-destructive">{error}</p>}{loading?<Card><CardContent className="p-10 text-center">{t("customer.loadingTitle")}</CardContent></Card>:!data?.items.length?<Card><CardContent className="p-10 text-center"><FileText className="mx-auto mb-3"/>{t("customer.noRequestsTitle")}</CardContent></Card>:<div className="space-y-3">{data.items.map(item=><Card key={item.public_id}><CardHeader><CardTitle className="flex justify-between gap-3 text-base"><span>{item.tracking_code||item.public_id}</span><Badge variant="outline">{statusLabel(item.status)}</Badge></CardTitle></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-3"><span className="text-sm text-muted-foreground">{shippingTypeLabel(item.shipping_type,{full:true})} · {new Date(item.created_at).toLocaleDateString(locale)}</span><Button asChild variant="outline"><Link to={`/customer/requests/${item.public_id}`}>{t("customer.viewDetails")}</Link></Button></CardContent></Card>)}<div className="flex justify-center gap-3"><Button variant="outline" disabled={!data.pagination.has_prev} onClick={()=>setPage(v=>v-1)}>{t("common.previous")}</Button><span className="py-2 text-sm">{data.pagination.page} / {Math.max(data.pagination.pages,1)}</span><Button variant="outline" disabled={!data.pagination.has_next} onClick={()=>setPage(v=>v+1)}>{t("common.next")}</Button></div></div>}
 </CustomerPortalLayout>}
