import { useCallback, useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router";
import { CheckCircle, Clock, MessageSquare, RefreshCw, XCircle } from "lucide-react";
import CustomerPortalLayout from "@/components/CustomerPortalLayout";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Textarea } from "@/components/ui/textarea";
import { CustomerPortalApiError, fetchCustomerRequest, fetchCustomerSession, respondToCustomerQuote, type CustomerQuoteResponse, type CustomerRequestDetail } from "@/lib/customerPortalApi";
import { formatDualCalendarDate,formatDualCalendarInstant } from "@/lib/dualCalendar"; import { formatMoney } from "@/lib/formatQuantity"; import { isLocalDateBeforeToday } from "@/lib/localDate"; import { useI18n } from "@/i18n";

export default function CustomerPortalRequestDetail(){const {requestId=""}=useParams();const {t,locale,statusLabel,shippingTypeLabel}=useI18n();const navigate=useNavigate(),location=useLocation();const [data,setData]=useState<CustomerRequestDetail|null>(null),[csrf,setCsrf]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[discussion,setDiscussion]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const s=await fetchCustomerSession();if(!s.authenticated||!s.csrf_token){navigate("/customer",{replace:true,state:{from:location.pathname}});return;}setCsrf(s.csrf_token);setData(await fetchCustomerRequest(requestId));}catch(e){if(e instanceof CustomerPortalApiError&&e.status===401){navigate("/customer",{replace:true,state:{from:location.pathname}});return;}setError(e instanceof Error?e.message:t("common.error"));}finally{setLoading(false);}},[location.pathname,navigate,requestId,t]);useEffect(()=>{void load();},[load]);
 const respond=async(response:CustomerQuoteResponse)=>{if(!data?.latest_quote||!csrf)return;if(response==="discussion"&&!discussion.trim())return;setBusy(true);setError("");try{await respondToCustomerQuote(data.public_id,data.latest_quote,response,csrf,response==="discussion"?discussion.trim():undefined);setDiscussion("");await load();}catch(e){setError(e instanceof Error?e.message:t("customer.quoteResponseErrorTitle"));}finally{setBusy(false);}};
 if(loading)return <CustomerPortalLayout privateNav><div className="flex justify-center p-16"><RefreshCw className="animate-spin"/></div></CustomerPortalLayout>;
 const quote=data?.latest_quote;const expired=Boolean(quote&&!quote.customer_response&&quote.valid_until&&isLocalDateBeforeToday(quote.valid_until));const canRespond=Boolean(quote&&!quote.customer_response&&!expired);
 return <CustomerPortalLayout privateNav><div className="mb-4"><Button asChild variant="outline"><Link to="/customer/requests">{t("customer.backToPanel")}</Link></Button></div>{error&&<p role="alert" className="mb-4 rounded bg-destructive/10 p-3 text-destructive">{error}</p>}{!data?<Card><CardContent className="p-10 text-center">{t("customer.requestNotFoundTitle")}</CardContent></Card>:<div className="space-y-5">
  <Card><CardHeader><CardTitle className="flex justify-between gap-3">{t("customer.requestDetails")}<Badge>{statusLabel(data.status)}</Badge></CardTitle></CardHeader><CardContent className="flex flex-wrap gap-4 text-sm"><span>{data.tracking_code||data.public_id}</span><span>{shippingTypeLabel(data.shipping_type,{full:true})}</span><span>{formatDualCalendarInstant(data.created_at,locale)}</span></CardContent></Card>
  <Card><CardHeader><CardTitle>{t("customer.quoteTitle")}</CardTitle></CardHeader><CardContent className="space-y-4">{!quote?<p>{t("customer.noQuote")}</p>:<><div className="text-xl font-bold">{formatMoney(quote.amount,quote.currency,locale)}</div>{quote.valid_until&&<p className="text-sm text-muted-foreground">{t("customer.quoteValidUntil")}: {formatDualCalendarDate(quote.valid_until,locale)}</p>}{quote.note&&<p className="border-t pt-3 text-sm">{quote.note}</p>}
   {quote.customer_response==="accepted"&&<p className="flex gap-2 rounded bg-green-50 p-3 text-green-800"><CheckCircle className="h-4 w-4"/>{t("customer.quoteAccepted")}</p>}{quote.customer_response==="discussion"&&<div className="rounded bg-amber-50 p-3 text-amber-900"><p className="flex gap-2"><MessageSquare className="h-4 w-4"/>{t("customer.quoteDiscussion")}</p><p className="mt-2 whitespace-pre-wrap">{quote.customer_response_message}</p></div>}{quote.customer_response==="declined"&&<p className="flex gap-2 rounded bg-red-50 p-3 text-red-800"><XCircle className="h-4 w-4"/>{t("customer.quoteDeclined")}</p>}{expired&&<p className="flex gap-2 rounded bg-muted p-3"><Clock className="h-4 w-4"/>{t("customer.quoteExpired")}</p>}
   {canRespond&&<div className="space-y-3 border-t pt-4"><div className="grid gap-2 sm:grid-cols-3"><Button disabled={busy} onClick={()=>void respond("accepted")}>{t("customer.quoteAccept")}</Button><Button disabled={busy} variant="outline" onClick={()=>document.getElementById("customer-discussion")?.focus()}>{t("customer.quoteNeedsDiscussion")}</Button><Button disabled={busy} variant="outline" onClick={()=>void respond("declined")}>{t("customer.quoteDecline")}</Button></div><div className="rounded border border-amber-200 p-3"><label htmlFor="customer-discussion" className="text-sm font-medium">{t("customer.quoteDiscussionMessage")}</label><Textarea id="customer-discussion" maxLength={500} value={discussion} onChange={e=>setDiscussion(e.target.value)} placeholder={t("customer.quoteDiscussionPlaceholder")}/><Button className="mt-2" disabled={busy||!discussion.trim()} onClick={()=>void respond("discussion")}>{t("customer.quoteSendDiscussion")}</Button></div></div>}</>}</CardContent></Card>
  <Card><CardHeader><CardTitle>{t("customer.quoteHistory")}</CardTitle></CardHeader><CardContent className="space-y-3">{data.quote_history.map(item=><div key={item.public_id} className="rounded border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{formatMoney(item.amount,item.currency,locale)}</strong><span className="text-xs text-muted-foreground">{formatDualCalendarInstant(item.created_at,locale)}</span></div><p className="mt-2 text-sm">{item.customer_response==="accepted"?t("customer.quoteAccepted"):item.customer_response==="discussion"?t("customer.quoteDiscussion"):item.customer_response==="declined"?t("customer.quoteDeclined"):t("customer.quoteAwaitingResponse")}</p>{item.customer_response_message&&<p className="mt-2 whitespace-pre-wrap rounded bg-amber-50 p-2 text-sm">{item.customer_response_message}</p>}</div>)}</CardContent></Card>
 </div>}</CustomerPortalLayout>;
}
