import {useCallback,useEffect,useState} from "react";
import {useParams} from "react-router";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";
import {createExecutionUnit,createExecutionUnitEvent,getExecutionUnitTimeline,listExecutionUnits,type ExecutionEventView,type ExecutionUnitView,type PageMeta} from "@/lib/api";

export default function ExecutionUnits(){
 const {projectId=""}=useParams(); const [rows,setRows]=useState<ExecutionUnitView[]>([]); const [meta,setMeta]=useState<PageMeta>({page:1,per_page:25,total:0,pages:0});
 const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [delayed,setDelayed]=useState(""); const [stale,setStale]=useState(""); const [active,setActive]=useState("true"); const [opened,setOpened]=useState<ExecutionUnitView>(); const [timeline,setTimeline]=useState<ExecutionEventView[]>([]); const [error,setError]=useState("");
 const load=useCallback(async(page=1)=>{try{setError("");const p=new URLSearchParams({page:String(page),per_page:"25"});if(search)p.set("search",search);if(status)p.set("status",status);if(delayed)p.set("delayed",delayed);if(stale)p.set("stale",stale);if(active)p.set("active",active);const r=await listExecutionUnits(projectId,p);setRows(r.data);setMeta(r.meta)}catch(e){setError(e instanceof Error?e.message:"Unable to load units")}},[projectId,search,status,delayed,stale,active]);
 useEffect(()=>{void load()},[load]);
 const open=async(unit:ExecutionUnitView)=>{setOpened(unit);setTimeline([]);try{setTimeline((await getExecutionUnitTimeline(projectId,unit.public_id)).data)}catch(e){setError(e instanceof Error?e.message:"Unable to load timeline")}};
 const addUnit=async()=>{try{await createExecutionUnit(projectId,{unit_type:"road",display_name:"New execution unit"});await load(meta.page)}catch(e){setError(e instanceof Error?e.message:"Unable to create unit")}};
 const addUpdate=async()=>{if(!opened)return;try{await createExecutionUnitEvent(projectId,opened.public_id,{expected_version:opened.version,lifecycle_status:"in_progress",event_type:"unit_updated",visibility:"internal",internal_note:"Operational update",occurred_at:new Date().toISOString()},crypto.randomUUID());await load(meta.page);await open({...opened,version:(opened.version||1)+1})}catch(e){setError(e instanceof Error?e.message:"Unable to register update")}};
 return <main className="mx-auto max-w-7xl space-y-4 p-4 sm:p-6" dir="auto"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Execution units</h1><p className="text-sm text-muted-foreground">Project {projectId}</p></div><Button onClick={addUnit}>Create unit</Button></div>{error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
 <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-6"><Input aria-label="Search units" placeholder="Code, reference, or name" value={search} onChange={e=>setSearch(e.target.value)}/>{[["Status",status,setStatus,["","not_started","ready","in_progress","arrived","delivered","cancelled"]],["Delayed",delayed,setDelayed,["","true","false"]],["Stale",stale,setStale,["","true","false"]],["Active",active,setActive,["","true","false"]]].map(([label,value,setter,options])=><label className="text-sm" key={label as string}>{label as string}<select className="mt-1 h-10 w-full rounded border bg-background px-2" value={value as string} onChange={e=>(setter as (x:string)=>void)(e.target.value)}>{(options as string[]).map(x=><option key={x} value={x}>{x||"All"}</option>)}</select></label>)}<Button variant="outline" onClick={()=>void load(1)}>Apply</Button></CardContent></Card>
 <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b bg-muted/40 text-left"><th className="p-3">Code</th><th>Name / reference</th><th>Status</th><th>Last update</th><th>Alerts</th><th></th></tr></thead><tbody>{rows.map(u=><tr className="border-b" key={u.public_id}><td className="p-3 font-mono">{u.unit_code}</td><td>{u.display_name||"—"}<br/><span className="text-muted-foreground">{u.vehicle_reference||u.unit_type}</span></td><td><Badge variant="outline">{u.lifecycle_status}</Badge></td><td>{u.last_update_at?new Date(u.last_update_at).toLocaleString():"—"}</td><td>{u.alerts.delayed&&<Badge variant="destructive">Delayed</Badge>} {u.alerts.stale&&<Badge variant="secondary">Stale</Badge>} {u.alerts.attention_required&&<Badge>Attention</Badge>}</td><td><Button variant="ghost" onClick={()=>void open(u)}>Open</Button></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-8 text-center text-muted-foreground">No execution units match these filters.</p>}</CardContent></Card>
 <div className="flex items-center justify-between"><span className="text-sm">{meta.total} units · page {meta.page} of {Math.max(meta.pages,1)}</span><div className="flex gap-2"><Button variant="outline" disabled={meta.page<=1} onClick={()=>void load(meta.page-1)}>Previous</Button><Button variant="outline" disabled={meta.page>=meta.pages} onClick={()=>void load(meta.page+1)}>Next</Button></div></div>
 {opened&&<Card><CardHeader><CardTitle>{opened.unit_code} · {opened.display_name||opened.unit_type}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Badge>{opened.lifecycle_status}</Badge><span>{opened.latest_checkpoint||"No checkpoint recorded"}</span><Button className="ms-auto" onClick={addUpdate}>Register unit update</Button></div><h2 className="font-semibold">Timeline</h2>{timeline.length===0?<p className="text-muted-foreground">No updates.</p>:<ol className="space-y-3">{timeline.map(e=><li className="rounded border p-3" key={e.public_id}><b>{e.lifecycle_status||e.event_type}</b><p>{e.checkpoint_text||e.internal_note||e.customer_message||"—"}</p><time className="text-xs text-muted-foreground">{new Date(e.occurred_at).toLocaleString()}</time></li>)}</ol>}</CardContent></Card>}
 </main>
}
