import {useCallback,useEffect,useState} from "react";
import {useParams} from "react-router";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";
import {createExecutionUnit,createExecutionUnitEvent,getExecutionUnitTimeline,listExecutionUnits,type ExecutionEventView,type ExecutionUnitView,type PageMeta} from "@/lib/api";
import ProjectConfiguration from "@/components/ProjectConfiguration";

const statusLabels:Record<string,string>={not_started:"شروع‌نشده",ready:"آماده",in_progress:"در حال انجام",arrived:"رسیده",delivered:"تحویل‌شده",cancelled:"لغوشده"};
const yesNo=[{value:"",label:"همه"},{value:"true",label:"بله"},{value:"false",label:"خیر"}];

export default function ExecutionUnits(){
 const {projectId=""}=useParams(); const [rows,setRows]=useState<ExecutionUnitView[]>([]); const [meta,setMeta]=useState<PageMeta>({page:1,per_page:25,total:0,pages:0});
 const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [delayed,setDelayed]=useState(""); const [stale,setStale]=useState(""); const [active,setActive]=useState("true"); const [opened,setOpened]=useState<ExecutionUnitView>(); const [timeline,setTimeline]=useState<ExecutionEventView[]>([]); const [error,setError]=useState("");
 const load=useCallback(async(page=1)=>{try{setError("");const p=new URLSearchParams({page:String(page),per_page:"25"});if(search)p.set("search",search);if(status)p.set("status",status);if(delayed)p.set("delayed",delayed);if(stale)p.set("stale",stale);if(active)p.set("active",active);const r=await listExecutionUnits(projectId,p);setRows(r.data);setMeta(r.meta)}catch{setError("بارگذاری بخش‌های اجرایی انجام نشد.")}},[projectId,search,status,delayed,stale,active]);
 useEffect(()=>{void load()},[load]);
 const open=async(unit:ExecutionUnitView)=>{setOpened(unit);setTimeline([]);try{setTimeline((await getExecutionUnitTimeline(projectId,unit.public_id)).data)}catch{setError("بارگذاری تاریخچه رویدادها انجام نشد.")}};
 const addUnit=async()=>{try{await createExecutionUnit(projectId,{unit_type:"road",display_name:"بخش اجرایی جدید"});await load(meta.page)}catch{setError("ایجاد بخش اجرایی انجام نشد.")}};
 const addUpdate=async()=>{if(!opened)return;try{await createExecutionUnitEvent(projectId,opened.public_id,{expected_version:opened.version,lifecycle_status:"in_progress",event_type:"unit_updated",visibility:"internal",internal_note:"به‌روزرسانی عملیاتی",occurred_at:new Date().toISOString()},crypto.randomUUID());await load(meta.page);await open({...opened,version:(opened.version||1)+1})}catch{setError("ثبت به‌روزرسانی انجام نشد.")}};
 return <main className="mx-auto max-w-7xl space-y-4 p-4 sm:p-6" dir="rtl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">بخش‌های اجرایی حمل</h1><p className="text-sm text-muted-foreground">بخش‌های مستقل حمل مانند وسیله، کانتینر، واگن یا عملیات هوایی که وضعیت آن‌ها جداگانه مدیریت می‌شود. <span dir="ltr">{projectId}</span></p></div><Button onClick={addUnit}>ایجاد بخش اجرایی</Button></div>{error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}<ProjectConfiguration projectId={projectId}/>
 <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-6"><Input aria-label="جست‌وجوی بخش‌های اجرایی" placeholder="کد، شناسه یا عنوان" value={search} onChange={e=>setSearch(e.target.value)}/><label className="text-sm">وضعیت<select className="mt-1 h-10 w-full rounded border bg-background px-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{[["دارای تأخیر",delayed,setDelayed],["به‌روزرسانی قدیمی",stale,setStale],["فعال",active,setActive]].map(([label,value,setter])=><label className="text-sm" key={label as string}>{label as string}<select className="mt-1 h-10 w-full rounded border bg-background px-2" value={value as string} onChange={e=>(setter as (x:string)=>void)(e.target.value)}>{yesNo.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>)}<Button variant="outline" onClick={()=>void load(1)}>اعمال فیلتر</Button></CardContent></Card>
 <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b bg-muted/40 text-right"><th className="p-3">کد</th><th>عنوان یا شناسه</th><th>وضعیت</th><th>آخرین به‌روزرسانی</th><th>هشدارها</th><th></th></tr></thead><tbody>{rows.map(u=><tr className="border-b" key={u.public_id}><td className="p-3 font-mono" dir="ltr">{u.unit_code}</td><td>{u.display_name||"—"}<br/><span className="text-muted-foreground" dir="auto">{u.vehicle_reference||u.unit_type}</span></td><td><Badge variant="outline">{statusLabels[u.lifecycle_status]||u.lifecycle_status}</Badge></td><td>{u.last_update_at?new Date(u.last_update_at).toLocaleString("fa-IR"):"—"}</td><td>{u.alerts.delayed&&<Badge variant="destructive">با تأخیر</Badge>} {u.alerts.stale&&<Badge variant="secondary">نیازمند به‌روزرسانی</Badge>} {u.alerts.attention_required&&<Badge>نیازمند پیگیری</Badge>}</td><td><Button variant="ghost" onClick={()=>void open(u)}>مشاهده</Button></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-8 text-center text-muted-foreground">بخش اجرایی منطبق با فیلترها یافت نشد. اگر هنوز موردی ثبت نشده، نخست بخش قابل مدیریت حمل را ایجاد کنید.</p>}</CardContent></Card>
 <div className="flex items-center justify-between"><span className="text-sm">{meta.total} بخش · صفحه {meta.page} از {Math.max(meta.pages,1)}</span><div className="flex gap-2"><Button variant="outline" disabled={meta.page<=1} onClick={()=>void load(meta.page-1)}>قبلی</Button><Button variant="outline" disabled={meta.page>=meta.pages} onClick={()=>void load(meta.page+1)}>بعدی</Button></div></div>
 {opened&&<Card><CardHeader><CardTitle><span dir="ltr">{opened.unit_code}</span> · {opened.display_name||opened.unit_type}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Badge>{statusLabels[opened.lifecycle_status]||opened.lifecycle_status}</Badge><span>{opened.latest_checkpoint||"نقطه عملیاتی ثبت نشده است"}</span><Button className="ms-auto" onClick={addUpdate}>ثبت به‌روزرسانی بخش</Button></div><h2 className="font-semibold">تاریخچه رویدادها</h2>{timeline.length===0?<p className="text-muted-foreground">هنوز رویدادی ثبت نشده است.</p>:<ol className="space-y-3">{timeline.map(e=><li className="rounded border p-3" key={e.public_id}><b>{statusLabels[e.lifecycle_status||""]||e.lifecycle_status||e.event_type}</b><p>{e.checkpoint_text||e.internal_note||e.customer_message||"—"}</p><time className="text-xs text-muted-foreground" dir="ltr">{new Date(e.occurred_at).toLocaleString("fa-IR")}</time></li>)}</ol>}</CardContent></Card>}
 </main>
}
