import { FormEvent, useEffect, useRef, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import OperationalPermission from "@/components/OperationalPermission";
import { ApiError, createOperationalShipment, listOperationalShipments, type OperationalShipmentSummary } from "@/lib/api"; import { useI18n } from "@/i18n";

export default function OperationalShipments(){
 const {t,direction,locale}=useI18n(); const navigate=useNavigate(); const [search]=useSearchParams(); const [rows,setRows]=useState<OperationalShipmentSummary[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [page,setPage]=useState(1); const [more,setMore]=useState(false); const [submitting,setSubmitting]=useState(false); const key=useRef(crypto.randomUUID());
 const [filters,setFilters]=useState({status:"",customer:"",origin:"",destination:"",overdue:"",date_from:"",date_to:""}); const [form,setForm]=useState({quote:search.get("accepted_quote_id")||"",origin:"",destination:"",departure:"",arrival:"",mode:"road"});
 const load=()=>{setLoading(true);setError(""); const q=new URLSearchParams({...filters,page:String(page)}); listOperationalShipments(q.toString()).then(r=>{setRows(r.data);setMore(r.meta.has_more)}).catch(e=>setError(e instanceof ApiError&&e.status===403?t("operations.forbidden"):e.message)).finally(()=>setLoading(false));}; useEffect(load,[page]);
 async function create(e:FormEvent){e.preventDefault();if(submitting)return;setError("");const departure=new Date(form.departure);const arrival=new Date(form.arrival);if(Number.isNaN(departure.getTime())||Number.isNaN(arrival.getTime())){setError(t("operations.invalidTime"));return}setSubmitting(true);try{const r=await createOperationalShipment({accepted_quote_id:Number(form.quote),planned_departure:departure.toISOString(),planned_arrival:arrival.toISOString(),origin:{source_type:"province",source_id:Number(form.origin)},destination:{source_type:"province",source_id:Number(form.destination)},transport_mode:form.mode},key.current);navigate(`/operations/shipments/${r.data.id}`)}catch(x){setError(x instanceof Error?x.message:t("operations.error"));}finally{setSubmitting(false)}}
 return <main className="min-h-screen bg-slate-50 p-4 md:p-8" dir={direction}><div className="mx-auto max-w-7xl space-y-5"><header className="flex justify-between"><div><h1 className="text-2xl font-bold">{t("operations.shipmentsTitle")}</h1><p>{t("operations.shipmentsSubtitle")}</p></div><Link to="/operations/work-queue"><Button variant="outline">{t("operations.workQueue")}</Button></Link></header>
 <Card><CardContent className="grid gap-3 p-4 md:grid-cols-4">{Object.entries(filters).map(([name,value])=><div key={name}><Label htmlFor={`filter-${name}`}>{name}</Label><Input id={`filter-${name}`} value={value} onChange={e=>setFilters({...filters,[name]:e.target.value})}/></div>)}<Button onClick={()=>{setPage(1);load()}} disabled={loading}>{t("operations.applyFilters")}</Button></CardContent></Card>
 <OperationalPermission permission="operational_shipment.create"><Card><CardHeader><CardTitle>{t("operations.createTitle")}</CardTitle></CardHeader><CardContent><form onSubmit={create} className="grid gap-3 md:grid-cols-3">{Object.entries(form).map(([name,value])=><div key={name}><Label htmlFor={`create-${name}`}>{name}</Label><Input id={`create-${name}`} required type="text" placeholder={name==="departure"||name==="arrival"?"YYYY-MM-DDTHH:mm":undefined} value={value} onChange={e=>setForm({...form,[name]:e.target.value})}/></div>)}<Button type="submit" disabled={submitting}>{submitting?t("operations.submitting"):t("operations.create")}</Button></form></CardContent></Card></OperationalPermission>
 {error&&<div role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}<Button variant="link" onClick={load}>{t("operations.retry")}</Button></div>}{loading?<p aria-live="polite">{t("operations.loading")}</p>:rows.length===0?<p className="rounded bg-white p-8 text-center">{t("operations.empty")}</p>:<div className="grid gap-4 md:grid-cols-2">{rows.map(r=><Link key={r.id} to={`/operations/shipments/${r.id}`}><Card><CardContent className="space-y-1 p-5"><div className="flex justify-between"><strong>#{r.id}</strong><span>{r.status}</span></div><p>{r.customer||"—"}</p><p>{r.route_leg.origin.display_name} → {r.route_leg.destination.display_name}</p><p>Quote #{r.source.accepted_quote_id} · Request #{r.source.shipment_request_id}</p><p>{new Date(r.route_leg.planned_departure).toLocaleString(locale)} — {new Date(r.route_leg.planned_arrival).toLocaleString(locale)}</p><p>{r.current_milestone||"—"} · {r.overdue?"Overdue":"On time"} · {r.open_work_item_count}</p></CardContent></Card></Link>)}</div>}<div className="flex justify-center gap-2"><Button disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>‹</Button><span>{page}</span><Button disabled={!more||loading} onClick={()=>setPage(p=>p+1)}>›</Button></div></div></main>
}
