import { useEffect, useState } from "react";
import { Link } from "react-router";
import OperationsNav from "@/components/OperationsNav";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ApiError, listOperationalShipments, type OperationalShipmentSummary } from "@/lib/api";
import { useI18n } from "@/i18n";
import OperationalAnyPermission from "@/components/OperationalAnyPermission";

const operationalCustomerLabel=(row:OperationalShipmentSummary)=>typeof row.customer==="string"?row.customer:row.customer?.display_name||"Not provided";
export default function OperationalShipments(){
 const {t,direction,locale}=useI18n(); const [rows,setRows]=useState<OperationalShipmentSummary[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [page,setPage]=useState(1); const [more,setMore]=useState(false); const [filters,setFilters]=useState({status:"",customer:"",origin:"",destination:"",overdue:"",date_from:"",date_to:""});
 const load=()=>{setLoading(true);setError("");const q=new URLSearchParams({...filters,page:String(page)});listOperationalShipments(q.toString()).then(r=>{setRows(r.data);setMore(r.meta.has_more)}).catch(e=>setError(e instanceof ApiError&&e.status===403?t("operations.forbidden"):e instanceof Error?e.message:t("operations.error"))).finally(()=>setLoading(false));};
 // Pagination reloads automatically; edited filters apply only via the explicit button.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(load,[page]);
 return <main className="min-h-screen overflow-x-hidden bg-slate-50 p-3 sm:p-5 md:p-8" dir={direction}><div className="mx-auto max-w-7xl space-y-5"><OperationsNav/><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{t("operations.shipmentsTitle")}</h1><p>{t("operations.shipmentsSubtitle")}</p></div><OperationalAnyPermission permissions={["operational_shipment.create_direct","operational_shipment.create_from_quote","operational_shipment.create"]}><Button asChild><Link to="/operations/shipments/new">New Operation</Link></Button></OperationalAnyPermission></header>
 <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(filters).map(([name,value])=><div className="min-w-0" key={name}><Label htmlFor={`filter-${name}`}>{name}</Label><Input id={`filter-${name}`} aria-label={name} value={value} onChange={e=>setFilters({...filters,[name]:e.target.value})}/></div>)}<Button onClick={()=>{setPage(1);load()}} disabled={loading}>{t("operations.applyFilters")}</Button></CardContent></Card>
 {error&&<div role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}<Button variant="link" onClick={load}>{t("operations.retry")}</Button></div>}{loading?<p aria-live="polite">{t("operations.loading")}</p>:!rows.length?<p className="rounded bg-white p-8 text-center">{t("operations.empty")}</p>:<div className="grid gap-4 md:grid-cols-2">{rows.map(r=><Link className="min-w-0 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" key={r.public_id} to={`/operations/shipments/${r.public_id}`}><Card className="h-full"><CardContent className="min-w-0 space-y-2 p-5"><div className="flex flex-wrap justify-between gap-2"><strong className="truncate">{operationalCustomerLabel(r)}</strong><span className="rounded-full border px-2 py-0.5 text-xs">{r.source.type==="direct"?"Direct":"Accepted quote"}</span></div><p className="break-words">{r.route_leg.origin.display_name} → {r.route_leg.destination.display_name}</p><p>{new Date(r.route_leg.planned_departure).toLocaleString(locale)} — {new Date(r.route_leg.planned_arrival).toLocaleString(locale)}</p><p>Project: {r.project_public_id||"—"}</p><p>Request: {r.source.shipment_request_id??"Not applicable"} · Quote: {r.source.accepted_quote_id??"Not applicable"}</p><p>{r.current_milestone||"—"} · {r.overdue?"Overdue":"On time"} · {r.open_work_item_count}</p></CardContent></Card></Link>)}</div>}<div className="flex items-center justify-center gap-2"><Button aria-label="Previous page" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>‹</Button><span>{page}</span><Button aria-label="Next page" disabled={!more||loading} onClick={()=>setPage(p=>p+1)}>›</Button></div></div></main>;
}
