import { useEffect, useMemo, useRef, useState } from "react";
import { RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Alert, AlertDescription } from "@/components/ui/alert";
import OperationsNav from "@/components/OperationsNav";
import { getAnalyticsSemanticRegistry, getOperationalContext, queryAnalytics, type AnalyticsFilter, type AnalyticsSemanticRegistry } from "@/lib/api";
import { operationsControlTower } from "@/dashboard/control-tower";
import { validateDashboardDefinition } from "@/dashboard/validator";
import { DashboardWidget, type WidgetResult } from "@/dashboard/DashboardWidgets";
import type { WidgetDefinition } from "@/dashboard/types";

const blank = (): Record<string, WidgetResult> => Object.fromEntries(operationsControlTower.widgets.map((widget) => [widget.widget_id, { state:"LOADING" }]));
export default function OperationsControlTower() {
  const [registry, setRegistry] = useState<AnalyticsSemanticRegistry>(); const [issues, setIssues] = useState<string[]>([]); const [results, setResults] = useState<Record<string, WidgetResult>>(blank); const [filters, setFilters] = useState({ from:"", to:"", customer:"", project:"" }); const [cycle, setCycle] = useState(0); const [lastRefreshed, setLastRefreshed] = useState<string>(); const [allowed, setAllowed] = useState<boolean>(); const cycleRef = useRef(0);
  const globalFilters = useMemo<AnalyticsFilter[]>(() => [filters.from || filters.to ? { dimension:"TIME", value:{ ...(filters.from ? {from:filters.from}:{}), ...(filters.to ? {to:filters.to}:{}) } } : null, filters.customer ? {dimension:"CUSTOMER",value:filters.customer}:null, filters.project ? {dimension:"PROJECT",value:filters.project}:null].filter(Boolean) as AnalyticsFilter[], [filters]);
  useEffect(() => { getOperationalContext().then((item) => setAllowed(item.data.permissions.includes("operational_shipment.read"))).catch(() => setAllowed(false)); }, []);
  useEffect(() => { let live = true; getAnalyticsSemanticRegistry().then(({data}) => { if (!live) return; setRegistry(data); setIssues(validateDashboardDefinition(operationsControlTower, data).map((item) => item.message)); }).catch((error) => live && setIssues([error instanceof Error ? error.message : "Semantic registry unavailable."])); return () => { live = false; }; }, []);
  useEffect(() => { if (!registry || issues.length || !allowed) return; const current = ++cycleRef.current; setResults(blank()); const queue = [...operationsControlTower.widgets]; const run = async () => { while (queue.length) { const widget = queue.shift()!; const applicable = new Set(operationsControlTower.global_filters.filter((filter) => filter.applicable_widget_ids.includes(widget.widget_id)).map((filter) => filter.dimension_key)); const query = { metrics:widget.query.metric_keys, dimensions:widget.query.dimension_keys, filters:[...globalFilters.filter((filter) => applicable.has(filter.dimension)), ...(widget.query.filters || [])], time_dimension:widget.query.time_dimension, time_grain:widget.query.time_grain, limit:widget.query.limit }; try { const {data} = await queryAnalytics(query); if (cycleRef.current === current) setResults((old) => ({...old,[widget.widget_id]:{state:data.coverage.some((item) => item.state !== "VALUE") || data.warnings.length ? "PARTIAL_COVERAGE":"VALUE",response:data,receivedAt:new Date().toISOString()}})); } catch (error) { if (cycleRef.current === current) setResults((old) => ({...old,[widget.widget_id]:{state:"ERROR",error:error instanceof Error ? error.message : "Query failed."}})); } } };
    Promise.all(Array.from({length:4}, run)).then(() => current === cycleRef.current && setLastRefreshed(new Date().toISOString())); }, [registry, issues.length, allowed, globalFilters, cycle]);
  useEffect(() => { const timer = window.setInterval(() => { if (!document.hidden) setCycle((value) => value + 1); }, 120000); return () => window.clearInterval(timer); }, []);
  if (allowed === false) return <main className="min-h-screen bg-slate-50 p-4"><OperationsNav/><Alert className="mx-auto mt-6 max-w-xl"><AlertDescription>مجوز مشاهده عملیات برای نمایش برج کنترل لازم است.</AlertDescription></Alert></main>;
  return <main dir="rtl" className="min-h-screen bg-slate-50 p-3 sm:p-5 md:p-8"><div className="mx-auto max-w-7xl space-y-5"><OperationsNav/><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{operationsControlTower.name}</h1><p className="text-sm text-muted-foreground">{operationsControlTower.description}</p>{lastRefreshed && <p className="mt-1 text-xs text-muted-foreground">آخرین به‌روزرسانی: {new Date(lastRefreshed).toLocaleString("fa-IR")} · چرخه {cycle}</p>}</div><Button onClick={() => setCycle((value) => value + 1)}><RefreshCw className="ms-2 h-4 w-4" />به‌روزرسانی</Button></header>
    <section aria-label="فیلترهای سراسری" className="grid gap-3 rounded-lg border bg-card p-4 sm:grid-cols-2 lg:grid-cols-4"><Input aria-label="شروع بازه زمانی" type="datetime-local" value={filters.from} onChange={(event) => setFilters({...filters,from:event.target.value ? new Date(event.target.value).toISOString():""})}/><Input aria-label="پایان بازه زمانی" type="datetime-local" value={filters.to} onChange={(event) => setFilters({...filters,to:event.target.value ? new Date(event.target.value).toISOString():""})}/><Input aria-label="شناسه مشتری" placeholder="شناسه مشتری، مانند customer:1" value={filters.customer} onChange={(event) => setFilters({...filters,customer:event.target.value})}/><Input aria-label="شناسه پروژه" placeholder="شناسه عمومی پروژه" value={filters.project} onChange={(event) => setFilters({...filters,project:event.target.value})}/></section>
    {issues.length > 0 && <Alert variant="destructive"><AlertDescription>{issues.join(" ")}</AlertDescription></Alert>}
    {operationsControlTower.sections.map((section) => <section key={section.section_id} aria-labelledby={section.section_id}><h2 id={section.section_id} className="mb-3 text-lg font-semibold">{section.title}</h2><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{section.widget_ids.map((id) => { const widget = operationsControlTower.widgets.find((item) => item.widget_id === id) as WidgetDefinition; const inactive = globalFilters.filter((filter) => !operationsControlTower.global_filters.some((definition) => definition.dimension_key === filter.dimension && definition.applicable_widget_ids.includes(id))).map((filter) => operationsControlTower.global_filters.find((definition) => definition.dimension_key === filter.dimension)?.label || filter.dimension); return <DashboardWidget key={id} widget={widget} result={results[id] || {state:"LOADING"}} notApplicableFilters={inactive} />; })}</div></section>)}</div></main>;
}
