"""add_transport_method_columns

Revision ID: 54ea21ea0d9f
Revises: 20240923_add_cargo_details
Create Date: 2025-10-07 10:21:19.556833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54ea21ea0d9f'
down_revision = '20240923_add_cargo_details'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipper')
    op.drop_index(op.f('idx_shipmode_namefa'), table_name='shipment_mode')
    op.drop_table('shipment_mode')
    op.drop_index(op.f('idx_user_otp_user'), table_name='user_otp')
    op.drop_index(op.f('idx_user_otp_valid'), table_name='user_otp', postgresql_where='(consumed_at IS NULL)')
    op.drop_table('user_otp')
    op.drop_index(op.f('idx_incoterm_namefa'), table_name='incoterm')
    op.drop_table('incoterm')
    op.drop_index(op.f('idx_packtype_namefa'), table_name='package_type')
    op.drop_table('package_type')
    op.drop_index(op.f('ux_app_user_email'), table_name='app_user', postgresql_where='(email IS NOT NULL)')
    op.drop_index(op.f('ux_app_user_phone'), table_name='app_user')
    op.drop_table('app_user')
    op.alter_column('city', 'county_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('city', 'province_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('idx_city_county_id'), table_name='city')
    op.drop_index(op.f('ix_city_name_fa'), table_name='city')
    op.drop_index(op.f('ix_city_province_id'), table_name='city')
    op.drop_constraint(op.f('uq_city_province_name_fa'), 'city', type_='unique')
    op.drop_constraint(op.f('fk_city_county'), 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'county', ['county_id'], ['id'])
    op.drop_constraint(op.f('county_province_id_name_fa_key'), 'county', type_='unique')
    op.drop_index(op.f('idx_county_province'), table_name='county')
    op.drop_index(op.f('idx_county_province_id'), table_name='county')
    op.drop_index(op.f('ix_county_city_id'), table_name='county')
    op.drop_index(op.f('ix_county_name_fa'), table_name='county')
    op.drop_constraint(op.f('uq_county_city_name_fa'), 'county', type_='unique')
    op.drop_constraint(op.f('county_province_id_fkey'), 'county', type_='foreignkey')
    op.drop_constraint(op.f('fk_county_city'), 'county', type_='foreignkey')
    op.create_foreign_key(None, 'county', 'province', ['province_id'], ['id'])
    op.drop_column('county', 'city_id')
    op.alter_column('expert_console_message', 'is_read_by_customer',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('expert_console_message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expert_console_notification', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('expert_user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('expert_user', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'expert'::character varying"))
    op.alter_column('expert_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_iran_port_is_active'), table_name='iran_port')
    op.drop_index(op.f('ix_iran_port_port_type'), table_name='iran_port')
    op.drop_index(op.f('ix_iran_port_province_id'), table_name='iran_port')
    op.drop_constraint(op.f('iran_port_province_id_fkey'), 'iran_port', type_='foreignkey')
    op.create_foreign_key(None, 'iran_port', 'province', ['province_id'], ['id'])
    op.drop_index(op.f('ix_port_province_mapping_port_id'), table_name='port_province_mapping')
    op.drop_index(op.f('ix_port_province_mapping_province_id'), table_name='port_province_mapping')
    op.drop_index(op.f('ix_port_province_mapping_suitability'), table_name='port_province_mapping')
    op.drop_constraint(op.f('port_province_mapping_port_id_fkey'), 'port_province_mapping', type_='foreignkey')
    op.drop_constraint(op.f('port_province_mapping_province_id_fkey'), 'port_province_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'port_province_mapping', 'iran_port', ['port_id'], ['id'])
    op.create_foreign_key(None, 'port_province_mapping', 'province', ['province_id'], ['id'])
    op.alter_column('province', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_index(op.f('ix_province_name_fa'), table_name='province')
    op.drop_constraint(op.f('province_name_fa_key'), 'province', type_='unique')
    op.drop_constraint(op.f('uq_province_name_fa'), 'province', type_='unique')
    op.add_column('shipment_request', sa.Column('international_transport_method', sa.String(length=32), nullable=True))
    op.add_column('shipment_request', sa.Column('domestic_transport_method', sa.String(length=32), nullable=True))
    op.add_column('shipment_request', sa.Column('transport_method_preference', sa.String(length=20), nullable=True))
    op.alter_column('shipment_request', 'has_unread_for_assignee',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('shipment_request', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.drop_index(op.f('idx_req_dest_city'), table_name='shipment_request')
    op.drop_index(op.f('idx_req_origin_city'), table_name='shipment_request')
    op.drop_index(op.f('idx_req_status_str'), table_name='shipment_request')
    op.drop_index(op.f('ix_shipment_request_iran_entry_port_id'), table_name='shipment_request')
    op.drop_index(op.f('ix_shipment_request_iran_entry_province_id'), table_name='shipment_request')
    op.drop_constraint(op.f('fk_shipment_request_iran_entry_port_id'), 'shipment_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_shipment_request_iran_entry_province_id'), 'shipment_request', type_='foreignkey')
    op.drop_constraint(op.f('shipment_request_request_user_id_fkey'), 'shipment_request', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_request', 'iran_port', ['iran_entry_port_id'], ['id'])
    op.create_foreign_key(None, 'shipment_request', 'province', ['iran_entry_province_id'], ['id'])
    op.create_foreign_key(None, 'shipment_request', 'customer', ['customer_id'], ['id'])
    op.alter_column('shipment_request_log', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('shipment_request_log', 'ip_address',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_srl_created_at'), table_name='shipment_request_log')
    op.drop_index(op.f('idx_srl_request_id'), table_name='shipment_request_log')
    op.drop_constraint(op.f('fk_srl_shipment_request'), 'shipment_request_log', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_request_log', 'shipment_request', ['shipment_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment_request_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_srl_shipment_request'), 'shipment_request_log', 'shipment_request', ['shipment_request_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_srl_request_id'), 'shipment_request_log', ['shipment_request_id'], unique=False)
    op.create_index(op.f('idx_srl_created_at'), 'shipment_request_log', ['created_at'], unique=False)
    op.alter_column('shipment_request_log', 'ip_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('shipment_request_log', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'shipment_request', type_='foreignkey')
    op.drop_constraint(None, 'shipment_request', type_='foreignkey')
    op.drop_constraint(None, 'shipment_request', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_request_request_user_id_fkey'), 'shipment_request', 'app_user', ['request_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_shipment_request_iran_entry_province_id'), 'shipment_request', 'province', ['iran_entry_province_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_shipment_request_iran_entry_port_id'), 'shipment_request', 'iran_port', ['iran_entry_port_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_shipment_request_iran_entry_province_id'), 'shipment_request', ['iran_entry_province_id'], unique=False)
    op.create_index(op.f('ix_shipment_request_iran_entry_port_id'), 'shipment_request', ['iran_entry_port_id'], unique=False)
    op.create_index(op.f('idx_req_status_str'), 'shipment_request', ['status_request_status'], unique=False)
    op.create_index(op.f('idx_req_origin_city'), 'shipment_request', ['origin_city_id'], unique=False)
    op.create_index(op.f('idx_req_dest_city'), 'shipment_request', ['dest_city_id'], unique=False)
    op.alter_column('shipment_request', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('shipment_request', 'has_unread_for_assignee',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('shipment_request', 'transport_method_preference')
    op.drop_column('shipment_request', 'domestic_transport_method')
    op.drop_column('shipment_request', 'international_transport_method')
    op.create_unique_constraint(op.f('uq_province_name_fa'), 'province', ['name_fa'])
    op.create_unique_constraint(op.f('province_name_fa_key'), 'province', ['name_fa'])
    op.create_index(op.f('ix_province_name_fa'), 'province', ['name_fa'], unique=False)
    op.alter_column('province', 'code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'port_province_mapping', type_='foreignkey')
    op.drop_constraint(None, 'port_province_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('port_province_mapping_province_id_fkey'), 'port_province_mapping', 'province', ['province_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('port_province_mapping_port_id_fkey'), 'port_province_mapping', 'iran_port', ['port_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_port_province_mapping_suitability'), 'port_province_mapping', ['suitability_score'], unique=False)
    op.create_index(op.f('ix_port_province_mapping_province_id'), 'port_province_mapping', ['province_id'], unique=False)
    op.create_index(op.f('ix_port_province_mapping_port_id'), 'port_province_mapping', ['port_id'], unique=False)
    op.drop_constraint(None, 'iran_port', type_='foreignkey')
    op.create_foreign_key(op.f('iran_port_province_id_fkey'), 'iran_port', 'province', ['province_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_iran_port_province_id'), 'iran_port', ['province_id'], unique=False)
    op.create_index(op.f('ix_iran_port_port_type'), 'iran_port', ['port_type'], unique=False)
    op.create_index(op.f('ix_iran_port_is_active'), 'iran_port', ['is_active'], unique=False)
    op.alter_column('expert_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('expert_user', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'expert'::character varying"))
    op.alter_column('expert_user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('expert_console_notification', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('expert_console_message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expert_console_message', 'is_read_by_customer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('county', sa.Column('city_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'county', type_='foreignkey')
    op.create_foreign_key(op.f('fk_county_city'), 'county', 'city', ['city_id'], ['id'])
    op.create_foreign_key(op.f('county_province_id_fkey'), 'county', 'province', ['province_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_county_city_name_fa'), 'county', ['city_id', 'name_fa'])
    op.create_index(op.f('ix_county_name_fa'), 'county', ['name_fa'], unique=False)
    op.create_index(op.f('ix_county_city_id'), 'county', ['city_id'], unique=False)
    op.create_index(op.f('idx_county_province_id'), 'county', ['province_id'], unique=False)
    op.create_index(op.f('idx_county_province'), 'county', ['province_id'], unique=False)
    op.create_unique_constraint(op.f('county_province_id_name_fa_key'), 'county', ['province_id', 'name_fa'])
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key(op.f('fk_city_county'), 'city', 'county', ['county_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_unique_constraint(op.f('uq_city_province_name_fa'), 'city', ['province_id', 'name_fa'])
    op.create_index(op.f('ix_city_province_id'), 'city', ['province_id'], unique=False)
    op.create_index(op.f('ix_city_name_fa'), 'city', ['name_fa'], unique=False)
    op.create_index(op.f('idx_city_county_id'), 'city', ['county_id'], unique=False)
    op.alter_column('city', 'province_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('city', 'county_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_table('app_user',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('app_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone_e164', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('customer', 'staff', 'admin', name='user_role'), server_default=sa.text("'customer'::user_role"), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ux_app_user_phone'), 'app_user', ['phone_e164'], unique=True)
    op.create_index(op.f('ux_app_user_email'), 'app_user', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_table('package_type',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('package_type_pkey')),
    sa.UniqueConstraint('code', name=op.f('package_type_code_key'))
    )
    op.create_index(op.f('idx_packtype_namefa'), 'package_type', [sa.literal_column('lower(name_fa)')], unique=False)
    op.create_table('incoterm',
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('desc_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('modes', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('incoterm_pkey'))
    )
    op.create_index(op.f('idx_incoterm_namefa'), 'incoterm', [sa.literal_column('lower(name_fa)')], unique=False)
    op.create_table('user_otp',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('expires_at > created_at', name=op.f('user_otp_check')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('user_otp_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_otp_pkey'))
    )
    op.create_index(op.f('idx_user_otp_valid'), 'user_otp', ['user_id', 'expires_at'], unique=False, postgresql_where='(consumed_at IS NULL)')
    op.create_index(op.f('idx_user_otp_user'), 'user_otp', ['user_id'], unique=False)
    op.create_table('shipment_mode',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name_fa', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shipment_mode_pkey')),
    sa.UniqueConstraint('code', name=op.f('shipment_mode_code_key'))
    )
    op.create_index(op.f('idx_shipmode_namefa'), 'shipment_mode', [sa.literal_column('lower(name_fa)')], unique=False)
    op.create_table('shipper',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shipper_pkey'))
    )
    # ### end Alembic commands ###







