import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {MemoryRouter,Route,Routes} from "react-router";
import {beforeEach,describe,expect,it,vi} from "vitest";
import ExecutionUnits from "@/pages/ExecutionUnits";
import ProjectTracking from "@/pages/ProjectTracking";
import * as api from "@/lib/api";

vi.mock("@/lib/api",()=>({
 listExecutionUnits:vi.fn(),createExecutionUnit:vi.fn(),getExecutionUnitTimeline:vi.fn(),createExecutionUnitEvent:vi.fn(),
 getSharedTransport:vi.fn(),listEligibleSharedCargo:vi.fn(),listSharedCarrierOptions:vi.fn(),addSharedCargo:vi.fn(),removeSharedCargo:vi.fn(),setSharedCarrier:vi.fn(),
 getOperationalContext:vi.fn(),listProjectConfiguration:vi.fn(),listProjectServiceTypes:vi.fn(),
 getPublicProjectSummary:vi.fn(),listPublicExecutionUnits:vi.fn(),getPublicExecutionTimeline:vi.fn(),
}));
const unit={public_id:"opaque-unit",unit_code:"U-0001",unit_type:"road",display_name:"Truck 1",vehicle_reference:"ABC",lifecycle_status:"in_progress",is_active:true,version:1,latest_checkpoint:"Border",last_update_at:"2026-07-31T12:00:00Z",alerts:{attention_required:false,delayed:true,stale:false}};
const page={page:1,per_page:25,total:1,pages:1};

describe("Release 1.2.0 execution unit pages",()=>{
 beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.getOperationalContext).mockResolvedValue({data:{organization_id:1,permissions:[]}});vi.mocked(api.listExecutionUnits).mockResolvedValue({data:[unit],meta:page});vi.mocked(api.getExecutionUnitTimeline).mockResolvedValue({data:[],meta:{...page,total:0,pages:0}});vi.mocked(api.getSharedTransport).mockResolvedValue({data:{execution:{public_id:"opaque-unit",unit_code:"U-0001",carrier:null},allocations:[],summary:{cargo_count:0,cargo_owner_count:0,source_shipment_count:0,uom_distribution:[],classification:"single_cargo"}}});vi.mocked(api.listEligibleSharedCargo).mockResolvedValue({data:[{public_id:"cargo-a",description:"Cargo A",quantity:"20",uom:{code:"PALLET",symbol:"PALLET"},cargo_owner:{public_label:"Customer A"},shipment_public_id:"shipment-a",project:{public_id:"project",code:"PRJ-1"}}]});vi.mocked(api.listSharedCarrierOptions).mockResolvedValue({data:[{id:7,label:"Carrier X"}]});vi.mocked(api.getPublicProjectSummary).mockResolvedValue({data:{project_public_id:"project",project_code:"PRJ-1",status:"in_progress",total_units:1,delivered_units:0,in_progress_units:1,delayed_units:1,attention_required:0,units_without_recent_update:0,progress_percentage:0,last_update_at:null,threshold_policy:{version:"stale-v1",stale_after_hours:24}}});vi.mocked(api.listPublicExecutionUnits).mockResolvedValue({data:[unit],meta:page});vi.mocked(api.getPublicExecutionTimeline).mockResolvedValue({data:[],meta:{...page,total:0,pages:0}})});
 it("renders localized expert terminology and lazy-loads the timeline",async()=>{render(<MemoryRouter initialEntries={["/operations/projects/project/units"]}><Routes><Route path="/operations/projects/:projectId/units" element={<ExecutionUnits/>}/></Routes></MemoryRouter>);expect(await screen.findByText("بخش‌های اجرایی حمل")).toBeInTheDocument();expect(screen.getByText("U-0001")).toHaveAttribute("dir","ltr");expect(api.getExecutionUnitTimeline).not.toHaveBeenCalled();await userEvent.click(screen.getByRole("button",{name:"مشاهده"}));await waitFor(()=>expect(api.getExecutionUnitTimeline).toHaveBeenCalledWith("project","opaque-unit"));expect(screen.getByText("هنوز رویدادی ثبت نشده است.")).toBeInTheDocument()});
 it("allocates cargo, persists a carrier, and localizes the shared-transport classification",async()=>{const user=userEvent.setup();render(<MemoryRouter initialEntries={["/operations/projects/project/units"]}><Routes><Route path="/operations/projects/:projectId/units" element={<ExecutionUnits/>}/></Routes></MemoryRouter>);await user.click(await screen.findByRole("button",{name:"مشاهده"}));await screen.findByText("بارهای اجرای مشترک");expect(screen.getByText("یک بار")).toBeInTheDocument();expect(screen.queryByText("single_cargo")).not.toBeInTheDocument();await user.selectOptions(screen.getByLabelText("انتخاب بار قابل تخصیص"),"cargo-a");await user.click(screen.getByRole("button",{name:"تخصیص بار"}));await waitFor(()=>expect(api.addSharedCargo).toHaveBeenCalledWith("project","opaque-unit","cargo-a","20"));await user.selectOptions(screen.getByLabelText("انتخاب کریر"),"7");await user.click(screen.getByRole("button",{name:"ذخیره کریر"}));await waitFor(()=>expect(api.setSharedCarrier).toHaveBeenCalledWith("project","opaque-unit",7))});
 it("keeps an ineligible current Carrier readable but out of new candidates",async()=>{vi.mocked(api.getSharedTransport).mockResolvedValue({data:{execution:{public_id:"opaque-unit",unit_code:"U-0001",carrier:{id:7,label:"Carrier B"}},allocations:[],summary:{cargo_count:0,cargo_owner_count:0,source_shipment_count:0,uom_distribution:[],classification:"single_cargo"}}});vi.mocked(api.listSharedCarrierOptions).mockResolvedValueOnce({data:[]}).mockResolvedValueOnce({data:[{id:7,label:"Carrier B"}]});const user=userEvent.setup();render(<MemoryRouter initialEntries={["/operations/projects/project/units"]}><Routes><Route path="/operations/projects/:projectId/units" element={<ExecutionUnits/>}/></Routes></MemoryRouter>);const open=await screen.findByRole("button",{name:"مشاهده"});await user.click(open);await screen.findByText(/کریر: Carrier B/);expect(screen.getByLabelText("انتخاب کریر").querySelector('option[value="7"]')).toBeNull();await user.click(open);await waitFor(()=>expect(screen.getByLabelText("انتخاب کریر").querySelector('option[value="7"]')).not.toBeNull())});
 it("does not mount Project Configuration or issue its requests without entitlement",async()=>{render(<MemoryRouter initialEntries={["/operations/projects/project/units"]}><Routes><Route path="/operations/projects/:projectId/units" element={<ExecutionUnits/>}/></Routes></MemoryRouter>);await screen.findByText("بخش‌های اجرایی حمل");await waitFor(()=>expect(api.getOperationalContext).toHaveBeenCalled());expect(screen.queryByText("Project Configuration")).not.toBeInTheDocument();expect(api.listProjectConfiguration).not.toHaveBeenCalled();expect(api.listProjectServiceTypes).not.toHaveBeenCalled();expect(screen.getByRole("button",{name:"مشاهده"})).toBeEnabled()});
 it("renders customer aggregate, filters, disclosure, and lazy timeline",async()=>{render(<MemoryRouter initialEntries={["/project/track/code"]}><Routes><Route path="/project/track/:trackingCode" element={<ProjectTracking/>}/></Routes></MemoryRouter>);expect(await screen.findByText("Project PRJ-1")).toBeInTheDocument();expect(screen.getByText("This is process and event tracking, not GPS or live map tracking.")).toBeInTheDocument();expect(api.getPublicExecutionTimeline).not.toHaveBeenCalled();await userEvent.click(screen.getByRole("button",{name:"View timeline"}));await waitFor(()=>expect(api.getPublicExecutionTimeline).toHaveBeenCalledWith("code","opaque-unit"));expect(screen.queryByText(/internal/i)).not.toBeInTheDocument()});
});
