import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { routeSelectClass } from "@/components/RouteAuthoringSection";
import {
  createExpertLocation, fetchCanonicalAdmin1, fetchCanonicalCities, fetchCanonicalCountries,
  listLogisticsPoints, listLogisticsPointTypes,
  type CanonicalAdmin1, type CanonicalCity, type CanonicalCountry, type LogisticsPointTypeView,
  type LogisticsPointView, type OperationalLocationRef,
} from "@/lib/api";

export type CanonicalEndpointRef = OperationalLocationRef & { country_id: number };

export default function CanonicalLocationPicker({label,value,onChange,allowCreate=true}:{
  label:string; value:CanonicalEndpointRef|null; onChange:(value:CanonicalEndpointRef|null)=>void; allowCreate?:boolean;
}) {
  const [countries,setCountries]=useState<CanonicalCountry[]>([]),[admin1,setAdmin1]=useState<CanonicalAdmin1[]>([]),[cities,setCities]=useState<CanonicalCity[]>([]),[locations,setLocations]=useState<LogisticsPointView[]>([]),[types,setTypes]=useState<LogisticsPointTypeView[]>([]);
  const [country,setCountry]=useState<CanonicalCountry>(),[region,setRegion]=useState<CanonicalAdmin1>(),[city,setCity]=useState<CanonicalCity>();
  const [location,setLocation]=useState(""),[countryQuery,setCountryQuery]=useState(""),[regionQuery,setRegionQuery]=useState(""),[query,setQuery]=useState(""),[cityQuery,setCityQuery]=useState(""),[adding,setAdding]=useState(false),[name,setName]=useState(""),[type,setType]=useState(""),[address,setAddress]=useState(""),[description,setDescription]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState("initial"),[error,setError]=useState("");
  useEffect(()=>{void Promise.all([fetchCanonicalCountries(),listLogisticsPointTypes()]).then(([geo,kinds])=>{setCountries(geo.items);setTypes(kinds.items.filter(item=>item.is_active));}).catch(()=>setError("دریافت جغرافیای معتبر ممکن نشد.")).finally(()=>setLoading(""));},[]);
  const chooseCountry=async(id:string)=>{const row=countries.find(item=>String(item.id)===id);setCountry(row);setRegion(undefined);setCity(undefined);setAdmin1([]);setCities([]);setLocations([]);setLocation("");onChange(null);if(row){setLoading("admin1");setError("");try{setAdmin1((await fetchCanonicalAdmin1(row.code)).items);}catch{setError("دریافت استان/ایالت ممکن نشد.");}finally{setLoading("");}}};
  const chooseRegion=async(identity:string)=>{const row=admin1.find(item=>String(item.geoname_id)===identity);setRegion(row);setCity(undefined);setCities([]);setLocations([]);setLocation("");onChange(null);if(row){setLoading("cities");setError("");try{setCities((await fetchCanonicalCities(row.geoname_id)).items);}catch{setError("دریافت شهرها ممکن نشد.");}finally{setLoading("");}}};
  const chooseCity=async(identity:string)=>{const row=cities.find(item=>String(item.geoname_id)===identity);setCity(row);setLocation("");onChange(row&&country?{country_id:country.id,source_type:"city",source_id:row.source_id}:null);if(row){setLoading("locations");setError("");try{setLocations((await listLogisticsPoints({city_geoname_id:row.geoname_id,active:"true",per_page:100})).items);}catch{setError("دریافت مکان‌های سازمان ممکن نشد.");}finally{setLoading("");}}};
  const searchCities=async()=>{if(region){setLoading("cities");setError("");try{setCities((await fetchCanonicalCities(region.geoname_id,cityQuery)).items);}catch{setError("جست‌وجوی شهر ممکن نشد.");}finally{setLoading("");}}};
  const searchLocations=async()=>{if(city){setLoading("locations");setError("");try{setLocations((await listLogisticsPoints({city_geoname_id:city.geoname_id,q:query,active:"true",per_page:100})).items);}catch{setError("جست‌وجوی مکان سازمان ممکن نشد.");}finally{setLoading("");}}};
  const chooseLocation=(publicId:string)=>{setLocation(publicId);const row=locations.find(item=>item.public_id===publicId);onChange(row&&country?{country_id:country.id,source_type:"logistics_point",source_id:row.public_id}:city&&country?{country_id:country.id,source_type:"city",source_id:city.source_id}:null);};
  const create=async()=>{if(!city||!name.trim())return;setBusy(true);setError("");try{const result=await createExpertLocation({name,city_geoname_id:city.geoname_id,point_type_public_id:type||null,address:address||null,description:description||null});setLocations(old=>[result.item,...old]);setAdding(false);setName("");setLocation(result.item.public_id);if(country)onChange({country_id:country.id,source_type:"logistics_point",source_id:result.item.public_id});}catch(caught){setError(caught instanceof Error?caught.message:"ایجاد مکان ممکن نشد.");}finally{setBusy(false);}};
  const includes=(values:Array<string|undefined>,term:string)=>!term.trim()||values.some(value=>value?.toLocaleLowerCase().includes(term.trim().toLocaleLowerCase()));
  const visibleCountries=countries.filter(item=>includes([item.name_fa,item.name_en,item.code],countryQuery));
  const visibleAdmin1=admin1.filter(item=>includes([item.name_fa,item.name_en,item.code],regionQuery));
  return <fieldset className="space-y-3 rounded-xl border p-3"><legend className="px-1 font-medium">{label}</legend>
    <label className="block space-y-2 text-sm">کشور<Input aria-label={`${label} جست‌وجوی کشور`} value={countryQuery} onChange={e=>setCountryQuery(e.target.value)} placeholder="جست‌وجوی کشور"/><select aria-label={`${label} کشور`} className={routeSelectClass} value={country?.id||""} onChange={e=>void chooseCountry(e.target.value)}><option value="">انتخاب کشور</option>{visibleCountries.map(item=><option key={item.id} value={item.id}>{item.name_fa} · {item.code}</option>)}</select></label>
    <label className="block space-y-2 text-sm">استان / ایالت<Input aria-label={`${label} جست‌وجوی استان`} disabled={!country} value={regionQuery} onChange={e=>setRegionQuery(e.target.value)} placeholder="جست‌وجوی استان / ایالت"/><select aria-label={`${label} استان`} className={routeSelectClass} disabled={!country} value={region?.geoname_id||""} onChange={e=>void chooseRegion(e.target.value)}><option value="">انتخاب استان / ایالت</option>{visibleAdmin1.map(item=><option key={item.geoname_id} value={item.geoname_id}>{item.name_fa}</option>)}</select></label>
    <label className="block space-y-2 text-sm">شهر<div className="flex gap-2"><Input aria-label={`${label} جست‌وجوی شهر`} disabled={!region} value={cityQuery} onChange={e=>setCityQuery(e.target.value)} placeholder="جست‌وجوی شهر"/><Button type="button" variant="outline" disabled={!region} onClick={()=>void searchCities()}>جست‌وجو</Button></div><select aria-label={`${label} شهر`} className={routeSelectClass} disabled={!region} value={city?.geoname_id||""} onChange={e=>void chooseCity(e.target.value)}><option value="">انتخاب شهر</option>{cities.map(item=><option key={item.geoname_id} value={item.geoname_id}>{item.name_fa} / {item.name_en}</option>)}</select></label>
    <label className="block space-y-2 text-sm">مکان سازمان (اختیاری)<div className="flex gap-2"><Input aria-label={`${label} جست‌وجوی مکان سازمان`} disabled={!city} value={query} onChange={e=>setQuery(e.target.value)} placeholder="کارخانه، انبار، پایانه…"/><Button type="button" variant="outline" disabled={!city} onClick={()=>void searchLocations()}>جست‌وجو</Button></div><select aria-label={`${label} مکان سازمان`} className={routeSelectClass} disabled={!city} value={location} onChange={e=>chooseLocation(e.target.value)}><option value="">بدون مکان سازمانی؛ خود شهر</option>{locations.map(item=><option key={item.public_id} value={item.public_id}>{item.fa_name}{item.governance_state==="PENDING_REVIEW"?" · در انتظار بررسی":""}</option>)}</select></label>
    {allowCreate&&city&&<Button type="button" variant="outline" onClick={()=>setAdding(value=>!value)}>{adding?"بستن فرم":"افزودن مکان تازه"}</Button>}
    {adding&&<div className="grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-2"><label>نام مکان<Input required value={name} onChange={e=>setName(e.target.value)}/></label><label>نوع (اختیاری)<select className={routeSelectClass} value={type} onChange={e=>setType(e.target.value)}><option value="">بدون نوع</option>{types.map(item=><option key={item.public_id} value={item.public_id}>{item.fa_name}</option>)}</select></label><label>نشانی (اختیاری)<Input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>توضیحات (اختیاری)<Input value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="sm:col-span-2"><Button type="button" disabled={busy||!name.trim()} onClick={()=>void create()}>{busy?"در حال ثبت…":"ایجاد و استفاده فوری"}</Button><p className="mt-1 text-xs text-slate-600">مکان بلافاصله قابل استفاده و برای بررسی مدیر سازمان علامت‌گذاری می‌شود.</p></div></div>}
    {loading&&<p role="status" className="text-sm text-slate-600">{loading==="initial"?"در حال دریافت جغرافیای معتبر…":loading==="admin1"?"در حال دریافت استان‌ها / ایالت‌ها…":loading==="cities"?"در حال دریافت شهرها…":"در حال جست‌وجوی مکان‌های سازمان…"}</p>}
    {!loading&&region&&cities.length===0&&<p className="text-sm text-slate-600">شهر منطبق یافت نشد.</p>}
    {!loading&&city&&locations.length===0&&<p className="text-sm text-slate-600">مکان سازمانی منطبق یافت نشد؛ خود شهر همچنان قابل انتخاب است.</p>}
    {value&&<p className="text-sm text-emerald-800">مقصد ساخت‌یافته انتخاب شد.</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
  </fieldset>;
}
