import { useCallback, useEffect, useState } from "react";
import { AlertCircle, Download, Trash2, Upload } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea";
import { deleteCaseDocument, downloadCaseDocument, fetchCaseDocuments, uploadCaseDocument, type CaseDocumentFile, type CaseDocumentsPayload } from "@/lib/api";

export default function CaseDocumentsTab({caseId}:{caseId:number}) {
 const [data,setData]=useState<CaseDocumentsPayload|null>(null); const [miscTitle,setMiscTitle]=useState(""); const [miscDescription,setMiscDescription]=useState(""); const [error,setError]=useState("");
 const load=useCallback(()=>fetchCaseDocuments(caseId).then(setData).catch(e=>setError(e.message)),[caseId]); useEffect(()=>{ void load(); },[load]);
 const send=async(requirementId:number|null,file:File,replace=false)=>{const f=new FormData();f.append("file",file);if(requirementId===null){f.append("title",miscTitle);f.append("description",miscDescription);} try{await uploadCaseDocument(caseId,requirementId,f,replace);setMiscTitle("");setMiscDescription("");setError("");load();}catch(e){setError(e instanceof Error?e.message:"خطا");}};
 const remove=async(id:number)=>{const reason=window.prompt("دلیل حذف را وارد کنید");if(reason){await deleteCaseDocument(caseId,id,reason);load();}};
 if(!data)return <p>{error||"در حال بارگذاری..."}</p>;
 const fileRow=(f:CaseDocumentFile)=><div key={f.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3"><span>{f.original_filename} · نسخه {f.version_number} · {Math.ceil(f.file_size_bytes/1024)} KB</span><div><Button variant="ghost" onClick={()=>downloadCaseDocument(caseId,f.id,f.original_filename)}><Download className="h-4 w-4"/> دریافت</Button>{f.status==="active"&&<Button variant="ghost" onClick={()=>remove(f.id)}><Trash2 className="h-4 w-4"/> حذف</Button>}</div></div>;
 return <div className="space-y-4">
  <div className="grid gap-3 md:grid-cols-5">{Object.entries(data.summary).map(([k,v])=><Card key={k}><CardContent className="p-4"><b>{v}</b><p className="text-xs text-slate-500">{({total_requirements:"کل نیازمندی‌ها",required_requirements:"الزامی",uploaded_requirements:"بارگذاری‌شده",missing_required_requirements:"الزامی ناقص",miscellaneous_file_count:"سایر مستندات"} as Record<string,string>)[k]}</p></CardContent></Card>)}</div>
  {data.summary.missing_required_requirements>0&&<p className="flex gap-2 rounded-xl bg-amber-50 p-3 text-amber-800"><AlertCircle/> موارد الزامی ناقص هستند؛ این هشدار مانع ادامه یا بستن پرونده نیست.</p>}
  {data.requirements.map(r=><Card key={r.id}><CardHeader><CardTitle className="flex gap-2">{r.title}<Badge>{r.is_required?"الزامی":"اختیاری"}</Badge><Badge variant="outline">{r.complete?"تکمیل":"ناقص"}</Badge></CardTitle><p>{r.description}</p></CardHeader><CardContent className="space-y-3"><p>فرمت‌ها: {r.allowed_formats.join("، ")} · حداکثر {Math.ceil(r.max_file_size_bytes/1048576)} MB · {r.max_active_file_count} فایل</p>{r.active_files.map(fileRow)}<label className="inline-flex cursor-pointer gap-2 rounded-lg border p-2"><Upload className="h-4 w-4"/> {r.active_files.length?"جایگزینی / نسخه جدید":"بارگذاری"}<input className="hidden" type="file" onChange={e=>e.target.files?.[0]&&send(r.id,e.target.files[0],r.active_files.length>0)}/></label>{r.versions.length>r.active_files.length&&<details><summary>تاریخچه نسخه‌ها</summary>{r.versions.map(fileRow)}</details>}</CardContent></Card>)}
  <Card><CardHeader><CardTitle>سایر مستندات</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="عنوان الزامی" value={miscTitle} onChange={e=>setMiscTitle(e.target.value)}/><Textarea placeholder="توضیحات اختیاری" value={miscDescription} onChange={e=>setMiscDescription(e.target.value)}/><input type="file" disabled={!miscTitle.trim()} onChange={e=>e.target.files?.[0]&&send(null,e.target.files[0])}/>{data.miscellaneous.map(fileRow)}</CardContent></Card>
  {error&&<p className="text-red-600">{error}</p>}
 </div>;
}
