import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { associateDocumentArtifact, assessDocumentArtifact, createTransitionOverride, getDocumentMaterializationPreview, getNextTransitionReadiness, listDocumentReadinessRequirements, materializeDocumentRequirements, resolveDocumentApplicability, type DocumentReadinessRequirement, type ExecutionMilestone, type TransitionReadiness } from "@/lib/api";

export default function DocumentReadinessSection({shipmentPublicId,shipmentVersion,readOnly=false}:{shipmentPublicId:string;shipmentVersion:number;readOnly?:boolean}) {
  const [rows,setRows]=useState<DocumentReadinessRequirement[]>([]); const [preview,setPreview]=useState<Awaited<ReturnType<typeof getDocumentMaterializationPreview>>["data"]>(); const [next,setNext]=useState<TransitionReadiness>(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{setError("");const [p,r,n]=await Promise.all([getDocumentMaterializationPreview(shipmentPublicId),listDocumentReadinessRequirements(shipmentPublicId),getNextTransitionReadiness(shipmentPublicId)]);setPreview(p.data);setRows(r.data);setNext(n.data||undefined)}catch(e){setError(e instanceof Error?e.message:String(e))}},[shipmentPublicId]); useEffect(()=>{void load()},[load]);
  const run=async(f:()=>Promise<unknown>)=>{try{setBusy(true);await f();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const associate=(r:DocumentReadinessRequirement)=>{const a=prompt("Existing artifact public ID");if(a)void run(()=>associateDocumentArtifact(shipmentPublicId,r,a.trim()))};
  const assess=(r:DocumentReadinessRequirement,d:string)=>{const reason=d==="REJECTED"?prompt("Rejection reason")||"":undefined;if(d!=="REJECTED"||reason)void run(()=>assessDocumentArtifact(shipmentPublicId,r,d,reason))};
  const resolve=(r:DocumentReadinessRequirement,d:string)=>{const reason=prompt("Applicability reason");if(reason)void run(()=>resolveDocumentApplicability(shipmentPublicId,r,d,reason))};
  const override=(r:DocumentReadinessRequirement)=>{const milestone=prompt("Target milestone public ID"),authority=prompt("Override authority"),reason=prompt("Override reason");if(milestone&&authority&&reason)void run(()=>createTransitionOverride(shipmentPublicId,r,{public_id:milestone} as ExecutionMilestone,authority,reason))};
  return <section className="space-y-3 rounded border bg-white p-5" aria-label="Document Readiness"><h3 className="font-semibold">Document Readiness</h3>{error&&<p role="alert" className="text-red-700">{error}</p>}{!preview?.initialized&&!readOnly&&<div><p>{preview?.requirements.length||0} configured requirements</p>{preview?.findings.map(f=><p key={f.code}>{f.message}</p>)}<Button disabled={busy||!preview?.confirmation_allowed} onClick={()=>void run(()=>materializeDocumentRequirements(shipmentPublicId,shipmentVersion))}>Confirm document materialization</Button></div>}<h4 className="font-medium">Required Documents</h4>{!rows.length&&<p>No materialized document requirements.</p>}{rows.map(r=><article key={r.public_id} className="rounded border p-3"><strong>{r.title}</strong><p>{r.requirement_level} · {r.applicability_state} · needs {r.required_assessment_level}</p><p>Current artifact/assessment: {r.artifact?`${r.artifact.filename} v${r.artifact.version} · ${r.artifact.assessment}`:"Missing"}</p>{!readOnly&&<div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>associate(r)}>Associate/replace</Button>{r.requirement_level==="CONDITIONAL"&&r.applicability_state==="UNRESOLVED"&&<><Button size="sm" onClick={()=>resolve(r,"APPLICABLE")}>Applicable</Button><Button size="sm" variant="outline" onClick={()=>resolve(r,"NOT_APPLICABLE")}>Not applicable</Button></>}{r.artifact&&<><Button size="sm" variant="outline" onClick={()=>assess(r,"REVIEW_STARTED")}>Start review</Button><Button size="sm" onClick={()=>assess(r,"APPROVED")}>Approve</Button><Button size="sm" variant="destructive" onClick={()=>assess(r,"REJECTED")}>Reject</Button><Button size="sm" onClick={()=>assess(r,"VERIFIED")}>Verify</Button></>}<Button size="sm" variant="outline" onClick={()=>override(r)}>Controlled override</Button></div>}</article>)}<h4 className="font-medium">Next Action / Blockers</h4>{next?<div><p>{next.allowed?"Ready":"Blocked"} for {next.target_action}</p>{next.blocking_requirements.map(b=><p className="text-red-700" key={b.requirement_public_id+b.code}>{b.code}: {b.title}</p>)}{next.warnings.map(w=><p className="text-amber-700" key={w.requirement_public_id+w.code}>{w.code}: {w.title}</p>)}</div>:<p>No next action readiness available.</p>}</section>;
}
