import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, BookOpen, ChevronLeft, ExternalLink, FileText, Loader2, Pencil, RefreshCw, Search, ShieldCheck, Tags } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { fetchDocumentCatalog, fetchDocumentCatalogDefinition, transitionDocumentCatalogDefinition, updateDocumentCatalogDefinition, type DocumentCatalogDefinition, type DocumentCatalogFilters, type DocumentCatalogLifecycle, type DocumentCatalogMetadataUpdate, type DocumentSourceReviewStatus } from "@/lib/api";

const families: Record<string,string> = {COMMERCIAL:"تجاری",TRANSPORT:"حمل‌ونقل",FORWARDING:"فورواردری",CUSTOMS:"گمرکی",WAREHOUSE:"انبار",RELEASE:"آزادسازی",CERTIFICATE:"گواهی",PERMIT_AUTHORIZATION:"مجوز و اختیار",INSURANCE:"بیمه",FINANCE:"مالی",SAFETY:"ایمنی",OPERATIONAL_NOTICE:"اعلامیه عملیاتی"};
const lifecycle: Record<string,string> = {DRAFT:"پیش‌نویس",REVIEWED:"بازبینی‌شده",SOURCE_CONFIRMED:"منبع تأییدشده",ACTIVE:"فعال",DEPRECATED:"منسوخ"};
const reviews: Record<string,string> = {VERIFIED:"راستی‌آزمایی‌شده",SOURCE_CONFIRMED:"منبع تأییدشده",SOURCE_CONFIRMATION_REQUIRED:"نیازمند تأیید منبع",DOMAIN_CONFIRMATION_REQUIRED:"نیازمند تأیید تخصصی",SUPERSEDED:"جایگزین‌شده"};
const modes: Record<string,string> = {ROAD:"جاده‌ای",SEA:"دریایی",AIR:"هوایی",RAIL:"ریلی",MULTIMODAL:"چندوجهی",MODE_INDEPENDENT:"مستقل از شیوه حمل"};
const stages: Record<string,string> = {PRE_SHIPMENT:"پیش از حمل",BOOKING:"رزرو",ORIGIN:"مبدأ",IN_TRANSIT:"در مسیر",ARRIVAL:"ورود",WAREHOUSE:"انبار",CUSTOMS_DECLARATION:"اظهار گمرکی",CUSTOMS_CLEARANCE:"ترخیص گمرکی",RELEASE:"آزادسازی",DELIVERY:"تحویل",POST_DELIVERY:"پس از تحویل"};
const scopes: Record<string,string> = {REQUEST:"درخواست",PROJECT:"پروژه",OPERATIONAL_SHIPMENT:"محموله عملیاتی",CARGO:"کالا",MULTIPLE:"چند حوزه"};
const aliasKinds: Record<string,string> = {COMMON_NAME:"نام رایج",ABBREVIATION:"اختصار",TRANSLATION_VARIANT:"گونه ترجمه",LEGACY_NAME:"نام پیشین"};
const transitions: Record<DocumentCatalogLifecycle,DocumentCatalogLifecycle[]> = {DRAFT:["REVIEWED"],REVIEWED:["DRAFT","SOURCE_CONFIRMED"],SOURCE_CONFIRMED:["REVIEWED","ACTIVE"],ACTIVE:["DEPRECATED"],DEPRECATED:[]};
const safeUrl=(value?:string|null)=>{try{const url=new URL(value||"");return ["https:","http:"].includes(url.protocol)?url.toString():null}catch{return null}};
const key=()=>globalThis.crypto?.randomUUID?.() || `catalog-${Date.now()}-${Math.random()}`;

function StatusBadge({value,kind}:{value:string;kind:"life"|"review"}) { const label=kind==="life"?lifecycle[value]:reviews[value]; const tone=value==="ACTIVE"||value==="VERIFIED"?"bg-emerald-50 text-emerald-700 border-emerald-200":value.includes("REQUIRED")?"bg-amber-50 text-amber-800 border-amber-200":value==="DEPRECATED"||value==="SUPERSEDED"?"bg-slate-100 text-slate-600":"bg-blue-50 text-blue-700 border-blue-200"; return <Badge variant="outline" className={tone}>{label||value}</Badge> }
function Empty({children}:{children:React.ReactNode}) { return <div className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-500">{children}</div> }
function Chips({values,labels}:{values:string[];labels:Record<string,string>}) { return values.length?<div className="flex flex-wrap gap-2">{values.map(x=><Badge key={x} variant="secondary">{labels[x]||x}</Badge>)}</div>:<Empty>اطلاعاتی ثبت نشده است.</Empty> }
function Section({title,children}:{title:string;children:React.ReactNode}) { return <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-900">{title}</h3>{children}</section> }

type EditState=Pick<DocumentCatalogDefinition,"name_fa"|"name_en"|"description_fa"|"description_en"|"family_code"|"reference_number_label_fa"|"reference_number_label_en"|"expiry_applicable"|"organization_overridable"|"source_review_status">;
function MetadataEditor({item,onSaved,onCancel}:{item:DocumentCatalogDefinition;onSaved:(x:DocumentCatalogDefinition)=>void;onCancel:()=>void}) {
  const [form,setForm]=useState<EditState>({...item}); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const save=async()=>{setSaving(true);setError("");try{const payload:DocumentCatalogMetadataUpdate={expected_revision:item.revision,...form};onSaved(await updateDocumentCatalogDefinition(item.public_id,payload,key()))}catch(e){const message=e instanceof Error?e.message:"خطای نامشخص";setError(message.includes("revision conflict")?"این رکورد پس از باز شدن صفحه تغییر کرده است. اطلاعات را دوباره بارگذاری و تغییرات را بررسی کنید.":message)}finally{setSaving(false)}};
  return <Section title="ویرایش کنترل‌شده فراداده"><div className="grid gap-3 md:grid-cols-2">
    <label className="text-sm">نام فارسی<Input value={form.name_fa||""} onChange={e=>setForm({...form,name_fa:e.target.value})}/></label><label className="text-sm">English name<Input dir="ltr" value={form.name_en||""} onChange={e=>setForm({...form,name_en:e.target.value})}/></label>
    <label className="text-sm">توضیح فارسی<Textarea value={form.description_fa||""} onChange={e=>setForm({...form,description_fa:e.target.value})}/></label><label className="text-sm">English description<Textarea dir="ltr" value={form.description_en||""} onChange={e=>setForm({...form,description_en:e.target.value})}/></label>
    <label className="text-sm">خانواده<select className="mt-1 h-10 w-full rounded-md border bg-white px-3" value={form.family_code||""} onChange={e=>setForm({...form,family_code:e.target.value||null})}><option value="">انتخاب نشده</option>{Object.entries(families).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label className="text-sm">وضعیت بررسی منبع<select className="mt-1 h-10 w-full rounded-md border bg-white px-3" value={form.source_review_status} onChange={e=>setForm({...form,source_review_status:e.target.value as DocumentSourceReviewStatus})}>{Object.entries(reviews).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label className="text-sm">برچسب شماره مرجع فارسی<Input value={form.reference_number_label_fa||""} onChange={e=>setForm({...form,reference_number_label_fa:e.target.value})}/></label><label className="text-sm">English reference label<Input dir="ltr" value={form.reference_number_label_en||""} onChange={e=>setForm({...form,reference_number_label_en:e.target.value})}/></label>
    <label className="flex items-center gap-2 text-sm"><Checkbox checked={form.expiry_applicable===true} onCheckedChange={v=>setForm({...form,expiry_applicable:!!v})}/>تاریخ انقضا کاربرد دارد</label><label className="flex items-center gap-2 text-sm"><Checkbox checked={form.organization_overridable} onCheckedChange={v=>setForm({...form,organization_overridable:!!v})}/>سیاست سازمان می‌تواند نحوه الزام را تنظیم کند</label>
  </div>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex gap-2"><Button onClick={save} disabled={saving}>{saving&&<Loader2 className="ml-2 h-4 w-4 animate-spin"/>}ذخیره</Button><Button variant="outline" onClick={onCancel}>انصراف</Button></div></Section>
}

function LifecycleActions({item,onSaved}:{item:DocumentCatalogDefinition;onSaved:(x:DocumentCatalogDefinition)=>void}) { const [target,setTarget]=useState<DocumentCatalogLifecycle|null>(null);const [approval,setApproval]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState(""); const act=async()=>{if(!target)return;setBusy(true);setError("");try{onSaved(await transitionDocumentCatalogDefinition(item.public_id,{expected_revision:item.revision,target_status:target,approval_reference:approval||undefined},key()));setTarget(null);setApproval("")}catch(e){const m=e instanceof Error?e.message:"خطا";setError(m.includes("revision conflict")?"این رکورد پس از باز شدن صفحه تغییر کرده است. اطلاعات را دوباره بارگذاری کنید.":({"Confirmed source review is required":"ابتدا بررسی منبع باید تأیید شود.","Confirmed provenance is required":"منبع و مستندات تأییدشده لازم است.","Bilingual names and family are required":"نام فارسی، نام انگلیسی و خانواده باید تکمیل شوند.","Jurisdiction classification is required":"قلمرو کاربرد باید مشخص شود.","Confirmed provenance is required for every jurisdiction":"برای همه قلمروهای کاربرد، منبع تأییدشده لازم است.","Existing organization policy conflicts must be resolved before activation":"تعارض سیاست سازمانی باید پیش از فعال‌سازی رفع شود."}[m]||m))}finally{setBusy(false)}}; return <Section title="۷. چرخه حیات"><div className="flex items-center gap-2"><StatusBadge value={item.catalog_lifecycle_status} kind="life"/><span className="text-xs text-slate-500" dir="ltr">{item.catalog_lifecycle_status}</span></div><p className="text-sm text-slate-600">تغییر وضعیت یک اقدام حاکمیتی و مشروط به اعتبارسنجی سرور است؛ منبع تأییدشده با وضعیت فعال یکسان نیست.</p>{transitions[item.catalog_lifecycle_status].length?<div className="flex flex-wrap gap-2">{transitions[item.catalog_lifecycle_status].map(x=><Button key={x} variant="outline" onClick={()=>setTarget(x)}>ارتقا/تغییر به «{lifecycle[x]}»</Button>)}</div>:<p className="text-sm text-slate-500">گذار دیگری برای این وضعیت مجاز نیست.</p>}{target&&<div className="space-y-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-medium">تأیید اقدام: {lifecycle[item.catalog_lifecycle_status]} ← {lifecycle[target]}</p>{target==="ACTIVE"&&<p className="text-sm">فعال‌سازی فقط پس از تکمیل نام‌های دوزبانه، طبقه‌بندی، قلمرو و منابع تأییدشده انجام می‌شود و هیچ سندی را الزامی نمی‌کند.</p>}{target==="DEPRECATED"&&<p className="text-sm">ارجاعات تاریخی معتبر می‌مانند؛ این نوع سند برای استفاده حاکمیتی جدید توصیه نخواهد شد.</p>}<Input placeholder="مرجع تأیید (اختیاری)" value={approval} onChange={e=>setApproval(e.target.value)}/><div className="flex gap-2"><Button onClick={act} disabled={busy}>{busy?"در حال بررسی...":"تأیید و اجرا"}</Button><Button variant="ghost" onClick={()=>setTarget(null)}>انصراف</Button></div></div>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}</Section> }

function Detail({item,onRefresh,onBack}:{item:DocumentCatalogDefinition;onRefresh:(x?:DocumentCatalogDefinition)=>void;onBack:()=>void}) { const [editing,setEditing]=useState(false);return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" onClick={onBack}><ChevronLeft className="ml-1 h-4 w-4"/>بازگشت به فهرست</Button><div className="flex gap-2"><Button variant="outline" onClick={()=>onRefresh()}><RefreshCw className="ml-2 h-4 w-4"/>بارگذاری دوباره</Button><Button onClick={()=>setEditing(!editing)}><Pencil className="ml-2 h-4 w-4"/>ویرایش فراداده</Button></div></div>
  <Card className="border-blue-100 bg-blue-50"><CardContent className="p-5"><h2 className="text-xl font-bold">{item.name_fa||item.title}</h2><p dir="ltr" className="mt-1 text-left text-slate-700">{item.name_en||"نام انگلیسی ثبت نشده"}</p><code dir="ltr" className="mt-3 inline-block rounded bg-white px-2 py-1 text-sm">{item.code}</code><p className="mt-4 text-sm text-blue-900">این مورد «نوع سند» مرجع است؛ فایل بارگذاری‌شده، شماره مرجع یا الزام یک سازمان نیست.</p></CardContent></Card>
  {editing&&<MetadataEditor item={item} onCancel={()=>setEditing(false)} onSaved={x=>{setEditing(false);onRefresh(x)}}/>}
  <div className="grid gap-4 xl:grid-cols-2"><Section title="۱. هویت و نام‌گذاری"><p>{item.description_fa||item.description||"توضیح فارسی ثبت نشده است."}</p><p dir="ltr" className="text-left text-sm text-slate-600">{item.description_en||"English description is not available."}</p><dl className="grid grid-cols-2 gap-2 text-sm"><dt>کد سیستمی</dt><dd dir="ltr">{item.code}</dd><dt>برچسب شماره مرجع</dt><dd>{item.reference_number_label_fa||"—"} <span dir="ltr">{item.reference_number_label_en||""}</span></dd></dl></Section>
  <Section title="۲. طبقه‌بندی"><p><strong>خانواده:</strong> {families[item.family_code||""]||"طبقه‌بندی نشده"}</p><p><strong>تاریخ انقضا:</strong> {item.expiry_applicable==null?"نامشخص":item.expiry_applicable?"کاربرد دارد":"کاربرد ندارد"}</p><p><strong>تنظیم‌پذیری سیاست سازمان:</strong> {item.organization_overridable?"سازمان می‌تواند الزام و شرایط استفاده را در سیاست خود تنظیم کند.":"واژگان و سیاست پایه در سطح پلتفرم کنترل می‌شود."}</p><p className="text-xs text-slate-500">این اختیار به معنی امکان تغییر نام، کد یا هویت مرجع پلتفرم نیست.</p></Section>
  <Section title="۳. دامنه کاربرد"><h4 className="text-sm font-medium">قلمرو کاربرد</h4>{item.jurisdictions.length?<div className="flex flex-wrap gap-2">{item.jurisdictions.map(x=><Badge key={x.key||x.country_code}>{x.kind==="GLOBAL"?"جهانی":x.kind==="INTERNATIONAL"?"بین‌المللی":`کشور ${x.country_code}`}</Badge>)}</div>:<Empty>قلمرو کاربرد مشخص نشده است.</Empty>}<h4 className="text-sm font-medium">شیوه حمل</h4><Chips values={item.modes} labels={modes}/><h4 className="text-sm font-medium">مرحله فرایند</h4><Chips values={item.stages} labels={stages}/><h4 className="text-sm font-medium">حوزه کسب‌وکار</h4><Chips values={item.business_scopes} labels={scopes}/></Section>
  <Section title="۴. نام‌های جایگزین"><p className="text-sm text-slate-600">هر نام جایگزین، نام دیگری برای همین نوع سند است و تعریف مستقلی ایجاد نمی‌کند.</p>{item.aliases.length?<div className="space-y-2">{item.aliases.map((x,i)=><div key={x.public_id||i} className="flex items-center justify-between rounded-lg border p-3"><span dir={x.locale?.startsWith("en")?"ltr":"auto"}>{x.display_value}</span><span className="flex gap-2"><Badge variant="secondary">{aliasKinds[x.alias_kind]||x.alias_kind}</Badge><Badge variant={x.is_active?"default":"outline"}>{x.is_active?"فعال":"غیرفعال"}</Badge></span></div>)}</div>:<Empty>نام جایگزینی ثبت نشده است.</Empty>}</Section>
  <Section title="۵. منابع و مستندات مرجع"><p className="text-sm text-slate-600">اعتماد به تعریف از مسیر مرجع صادرکننده ← مدرک ← بررسی ← چرخه حیات شکل می‌گیرد.</p>{item.provenance.length?<div className="space-y-3">{item.provenance.map((x,i)=><article key={x.public_id||i} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong>{x.source_authority_name}</strong><div dir="ltr" className="text-xs text-slate-500">{x.source_authority_code}</div></div><StatusBadge value={x.review_status} kind="review"/></div><p className="mt-2">{x.source_title}</p><p className="text-sm text-slate-500">نسخه/تاریخ: {x.source_version||"—"} / {x.source_date||"—"} · قلمرو: {x.jurisdiction_key||"—"}</p>{safeUrl(x.source_reference)&&<a className="mt-2 inline-flex items-center text-sm text-blue-700" href={safeUrl(x.source_reference)!} target="_blank" rel="noopener noreferrer">مشاهده مدرک مرجع<ExternalLink className="mr-1 h-3 w-3"/></a>}{x.notes&&<p className="mt-2 text-sm">{x.notes}</p>}</article>)}</div>:<Empty>منبع یا مستند مرجعی ثبت نشده است.</Empty>}</Section>
  <Section title="۶. وضعیت بررسی منبع"><div className="flex items-center gap-2"><StatusBadge value={item.source_review_status} kind="review"/><span dir="ltr" className="text-xs text-slate-500">{item.source_review_status}</span></div><p className="text-sm text-slate-600">این وضعیت کیفیت و کفایت شواهد منبع را نشان می‌دهد و مستقل از چرخه حیات کاتالوگ است.</p></Section><LifecycleActions item={item} onSaved={x=>onRefresh(x)}/>
  <Section title="۸. اطلاعات حاکمیتی"><p className="text-sm">شناسه عمومی: <span dir="ltr">{item.public_id}</span></p><p className="text-sm">بازنگری: <span dir="ltr">{item.revision}</span></p><p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">فعال بودن یک نوع سند در کاتالوگ، آن سند را به‌صورت خودکار برای سازمان، پروژه یا محموله الزامی نمی‌کند.</p></Section></div></div> }

export default function DocumentDefinitionsTab() {
 const [items,setItems]=useState<DocumentCatalogDefinition[]>([]),[selected,setSelected]=useState<DocumentCatalogDefinition|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""); const [q,setQ]=useState(""),[debounced,setDebounced]=useState(""),[family,setFamily]=useState(""),[life,setLife]=useState(""),[review,setReview]=useState(""),[mode,setMode]=useState("");
 useEffect(()=>{const t=setTimeout(()=>setDebounced(q.trim()),300);return()=>clearTimeout(t)},[q]); const filters=useMemo<DocumentCatalogFilters>(()=>({q:debounced||undefined,family_code:family||undefined,catalog_lifecycle_status:life||undefined,source_review_status:review||undefined,mode:mode||undefined}),[debounced,family,life,review,mode]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setItems((await fetchDocumentCatalog(filters)).items)}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت کاتالوگ")}finally{setLoading(false)}},[filters]); useEffect(()=>{void load()},[load]);
 const refreshDetail=async(value?:DocumentCatalogDefinition)=>{if(value){setSelected(value);return}if(selected)try{setSelected(await fetchDocumentCatalogDefinition(selected.public_id))}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 if(selected)return <Detail item={selected} onBack={()=>{setSelected(null);void load()}} onRefresh={refreshDetail}/>;
 const filtered=Boolean(debounced||family||life||review||mode);
 return <div className="space-y-5"><Card className="overflow-hidden border-slate-200"><CardContent className="p-0"><div className="bg-slate-950 p-6 text-white"><div className="flex items-center gap-3"><BookOpen className="h-7 w-7 text-blue-300"/><h2 className="text-2xl font-bold">مدیریت کاتالوگ اسناد</h2></div><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-200">کاتالوگ اسناد، فهرست مرجع و کنترل‌شده انواع اسناد قابل استفاده در سامانه است. وجود یک نوع سند در این فهرست به معنی الزامی بودن آن برای همه سازمان‌ها، پروژه‌ها یا محموله‌ها نیست.</p><p className="mt-1 text-sm text-slate-300">الزام هر سند در سطح سازمان، پروژه یا عملیات از طریق سیاست‌ها و الزامات مربوط به همان سطح تعیین می‌شود.</p></div><div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-5"><label className="relative xl:col-span-2"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400"/><Input aria-label="جستجوی کاتالوگ" className="pr-9" placeholder="نام فارسی، English name، کد یا نام جایگزین" value={q} onChange={e=>setQ(e.target.value)}/></label>
 {[{label:"خانواده",value:family,set:setFamily,options:families},{label:"چرخه حیات",value:life,set:setLife,options:lifecycle},{label:"بررسی منبع",value:review,set:setReview,options:reviews}].map(x=><select aria-label={x.label} key={x.label} className="h-10 rounded-md border bg-white px-3" value={x.value} onChange={e=>x.set(e.target.value)}><option value="">همه — {x.label}</option>{Object.entries(x.options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>)}</div><div className="flex flex-wrap items-center gap-3 border-t px-5 py-3"><span className="text-sm text-slate-600">شیوه حمل:</span><select aria-label="شیوه حمل" className="h-9 rounded-md border bg-white px-3" value={mode} onChange={e=>setMode(e.target.value)}><option value="">همه</option>{Object.entries(modes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{filtered&&<Button variant="ghost" size="sm" onClick={()=>{setQ("");setFamily("");setLife("");setReview("");setMode("")}}>پاک‌کردن فیلترها</Button>}<Button className="mr-auto" variant="outline" size="sm" onClick={load}><RefreshCw className="ml-2 h-4 w-4"/>تازه‌سازی</Button></div></CardContent></Card>
 {error&&<div role="alert" className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><AlertTriangle/><div><strong>دریافت اطلاعات انجام نشد.</strong><p className="text-sm">{error}</p></div><Button className="mr-auto" variant="outline" onClick={load}>تلاش دوباره</Button></div>}
 {loading?<Card><CardContent className="flex min-h-48 items-center justify-center gap-3"><Loader2 className="animate-spin"/>در حال دریافت کاتالوگ...</CardContent></Card>:items.length===0?<Empty>{filtered?"موردی مطابق جستجو یا فیلتر پیدا نشد.":"هنوز نوع سندی در کاتالوگ ثبت نشده است."}</Empty>:<Card><CardHeader><CardTitle className="flex items-center justify-between text-base"><span>تعریف‌های مرجع</span><Badge variant="secondary">{items.length} مورد (حداکثر ۲۰۰)</Badge></CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-right text-slate-500"><th className="p-3">نام فارسی / English Name</th><th className="p-3">کد سیستمی</th><th className="p-3">خانواده</th><th className="p-3">چرخه حیات</th><th className="p-3">بررسی منبع</th><th className="p-3"></th></tr></thead><tbody>{items.map(x=><tr key={x.public_id} className="border-b hover:bg-slate-50"><td className="p-3"><strong>{x.name_fa||x.title}</strong><div dir="ltr" className="mt-1 text-left text-xs text-slate-500">{x.name_en||"—"}</div></td><td className="p-3"><code dir="ltr">{x.code}</code></td><td className="p-3">{families[x.family_code||""]||"—"}</td><td className="p-3"><StatusBadge value={x.catalog_lifecycle_status} kind="life"/></td><td className="p-3"><StatusBadge value={x.source_review_status} kind="review"/></td><td className="p-3"><Button variant="ghost" onClick={()=>setSelected(x)}>مشاهده جزئیات<ChevronLeft className="mr-2 h-4 w-4"/></Button></td></tr>)}</tbody></table></CardContent></Card>}
 <div className="grid gap-3 md:grid-cols-3"><div className="flex gap-3 rounded-xl border bg-white p-4"><ShieldCheck className="text-blue-600"/><p className="text-sm"><strong>واژگان پلتفرم</strong><br/>سازمان‌ها مالک یا ویرایشگر هویت مرجع نیستند.</p></div><div className="flex gap-3 rounded-xl border bg-white p-4"><FileText className="text-blue-600"/><p className="text-sm"><strong>نوع سند ≠ فایل</strong><br/>فایل بارگذاری‌شده نمونه‌ای عملیاتی از یک نوع سند است.</p></div><div className="flex gap-3 rounded-xl border bg-white p-4"><Tags className="text-blue-600"/><p className="text-sm"><strong>نوع سند ≠ شماره مرجع</strong><br/>شماره بارنامه یا اظهارنامه، هویت کاتالوگ نیست.</p></div></div></div>
}
