import {useCallback,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {createLogisticsPoint,createLogisticsPointType,listLogisticsPoints,listLogisticsPointTypes,setLogisticsPointActive,setLogisticsPointTypeActive,updateLogisticsPoint,updateLogisticsPointType,type LogisticsPointTypeView,type LogisticsPointView} from "@/lib/api";

const typeBlank={immutable_code:"",fa_name:"",en_name:"",definition:"",display_order:"0"};
const pointBlank={immutable_code:"",fa_name:"",en_name:"",point_type_public_id:"",country_code:"IR",province_code:"",city_code:"",short_address:""};

export default function LogisticsNetworkAdminTab(){
 const [types,setTypes]=useState<LogisticsPointTypeView[]>([]),[points,setPoints]=useState<LogisticsPointView[]>([]);
 const [tf,setTf]=useState(typeBlank),[pf,setPf]=useState(pointBlank),[q,setQ]=useState(""),[error,setError]=useState(""),[warning,setWarning]=useState(false);
 const load=useCallback(async()=>{try{setError("");const [t,p]=await Promise.all([listLogisticsPointTypes(true),listLogisticsPoints({q,active:"all"},true)]);setTypes(t.items);setPoints(p.items)}catch(e){setError(e instanceof Error?e.message:"Unable to load logistics network")}},[q]);
 useEffect(()=>{void load()},[load]);
 const addType=async()=>{try{await createLogisticsPointType({...tf,display_order:Number(tf.display_order)});setTf(typeBlank);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create type")}};
 const addPoint=async(confirm=false)=>{try{await createLogisticsPoint({...pf,province_code:pf.province_code||null,city_code:pf.city_code||null,confirm_probable_duplicate:confirm});setPf(pointBlank);setWarning(false);await load()}catch(e){const message=e instanceof Error?e.message:"Unable to create point";setError(message);setWarning(message.toLowerCase().includes("probable"))}};
 const editType=async(x:LogisticsPointTypeView)=>{const fa_name=window.prompt("Persian name",x.fa_name);if(fa_name===null)return;const en_name=window.prompt("English name",x.en_name);if(en_name===null)return;await updateLogisticsPointType(x.public_id,{version:x.version,fa_name,en_name});await load()};
 const editPoint=async(x:LogisticsPointView)=>{const fa_name=window.prompt("Persian name",x.fa_name);if(fa_name===null)return;const en_name=window.prompt("English name",x.en_name||"");if(en_name===null)return;const short_address=window.prompt("Short address",x.short_address||"");if(short_address===null)return;await updateLogisticsPoint(x.public_id,{version:x.version,fa_name,en_name,short_address});await load()};
 return <div className="space-y-4" dir="auto">
  {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
  <Tabs defaultValue="points"><TabsList><TabsTrigger value="points">Logistics points</TabsTrigger><TabsTrigger value="types">Point types</TabsTrigger></TabsList>
   <TabsContent value="types" className="space-y-4"><Card><CardHeader><CardTitle>Create point type</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
    <Input placeholder="Immutable code" value={tf.immutable_code} onChange={e=>setTf({...tf,immutable_code:e.target.value})}/><Input placeholder="Persian name" value={tf.fa_name} onChange={e=>setTf({...tf,fa_name:e.target.value})}/><Input placeholder="English name" value={tf.en_name} onChange={e=>setTf({...tf,en_name:e.target.value})}/><Input placeholder="Definition" value={tf.definition} onChange={e=>setTf({...tf,definition:e.target.value})}/><Button onClick={addType}>Save</Button>
   </CardContent></Card><div className="grid gap-2">{types.map(x=><Card key={x.public_id}><CardContent className="flex flex-wrap items-center gap-3 p-3"><code>{x.immutable_code}</code><b>{x.fa_name}</b><span>{x.en_name}</span><span className="ms-auto">{x.is_active?"Active":"Inactive"}</span><Button variant="outline" onClick={()=>void editType(x)}>Edit</Button><Button variant="outline" onClick={async()=>{await setLogisticsPointTypeActive(x,!x.is_active);await load()}}>{x.is_active?"Deactivate":"Activate"}</Button></CardContent></Card>)}</div></TabsContent>
   <TabsContent value="points" className="space-y-4"><Card><CardHeader><CardTitle>Create logistics point</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
    <Input placeholder="Immutable code" value={pf.immutable_code} onChange={e=>setPf({...pf,immutable_code:e.target.value})}/><Input placeholder="Persian name" value={pf.fa_name} onChange={e=>setPf({...pf,fa_name:e.target.value})}/><Input placeholder="English name" value={pf.en_name} onChange={e=>setPf({...pf,en_name:e.target.value})}/><select className="h-10 rounded border bg-background px-2" value={pf.point_type_public_id} onChange={e=>setPf({...pf,point_type_public_id:e.target.value})}><option value="">Point type</option>{types.filter(x=>x.is_active).map(x=><option key={x.public_id} value={x.public_id}>{x.fa_name} / {x.en_name}</option>)}</select><Input placeholder="Country code" value={pf.country_code} onChange={e=>setPf({...pf,country_code:e.target.value})}/><Input placeholder="Province code (optional)" value={pf.province_code} onChange={e=>setPf({...pf,province_code:e.target.value})}/><Input placeholder="City code (optional)" value={pf.city_code} onChange={e=>setPf({...pf,city_code:e.target.value})}/><Input placeholder="Short address" value={pf.short_address} onChange={e=>setPf({...pf,short_address:e.target.value})}/><Button onClick={()=>void addPoint(false)}>Save</Button>{warning&&<Button variant="destructive" onClick={()=>void addPoint(true)}>Confirm distinct point</Button>}
   </CardContent></Card><Input aria-label="Search logistics points" placeholder="Search by code or name" value={q} onChange={e=>setQ(e.target.value)}/><div className="grid gap-2">{points.map(x=><Card key={x.public_id}><CardContent className="flex flex-wrap items-center gap-3 p-3"><code>{x.immutable_code}</code><b>{x.fa_name}</b><span>{x.en_name}</span><span>{x.point_type.fa_name}</span><span>{x.country.fa_name}</span><span className="ms-auto">{x.is_active?"Active":"Inactive"}</span><Button variant="outline" onClick={()=>void editPoint(x)}>Edit</Button><Button variant="outline" onClick={async()=>{await setLogisticsPointActive(x,!x.is_active);await load()}}>{x.is_active?"Deactivate":"Activate"}</Button></CardContent></Card>)}</div></TabsContent>
  </Tabs>
 </div>
}
