import {useCallback,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {ApiError,createLogisticsPointType,listLogisticsPoints,listLogisticsPointTypes,reviewLogisticsPoint,setLogisticsPointActive,setLogisticsPointTypeActive,updateLogisticsPoint,updateLogisticsPointType,type LogisticsPointTypeView,type LogisticsPointView} from "@/lib/api";
import OrganizationGlobalNetworkTab from "@/components/OrganizationGlobalNetworkTab";

const typeBlank={immutable_code:"",fa_name:"",en_name:"",definition:"",display_order:"0"};

export default function LogisticsNetworkAdminTab({isPlatformAdmin=false}:{isPlatformAdmin?:boolean}){
 const [types,setTypes]=useState<LogisticsPointTypeView[]>([]),[points,setPoints]=useState<LogisticsPointView[]>([]);
 const [tf,setTf]=useState(typeBlank),[q,setQ]=useState(""),[error,setError]=useState("");
 const [editingType,setEditingType]=useState<{item:LogisticsPointTypeView;fa_name:string;en_name:string}|null>(null);
 const [editingPoint,setEditingPoint]=useState<{item:LogisticsPointView;fa_name:string;en_name:string;short_address:string}|null>(null);
 const [duplicateReview,setDuplicateReview]=useState<{item:LogisticsPointView;duplicateOf:string}|null>(null);
 const safeError=(caught:unknown,fallback:string)=>caught instanceof ApiError&&caught.status===403?"شما اجازهٔ مدیریت شبکهٔ لجستیکی این سازمان را ندارید.":fallback;
 const load=useCallback(async()=>{try{setError("");const t=await listLogisticsPointTypes(true);setTypes(t.items);if(!isPlatformAdmin){const p=await listLogisticsPoints({q,active:"all"},true);setPoints(p.items)}}catch(e){setError(safeError(e,"دریافت شبکهٔ لجستیکی انجام نشد."))}},[isPlatformAdmin,q]);
 useEffect(()=>{void load()},[load]);
 const addType=async()=>{try{await createLogisticsPointType({...tf,display_order:Number(tf.display_order)});setTf(typeBlank);await load()}catch(e){setError(safeError(e,"ایجاد نوع مکان انجام نشد."))}};
 const saveTypeEdit=async()=>{if(!editingType)return;try{await updateLogisticsPointType(editingType.item.public_id,{version:editingType.item.version,fa_name:editingType.fa_name,en_name:editingType.en_name});setEditingType(null);await load()}catch(e){setError(safeError(e,"ویرایش نوع مکان انجام نشد."))}};
 const savePointEdit=async()=>{if(!editingPoint)return;try{await updateLogisticsPoint(editingPoint.item.public_id,{version:editingPoint.item.version,fa_name:editingPoint.fa_name,en_name:editingPoint.en_name,short_address:editingPoint.short_address});setEditingPoint(null);await load()}catch(e){setError(safeError(e,"ویرایش مکان لجستیکی انجام نشد."))}};
 return <div className="space-y-4" dir="rtl">
  <div><h2 className="text-lg font-semibold">{isPlatformAdmin?"انواع مکان لجستیکی سیستم":"شبکه لجستیکی سازمان"}</h2><p className="text-sm text-muted-foreground">{isPlatformAdmin?"نوع‌های استاندارد مکان را برای استفادهٔ شبکهٔ سراسری و سازمانی مدیریت کنید.":"مکان‌هایی مانند انبار، پایانه، بندر، گمرک، کارخانه و سایت مشتری را از فهرست استاندارد به شبکهٔ سازمان اضافه کنید یا یک مکان خصوصی بسازید. این مکان‌ها بعداً در پیکربندی پروژه و ثبت موقعیت محموله دوباره انتخاب می‌شوند؛ افزودن مکان به‌تنهایی مسیر یا نقطهٔ کنترل نمی‌سازد."}</p></div>
  {!isPlatformAdmin&&<OrganizationGlobalNetworkTab/>}
  {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
  <Tabs defaultValue={isPlatformAdmin?"types":"points"}><TabsList>{!isPlatformAdmin&&<TabsTrigger value="points">مکان‌های لجستیکی سازمان</TabsTrigger>}{isPlatformAdmin&&<TabsTrigger value="types">انواع مکان سیستم</TabsTrigger>}</TabsList>
   {isPlatformAdmin&&<TabsContent value="types" className="space-y-4"><Card><CardHeader><CardTitle>افزودن نوع مکان</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
    <Input aria-label="کد ثابت نوع مکان" dir="ltr" placeholder="کد ثابت" value={tf.immutable_code} onChange={e=>setTf({...tf,immutable_code:e.target.value})}/><Input aria-label="نام فارسی نوع مکان" placeholder="نام فارسی" value={tf.fa_name} onChange={e=>setTf({...tf,fa_name:e.target.value})}/><Input aria-label="نام انگلیسی نوع مکان" dir="ltr" placeholder="نام انگلیسی" value={tf.en_name} onChange={e=>setTf({...tf,en_name:e.target.value})}/><Input aria-label="توضیح نوع مکان" placeholder="توضیح" value={tf.definition} onChange={e=>setTf({...tf,definition:e.target.value})}/><Button onClick={addType}>ذخیره</Button>
   </CardContent></Card><div className="grid gap-2">{types.map(x=><Card key={x.public_id}><CardContent className="flex flex-wrap items-center gap-3 p-3"><b>{x.fa_name}</b><span dir="ltr" className="text-sm text-slate-500">{x.en_name}</span><span className="ms-auto">{x.is_active?"فعال":"غیرفعال"}</span><details className="text-xs text-slate-500"><summary>جزئیات فنی</summary><code>{x.immutable_code}</code></details><Button variant="outline" onClick={()=>setEditingType({item:x,fa_name:x.fa_name,en_name:x.en_name})}>ویرایش</Button><Button variant="outline" onClick={async()=>{await setLogisticsPointTypeActive(x,!x.is_active);await load()}}>{x.is_active?"غیرفعال کردن":"فعال کردن"}</Button></CardContent></Card>)}</div></TabsContent>}
   {!isPlatformAdmin&&<TabsContent value="points" className="space-y-4"><Card><CardHeader><CardTitle>بررسی مکان‌های سازمان</CardTitle><p className="text-sm text-muted-foreground">کارشناس می‌تواند مکان متصل به شهر معتبر را هنگام عملیات بسازد و بی‌درنگ استفاده کند. تأیید مدیر کیفیت کاتالوگ را اداره می‌کند و سابقهٔ عملیات را بازنویسی نمی‌کند.</p></CardHeader></Card><Input aria-label="جست‌وجوی مکان‌های لجستیکی" placeholder="جست‌وجو با کد یا نام" value={q} onChange={e=>setQ(e.target.value)}/><div className="grid gap-2">{points.length===0&&<p className="rounded border border-dashed p-4 text-muted-foreground">هنوز مکان سازمانی تعریف نشده است.</p>}{points.map(x=><Card id={`logistics-point-${x.public_id}`} key={x.public_id}><CardContent className="flex flex-wrap items-center gap-3 p-3"><b>{x.fa_name}</b><span dir="ltr">{x.en_name}</span><span>{x.point_type?.fa_name||"نوع تعریف نشده"}</span><span>{x.country.fa_name} · {x.province?.name_fa} · {x.city?.name_fa}</span><span className="rounded bg-amber-50 px-2 text-xs">{x.governance_state==="PENDING_REVIEW"?"در انتظار بررسی":x.governance_state==="APPROVED"?"تأییدشده":x.governance_state==="POTENTIAL_DUPLICATE"?"تکراری احتمالی":"غیرفعال"}</span>{x.global_source&&<span className="rounded bg-blue-50 px-2 text-xs text-blue-800">برگرفته از تعریف استاندارد سیستم · {x.global_source.fa_name}{x.global_source.platform_lifecycle_status==="DEPRECATED"?" · منسوخ‌شده در سیستم":""}</span>}<details className="text-xs text-slate-500"><summary>جزئیات فنی</summary><code dir="ltr">{x.immutable_code}</code></details><span className="ms-auto">{x.is_active?"قابل انتخاب":"غیرفعال"}</span><Button variant="outline" onClick={()=>setEditingPoint({item:x,fa_name:x.fa_name,en_name:x.en_name||"",short_address:x.short_address||""})}>غنی‌سازی</Button>{x.governance_state!=="APPROVED"&&x.is_active&&<Button onClick={async()=>{await reviewLogisticsPoint(x,"approve");await load()}}>تأیید</Button>}{x.is_active&&<Button variant="outline" onClick={()=>setDuplicateReview({item:x,duplicateOf:""})}>علامت‌گذاری تکراری احتمالی</Button>}{x.is_active&&<Button variant="outline" onClick={async()=>{await reviewLogisticsPoint(x,"deactivate");await load()}}>غیرفعال‌سازی برای آینده</Button>}{!x.is_active&&<Button variant="outline" onClick={async()=>{await setLogisticsPointActive(x,true);await load()}}>فعال‌سازی</Button>}</CardContent></Card>)}</div></TabsContent>}
  </Tabs>
  <Dialog open={editingType!==null} onOpenChange={open=>{if(!open)setEditingType(null)}}><DialogContent><DialogHeader><DialogTitle>ویرایش نوع مکان</DialogTitle></DialogHeader>{editingType&&<div className="grid gap-3"><Label htmlFor="edit-type-code">کد ثابت</Label><Input id="edit-type-code" value={editingType.item.immutable_code} disabled/><Label htmlFor="edit-type-fa">نام فارسی</Label><Input id="edit-type-fa" value={editingType.fa_name} onChange={e=>setEditingType({...editingType,fa_name:e.target.value})}/><Label htmlFor="edit-type-en">نام انگلیسی</Label><Input id="edit-type-en" value={editingType.en_name} onChange={e=>setEditingType({...editingType,en_name:e.target.value})}/></div>}<DialogFooter><Button variant="outline" onClick={()=>setEditingType(null)}>انصراف</Button><Button onClick={()=>void saveTypeEdit()}>ذخیره تغییرات</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={editingPoint!==null} onOpenChange={open=>{if(!open)setEditingPoint(null)}}><DialogContent><DialogHeader><DialogTitle>ویرایش مکان لجستیکی</DialogTitle></DialogHeader>{editingPoint&&<div className="grid gap-3"><Label htmlFor="edit-point-code">کد ثابت</Label><Input id="edit-point-code" value={editingPoint.item.immutable_code} disabled/><Label htmlFor="edit-point-fa">نام فارسی</Label><Input id="edit-point-fa" value={editingPoint.fa_name} onChange={e=>setEditingPoint({...editingPoint,fa_name:e.target.value})}/><Label htmlFor="edit-point-en">نام انگلیسی</Label><Input id="edit-point-en" value={editingPoint.en_name} onChange={e=>setEditingPoint({...editingPoint,en_name:e.target.value})}/><Label htmlFor="edit-point-address">نشانی کوتاه</Label><Input id="edit-point-address" value={editingPoint.short_address} onChange={e=>setEditingPoint({...editingPoint,short_address:e.target.value})}/></div>}<DialogFooter><Button variant="outline" onClick={()=>setEditingPoint(null)}>انصراف</Button><Button onClick={()=>void savePointEdit()}>ذخیره تغییرات</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={duplicateReview!==null} onOpenChange={open=>{if(!open)setDuplicateReview(null)}}><DialogContent><DialogHeader><DialogTitle>تکراری احتمالی</DialogTitle></DialogHeader>{duplicateReview&&<div className="grid gap-3"><p className="text-sm text-slate-600">این کار فقط رابطهٔ بررسی را ثبت می‌کند؛ رکوردها ادغام و سوابق تاریخی بازنویسی نمی‌شوند.</p><Label htmlFor="duplicate-of">مکان مرجع احتمالی</Label><select id="duplicate-of" className="rounded border p-2" value={duplicateReview.duplicateOf} onChange={e=>setDuplicateReview({...duplicateReview,duplicateOf:e.target.value})}><option value="">انتخاب مکان</option>{points.filter(item=>item.public_id!==duplicateReview.item.public_id).map(item=><option key={item.public_id} value={item.public_id}>{item.fa_name} · {item.city?.name_fa||item.country.fa_name}</option>)}</select></div>}<DialogFooter><Button variant="outline" onClick={()=>setDuplicateReview(null)}>انصراف</Button><Button disabled={!duplicateReview?.duplicateOf} onClick={async()=>{if(!duplicateReview)return;await reviewLogisticsPoint(duplicateReview.item,"flag-duplicate",{duplicate_of_public_id:duplicateReview.duplicateOf});setDuplicateReview(null);await load()}}>ثبت به‌عنوان تکراری احتمالی</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
