import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { createMasterData, fetchMasterData, setMasterDataActive, updateMasterData, type MasterDataItem, type MasterDataResource } from "@/lib/api";

const resources: { id: MasterDataResource; label: string }[] = [
  { id: "cargo-types", label: "انواع کالا" }, { id: "service-types", label: "انواع خدمت" }, { id: "units-of-measure", label: "واحدهای اندازه‌گیری" },
];
const dimensions = ["COUNT", "WEIGHT", "VOLUME", "LENGTH", "OTHER_GOVERNED"];
type Form = Record<string, string>;
const blank = (): Form => ({ immutable_code: "", fa_name: "", en_name: "", description: "", display_order: "0", parent_id: "none", symbol: "", measurement_dimension: "COUNT" });

function ResourceTable({ resource }: { resource: MasterDataResource }) {
  const { toast } = useToast();
  const [items, setItems] = useState<MasterDataItem[]>([]);
  const [q, setQ] = useState(""); const [active, setActive] = useState("all"); const [dimension, setDimension] = useState("all"); const [sort, setSort] = useState("display_order"); const [direction, setDirection] = useState("asc"); const [page, setPage] = useState(1); const [pages, setPages] = useState(1);
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<MasterDataItem | null>(null); const [form, setForm] = useState<Form>(blank());
  const load = useCallback(async () => { try { const result = await fetchMasterData(resource, { q, active, measurement_dimension: resource === "units-of-measure" && dimension !== "all" ? dimension : undefined, page, per_page: 10, sort, direction }); setItems(result.items); setPages(Math.max(result.pages, 1)); } catch (e) { toast({ title: "خطا", description: e instanceof Error ? e.message : "بارگذاری ناموفق بود", variant: "destructive" }); } }, [active, dimension, direction, page, q, resource, sort, toast]);
  useEffect(() => { void load(); }, [load]);
  const showForm = (item?: MasterDataItem) => { setEditing(item ?? null); setForm(item ? { immutable_code: item.immutable_code, fa_name: item.fa_name, en_name: item.en_name, description: item.description ?? "", display_order: String(item.display_order), parent_id: item.parent_id ?? "none", symbol: item.symbol ?? "", measurement_dimension: item.measurement_dimension ?? "COUNT" } : blank()); setOpen(true); };
  const save = async () => { const payload: Record<string, unknown> = { ...form, display_order: Number(form.display_order), description: form.description || null }; if (resource === "cargo-types") payload.parent_id = form.parent_id === "none" ? null : form.parent_id; else delete payload.parent_id; if (resource !== "units-of-measure") { delete payload.symbol; delete payload.measurement_dimension; } try { if (editing) await updateMasterData(resource, editing.public_id, { ...payload, version: editing.version }); else await createMasterData(resource, payload); setOpen(false); await load(); } catch (e) { toast({ title: "ذخیره ناموفق", description: e instanceof Error ? e.message : "خطای اعتبارسنجی", variant: "destructive" }); } };
  return <div className="space-y-4">
    <div className="max-w-full overflow-x-auto">
    <div className="flex flex-wrap gap-2"><Input aria-label="جستجو" className="max-w-sm" value={q} onChange={e => { setQ(e.target.value); setPage(1); }} placeholder="جستجو در کد یا نام"/><Select value={active} onValueChange={v => { setActive(v); setPage(1); }}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">همه وضعیت‌ها</SelectItem><SelectItem value="true">فعال</SelectItem><SelectItem value="false">غیرفعال</SelectItem></SelectContent></Select>{resource === "units-of-measure" && <Select value={dimension} onValueChange={v => { setDimension(v); setPage(1); }}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">همه ابعاد</SelectItem>{dimensions.map(d => <SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select>}<Select value={sort} onValueChange={v => setSort(v)}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="display_order">ترتیب نمایش</SelectItem><SelectItem value="code">کد</SelectItem><SelectItem value="fa_name">نام فارسی</SelectItem><SelectItem value="en_name">نام انگلیسی</SelectItem><SelectItem value="updated_at">آخرین تغییر</SelectItem></SelectContent></Select><Button variant="outline" onClick={() => setDirection(direction === "asc" ? "desc" : "asc")}>{direction === "asc" ? "صعودی" : "نزولی"}</Button><Button onClick={() => showForm()}>ایجاد</Button></div>
    <div className="rounded-xl border"><Table><TableHeader><TableRow><TableHead>کد</TableHead><TableHead>نام فارسی</TableHead><TableHead>نام انگلیسی</TableHead>{resource === "units-of-measure" && <TableHead>بعد / نماد</TableHead>}<TableHead>وضعیت</TableHead><TableHead>عملیات</TableHead></TableRow></TableHeader><TableBody>{items.map(item => <TableRow key={item.public_id}><TableCell dir="ltr">{item.immutable_code}</TableCell><TableCell>{item.fa_name}</TableCell><TableCell dir="ltr">{item.en_name}</TableCell>{resource === "units-of-measure" && <TableCell>{item.measurement_dimension} / {item.symbol}</TableCell>}<TableCell>{item.is_active ? "فعال" : "غیرفعال"}</TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" onClick={() => showForm(item)}>ویرایش</Button><Button size="sm" variant="outline" onClick={async () => { try { await setMasterDataActive(resource, item, !item.is_active); await load(); } catch (e) { toast({ title: "تغییر وضعیت ناموفق", description: e instanceof Error ? e.message : "خطا", variant: "destructive" }); } }}>{item.is_active ? "غیرفعال‌سازی" : "فعال‌سازی"}</Button></TableCell></TableRow>)}</TableBody></Table></div>
    </div>
    <div className="flex items-center justify-end gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => setPage(page - 1)}>قبلی</Button><span className="text-sm">{page} از {pages}</span><Button variant="outline" disabled={page >= pages} onClick={() => setPage(page + 1)}>بعدی</Button></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "ویرایش داده مرجع" : "ایجاد داده مرجع"}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Input disabled={Boolean(editing)} value={form.immutable_code} onChange={e => setForm({...form, immutable_code: e.target.value})} placeholder="کد ثابت"/><Input value={form.display_order} type="number" onChange={e => setForm({...form, display_order: e.target.value})} placeholder="ترتیب"/><Input value={form.fa_name} onChange={e => setForm({...form, fa_name: e.target.value})} placeholder="نام فارسی"/><Input value={form.en_name} onChange={e => setForm({...form, en_name: e.target.value})} placeholder="نام انگلیسی"/><Input className="sm:col-span-2" value={form.description} onChange={e => setForm({...form, description: e.target.value})} placeholder="توضیحات"/>{resource === "cargo-types" && <Select value={form.parent_id} onValueChange={v => setForm({...form, parent_id: v})}><SelectTrigger><SelectValue placeholder="والد"/></SelectTrigger><SelectContent><SelectItem value="none">بدون والد</SelectItem>{items.filter(i => i.is_active && i.public_id !== editing?.public_id).map(i => <SelectItem key={i.public_id} value={i.public_id}>{i.fa_name}</SelectItem>)}</SelectContent></Select>}{resource === "units-of-measure" && <><Input value={form.symbol} onChange={e => setForm({...form, symbol: e.target.value})} placeholder="نماد"/><Select value={form.measurement_dimension} onValueChange={v => setForm({...form, measurement_dimension: v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{dimensions.map(d => <SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select></>}</div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>انصراف</Button><Button disabled={!form.immutable_code.trim() || !form.fa_name.trim() || !form.en_name.trim()} onClick={save}>ذخیره</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

export default function MasterDataAdminTab() { return <Tabs defaultValue="cargo-types"><TabsList>{resources.map(r => <TabsTrigger key={r.id} value={r.id}>{r.label}</TabsTrigger>)}</TabsList>{resources.map(r => <TabsContent key={r.id} value={r.id}><ResourceTable resource={r.id}/></TabsContent>)}</Tabs>; }
