import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ApiError, createExecutionCondition, getExecutionPreview, getExecutionProgress, initializeExecution, listExecutionConditions, listExecutionEvents, listExecutionMilestones, listExecutionReasons, reopenExecutionMilestone, resolveExecutionCondition, transitionExecutionMilestone, verifyExecutionEvent, type ExecutionCondition, type ExecutionEvent, type ExecutionMilestone, type ExecutionProgress, type ExecutionReason } from "@/lib/api";

const transitions:Record<string,string[]>={PENDING:["READY","BLOCKED","SKIPPED","CANCELLED"],READY:["IN_PROGRESS","SKIPPED","CANCELLED","BLOCKED"],IN_PROGRESS:["COMPLETED","BLOCKED","CANCELLED"],BLOCKED:["READY","CANCELLED"]};
const message=(e:unknown)=>e instanceof ApiError?(e.code==="TRANSITION_READINESS_BLOCKED"?e.message:e.code.startsWith("STALE_")?"The record changed. Refresh and try again.":e.message):e instanceof Error?e.message:"The operation could not be completed.";

export default function OperationalExecutionSection({shipmentPublicId,shipmentVersion,readOnly=false}:{shipmentPublicId:string;shipmentVersion:number;readOnly?:boolean}){
  const [preview,setPreview]=useState<Awaited<ReturnType<typeof getExecutionPreview>>["data"]>(); const [milestones,setMilestones]=useState<ExecutionMilestone[]>([]); const [progress,setProgress]=useState<ExecutionProgress>(); const [events,setEvents]=useState<ExecutionEvent[]>([]); const [delays,setDelays]=useState<ExecutionCondition[]>([]); const [exceptions,setExceptions]=useState<ExecutionCondition[]>([]); const [delayReasons,setDelayReasons]=useState<ExecutionReason[]>([]); const [exceptionReasons,setExceptionReasons]=useState<ExecutionReason[]>([]); const [reason,setReason]=useState(""); const [note,setNote]=useState(""); const [delayReason,setDelayReason]=useState(""); const [exceptionReason,setExceptionReason]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setError("");const results=await Promise.allSettled([getExecutionPreview(shipmentPublicId),listExecutionMilestones(shipmentPublicId),getExecutionProgress(shipmentPublicId),listExecutionEvents(shipmentPublicId),listExecutionConditions(shipmentPublicId,"delay"),listExecutionConditions(shipmentPublicId,"exception"),listExecutionReasons("delay"),listExecutionReasons("exception")]);const [p,m,g,e,d,x,dr,xr]=results;if(p.status==="fulfilled")setPreview(p.value.data);if(m.status==="fulfilled")setMilestones(m.value.data);if(g.status==="fulfilled")setProgress(g.value.data);if(e.status==="fulfilled")setEvents(e.value.data);if(d.status==="fulfilled")setDelays(d.value.data);if(x.status==="fulfilled")setExceptions(x.value.data);if(dr.status==="fulfilled")setDelayReasons(dr.value.data.filter(v=>v.is_active));if(xr.status==="fulfilled")setExceptionReasons(xr.value.data.filter(v=>v.is_active));const failed=results.find((result):result is PromiseRejectedResult=>result.status==="rejected");if(failed)setError(message(failed.reason))},[shipmentPublicId]);
  useEffect(()=>{void load()},[load]);
  const run=async(action:()=>Promise<unknown>)=>{try{setBusy(true);setError("");await action();await load()}catch(e){setError(message(e))}finally{setBusy(false)}};
  const change=(m:ExecutionMilestone,target:string)=>{if(["COMPLETED","SKIPPED","CANCELLED"].includes(target)&&!window.confirm(`Confirm ${target.toLowerCase()}?`))return;if(["BLOCKED","SKIPPED","CANCELLED"].includes(target)&&!reason.trim()){setError("An explicit reason is required.");return}void run(()=>transitionExecutionMilestone(shipmentPublicId,m,target,reason.trim()||undefined))};
  const conditionPanel=(kind:"delay"|"exception",rows:ExecutionCondition[],reasons:ExecutionReason[],selected:string,setSelected:(v:string)=>void)=><section className="space-y-3" aria-label={`${kind} records`}><h3 className="font-semibold capitalize">{kind}s</h3>{!rows.length&&<p>No {kind} records.</p>}{rows.map(row=><article className="rounded border p-3" key={row.public_id}><strong>{row.reason.fa_name} / {row.reason.en_name}</strong><p>{row.active?"Active":"Resolved"} · {Math.ceil(row.duration_seconds/60)} min</p>{row.note&&<p>{row.note}</p>}{row.active&&!readOnly&&<Button disabled={busy} onClick={()=>void run(()=>resolveExecutionCondition(shipmentPublicId,kind,row))}>Resolve</Button>}</article>)}{!readOnly&&<div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><select className="min-h-11 rounded border px-2" aria-label={`${kind} reason`} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select governed reason</option>{reasons.map(r=><option key={r.public_id} value={r.public_id}>{r.fa_name} / {r.en_name}</option>)}</select><Input aria-label={`${kind} note`} placeholder="Optional note" value={note} onChange={e=>setNote(e.target.value)}/><Button disabled={busy||!selected} onClick={()=>void run(()=>createExecutionCondition(shipmentPublicId,kind,{reason_public_id:selected,note,...(kind==="delay"?{started_at:new Date().toISOString()}:{occurred_at:new Date().toISOString()})}))}>Add</Button></div>}{!reasons.length&&<p role="status">No active governed reasons. Ask an administrator to create one.</p>}</section>;
  return <Card><CardHeader><CardTitle>Operational Execution</CardTitle></CardHeader><CardContent className="space-y-6">{error&&<div role="alert" className="rounded bg-red-50 p-3 text-red-700">{error} <Button variant="link" onClick={()=>void load()}>Refresh</Button></div>}<section aria-label="progress summary"><h3 className="font-semibold">Progress</h3><p>{progress?.initialized?`${progress.completion_percentage}% complete · ${progress.total} milestones · ${progress.active_delay_count} active delays · ${progress.active_exception_count} active exceptions`:"Not initialized"}</p></section>{!preview?.initialized&&<section><h3 className="font-semibold">Initialization preview</h3>{preview?.findings.map(f=><p key={f.code}>{f.message}</p>)}<p>{preview?.milestones.length||0} expected milestones</p>{!readOnly&&<Button disabled={busy||!preview?.confirmation_allowed} onClick={()=>void run(()=>initializeExecution(shipmentPublicId,shipmentVersion))}>Confirm initialization</Button>}</section>}<section className="space-y-3" aria-label="milestones"><h3 className="font-semibold">Milestones</h3>{!milestones.length&&<p>No initialized milestones.</p>}{milestones.map(m=><article key={m.public_id} className="rounded border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{m.sequence}. {m.milestone_type_snapshot?.fa_name||m.milestone_type}</strong><span>{m.status} · v{m.version}</span></div><p>{m.expected_point_snapshot?.label||m.expected_point_snapshot?.role||"No expected point"}</p>{!readOnly&&<div className="mt-2 flex flex-wrap gap-2">{(transitions[m.status]||[]).map(target=><Button size="sm" variant="outline" disabled={busy} key={target} onClick={()=>change(m,target)}>{target}</Button>)}{["COMPLETED","SKIPPED","CANCELLED"].includes(m.status)&&<Button size="sm" variant="outline" disabled={busy||!reason.trim()} onClick={()=>void run(()=>reopenExecutionMilestone(shipmentPublicId,m,reason))}>Reopen</Button>}</div>}</article>)}{!readOnly&&<Input aria-label="transition reason" placeholder="Reason for block, skip, cancel, or reopen" value={reason} onChange={e=>setReason(e.target.value)}/>}</section><div className="grid gap-6 lg:grid-cols-2">{conditionPanel("delay",delays,delayReasons,delayReason,setDelayReason)}{conditionPanel("exception",exceptions,exceptionReasons,exceptionReason,setExceptionReason)}</div><section aria-label="immutable timeline"><h3 className="font-semibold">Immutable timeline</h3>{!events.length&&<p>No execution events.</p>}<ol className="space-y-2">{events.map(e=><li className="rounded border p-2" key={e.public_id}><strong>{e.event_type}</strong> · <time>{new Date(e.effective_at).toLocaleString()}</time>{e.reason&&<p>{e.reason}</p>}{e.verification_state!=="verified"&&!readOnly&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void run(()=>verifyExecutionEvent(shipmentPublicId,e.public_id))}>Verify</Button>}</li>)}</ol></section></CardContent></Card>;
}
