import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {fetchOrganizationDocumentPolicy,updateOrganizationDocumentPolicy,type OrganizationDocumentPolicyItem,type OrganizationDocumentRequirementLevel} from "@/lib/api";

const levels: OrganizationDocumentRequirementLevel[]=["REQUIRED","OPTIONAL","CONDITIONAL","DISABLED"];
const labels: Record<OrganizationDocumentRequirementLevel,string>={REQUIRED:"الزامی",OPTIONAL:"اختیاری",CONDITIONAL:"مشروط",DISABLED:"غیرفعال"};

export default function OrganizationDocumentPolicyTab(){
 const [items,setItems]=useState<OrganizationDocumentPolicyItem[]>([]),[mode,setMode]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const load=async()=>{try{setError("");const result=await fetchOrganizationDocumentPolicy();setItems(Array.isArray(result?.items)?result.items:[]);setMode(result?.mode||"")}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت الزامات مستندات")}};
 useEffect(()=>{void load()},[]);
 const save=async(item:OrganizationDocumentPolicyItem,level:OrganizationDocumentRequirementLevel)=>{try{setBusy(item.document_definition_public_id);setError("");await updateOrganizationDocumentPolicy(item.document_definition_public_id,{requirement_level:level,is_active:level!=="DISABLED",...(typeof item.version==="number"?{version:item.version}:{})});await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ذخیره الزام مستند")}finally{setBusy("")}};
 return <div className="space-y-4"><Card><CardHeader><CardTitle>الزامات مستندات سازمان</CardTitle></CardHeader><CardContent className="space-y-2"><p>در این بخش فقط سطح الزام انواع مستندات سراسری برای سازمان شما تعیین می‌شود. تعریف نوع مستند در اختیار مدیر سامانه است.</p>{mode==="COMPATIBILITY_FALLBACK"&&<p className="rounded border border-amber-300 bg-amber-50 p-3 text-amber-900">تا ثبت اولین سیاست، رفتار سازگار قبلی از پیش‌فرض سراسری استفاده می‌کند. پس از اولین ثبت، فقط سیاست‌های صریح سازمان اعمال می‌شوند.</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}</CardContent></Card><Card><CardContent className="overflow-auto p-4"><table className="w-full text-sm"><thead><tr><th>نوع مستند</th><th>کد</th><th>دامنه</th><th>الزام سازمان</th><th>عملیات</th></tr></thead><tbody>{items.map(item=>{const value=item.requirement_level||"DISABLED";return <tr className="border-t" key={item.document_definition_public_id}><td>{item.title||item.code}</td><td dir="ltr">{item.code}</td><td>{item.applicability_scope}</td><td><select aria-label={`سطح الزام ${item.title||item.code}`} value={value} onChange={e=>setItems(current=>current.map(row=>row.document_definition_public_id===item.document_definition_public_id?{...row,requirement_level:e.target.value as OrganizationDocumentRequirementLevel}:row))}>{levels.map(level=><option key={level} value={level}>{labels[level]}</option>)}</select></td><td><Button disabled={busy===item.document_definition_public_id||!item.global_is_active} onClick={()=>void save(item,value)}>{busy===item.document_definition_public_id?"در حال ذخیره":"ذخیره"}</Button></td></tr>})}</tbody></table>{!items.length&&!error&&<p>هیچ تعریف مستند سراسری موجود نیست.</p>}</CardContent></Card></div>
}
