import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ErrorState, EmptyState, LoadingState } from "@/components/ui/async-state";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toUserFacingApiError, type UserFacingApiError } from "@/lib/api-error-ux";
import { addOrganizationGlobalPointToNetwork, listOrganizationGlobalPoints, transitionOrganizationGlobalPointAdoption, updateOrganizationGlobalPointAdoption, type OrganizationGlobalPoint } from "@/lib/api";

const labels: Record<OrganizationGlobalPoint["organization_state"], string> = { AVAILABLE: "آماده افزودن", ADOPTED: "افزوده‌شده", INACTIVE_FOR_ORGANIZATION: "غیرفعال برای سازمان", PLATFORM_DEPRECATED: "منسوخ‌شده در مرجع" };
const blank = { organization_reference_code: "", display_label: "", notes: "" };

export default function OrganizationGlobalNetworkTab() {
  const [rows, setRows] = useState<OrganizationGlobalPoint[]>([]), [error, setError] = useState<UserFacingApiError | null>(null), [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false);
  const [filters, setFilters] = useState({ q: "", country: "", type: "", mode: "", corridor: "", adoption_state: "" });
  const [selected, setSelected] = useState<OrganizationGlobalPoint | null>(null), [form, setForm] = useState(blank);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await listOrganizationGlobalPoints(filters); setRows(response.items); } catch (caught) { setError(toUserFacingApiError(caught)); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, [load]);
  const choose = (row: OrganizationGlobalPoint) => { setSelected(row); setForm({ organization_reference_code: row.adoption?.organization_reference_code || "", display_label: row.adoption?.display_label || "", notes: row.adoption?.notes || "" }); };
  const perform = async (action: () => Promise<unknown>) => { setSubmitting(true); setError(null); try { await action(); await load(); } catch (caught) { setError(toUserFacingApiError(caught)); } finally { setSubmitting(false); } };
  const addFromReference = () => selected && window.confirm("این نقطه به شبکه لجستیکی سازمان افزوده شود؟") && void perform(() => addOrganizationGlobalPointToNetwork(selected.public_id, form));
  const save = () => selected?.adoption && void perform(() => updateOrganizationGlobalPointAdoption(selected.adoption!, form));
  const lifecycle = (action: "activate" | "deactivate") => selected?.adoption && void perform(() => transitionOrganizationGlobalPointAdoption(selected.adoption!, action));
  const needsAdd = selected && (selected.organization_state === "AVAILABLE" || (selected.organization_state === "ADOPTED" && selected.adoption?.materialization.state === "NOT_MATERIALIZED"));
  return <section className="space-y-4" data-testid="organization-global-network" dir="rtl" aria-label="افزودن از شبکه مرجع">
    <Card><CardHeader><CardTitle>افزودن از شبکه مرجع</CardTitle><p className="text-sm text-muted-foreground">یک نقطهٔ تأییدشدهٔ پلتفرم را انتخاب کنید تا مستقیماً به شبکهٔ عملیاتی سازمان افزوده شود. اطلاعات حاکمیتی و سابقهٔ منبع در پس‌زمینه حفظ می‌شود.</p></CardHeader><CardContent className="grid gap-2 md:grid-cols-3">
      <Input aria-label="جست‌وجوی نقطه مرجع" placeholder="جست‌وجو" value={filters.q} onChange={e => setFilters({ ...filters, q: e.target.value })} /><Input aria-label="کشور نقطه مرجع" placeholder="کد کشور" dir="ltr" value={filters.country} onChange={e => setFilters({ ...filters, country: e.target.value })} /><Input aria-label="نوع نقطه مرجع" placeholder="نوع" value={filters.type} onChange={e => setFilters({ ...filters, type: e.target.value })} /><Input aria-label="شیوه حمل نقطه مرجع" placeholder="شیوه حمل" value={filters.mode} onChange={e => setFilters({ ...filters, mode: e.target.value })} /><Input aria-label="کریدور نقطه مرجع" placeholder="کریدور" value={filters.corridor} onChange={e => setFilters({ ...filters, corridor: e.target.value })} />
      <select aria-label="وضعیت افزودن به سازمان" className="h-10 rounded border bg-background px-3" value={filters.adoption_state} onChange={e => setFilters({ ...filters, adoption_state: e.target.value })}><option value="">همه وضعیت‌ها</option>{Object.entries(labels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select>
    </CardContent></Card>
    {error && <ErrorState message={error.message} onRetry={error.retryable ? () => void load() : undefined} />}
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardContent className="space-y-2 p-4">{loading ? <LoadingState /> : rows.length === 0 ? <EmptyState>نقطهٔ مرجعی مطابق جست‌وجو پیدا نشد.</EmptyState> : rows.map(row => <button type="button" key={row.public_id} onClick={() => choose(row)} className="w-full rounded border p-3 text-right focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" aria-pressed={selected?.public_id === row.public_id}><b><bdi dir="ltr">{row.immutable_code}</bdi> · {row.fa_name}</b><span className="block text-xs text-muted-foreground"><bdi dir="ltr">{row.country.code} · {row.point_type.code}</bdi> · {labels[row.organization_state]}</span></button>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>{selected ? selected.fa_name : "جزئیات نقطه مرجع"}</CardTitle></CardHeader><CardContent className="grid gap-3">{selected && <><p>{labels[selected.organization_state]} · <bdi dir="ltr">{selected.en_name} · {selected.geography.city}</bdi></p><div><Label htmlFor="organization-reference-code">کد داخلی سازمان</Label><Input id="organization-reference-code" dir="ltr" value={form.organization_reference_code} onChange={e => setForm({ ...form, organization_reference_code: e.target.value })} /></div><div><Label htmlFor="organization-display-label">برچسب نمایشی سازمان</Label><Input id="organization-display-label" value={form.display_label} onChange={e => setForm({ ...form, display_label: e.target.value })} /></div><div><Label htmlFor="organization-notes">یادداشت سازمان</Label><Textarea id="organization-notes" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></div>
        {needsAdd && <Button type="button" disabled={submitting} onClick={addFromReference}>{submitting ? "در حال افزودن…" : "افزودن به شبکهٔ سازمان"}</Button>}{selected.adoption && <Button type="button" variant="outline" disabled={submitting} onClick={save}>ذخیره اطلاعات سازمان</Button>}{selected.organization_state === "ADOPTED" && <Button type="button" variant="destructive" disabled={submitting} onClick={() => lifecycle("deactivate")}>غیرفعال‌سازی برای سازمان</Button>}{selected.adoption && <p className="text-xs font-medium text-muted-foreground">وضعیت اتصال سازمان: {selected.adoption.materialization.state === "MATERIALIZED" ? "مکان عملیاتی آماده است" : "آماده افزودن"}</p>}{selected.adoption?.materialization.state === "MATERIALIZED" && <a className="text-blue-700 underline" href={`#logistics-point-${selected.adoption.materialization.logistics_point_public_id}`}>مشاهده مکان عملیاتی سازمان</a>}{selected.organization_state === "INACTIVE_FOR_ORGANIZATION" && <Button type="button" disabled={submitting} onClick={() => lifecycle("activate")}>فعال‌سازی برای سازمان</Button>}{selected.organization_state === "PLATFORM_DEPRECATED" && <p className="text-red-700">این نقطه در شبکهٔ مرجع منسوخ شده است؛ سابقهٔ عملیاتی موجود حفظ می‌شود، اما افزودن یا فعال‌سازی دوباره ممکن نیست.</p>}</>}</CardContent></Card></div>
  </section>;
}
