import {useCallback,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";
import {createProjectLogisticsPoint,listLogisticsPoints,listLogisticsPointTypes,listProjectLogisticsPoints,reorderProjectLogisticsPoints,setProjectLogisticsPointActive,type LogisticsPointView,type ProjectLogisticsPointView} from "@/lib/api";
const roles=["ORIGIN","INTERMEDIATE","DESTINATION","CUSTOMS_PROCESSING","TRANSFER","STORAGE","LOADING","UNLOADING","OTHER_GOVERNED"];
export default function ProjectLogisticsNetwork({projectId}:{projectId:string}){const [rows,setRows]=useState<ProjectLogisticsPointView[]>([]);const [points,setPoints]=useState<LogisticsPointView[]>([]);const [types,setTypes]=useState<{public_id:string;fa_name:string}[]>([]);const [type,setType]=useState("");const [point,setPoint]=useState("");const [role,setRole]=useState("ORIGIN");const [sequence,setSequence]=useState("1");const [label,setLabel]=useState("");const [notes,setNotes]=useState("");const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setError("");const [r,t,p]=await Promise.all([listProjectLogisticsPoints(projectId),listLogisticsPointTypes(),listLogisticsPoints({type:type||undefined,active:"true"})]);setRows(r.items);setTypes(t.items);setPoints(p.items)}catch(e){setError(e instanceof Error?e.message:"Unable to load project network")}},[projectId,type]);useEffect(()=>{void load()},[load]);
 const add=async()=>{try{await createProjectLogisticsPoint(projectId,{logistics_point_public_id:point,project_role:role,sequence_number:Number(sequence),display_label:label||null,notes:notes||null});setLabel("");setNotes("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to add point")}};
 const move=async(index:number,delta:number)=>{const next=[...rows.filter(x=>x.is_active)];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];try{await reorderProjectLogisticsPoints(projectId,next);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to reorder")}};
 return <Card dir="auto"><CardHeader><CardTitle>شبکه لجستیکی پروژه</CardTitle><p className="text-sm text-muted-foreground">پیکربندی نقاط پروژه؛ بدون ایجاد خودکار مسیر یا نقطه کنترل</p></CardHeader><CardContent className="space-y-4">{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><select aria-label="فیلتر نوع نقطه" className="h-10 rounded border bg-background px-2" value={type} onChange={e=>{setType(e.target.value);setPoint("")}}><option value="">همه انواع</option>{types.map(x=><option key={x.public_id} value={x.public_id}>{x.fa_name}</option>)}</select><select aria-label="انتخاب نقطه موجود" className="h-10 rounded border bg-background px-2" value={point} onChange={e=>setPoint(e.target.value)}><option value="">انتخاب نقطه موجود</option>{points.map(x=><option key={x.public_id} value={x.public_id}>{x.fa_name} — {x.immutable_code}</option>)}</select><select aria-label="نقش نقطه در پروژه" className="h-10 rounded border bg-background px-2" value={role} onChange={e=>setRole(e.target.value)}>{roles.map(x=><option key={x}>{x}</option>)}</select><Input aria-label="ترتیب نقطه در پروژه" type="number" min={1} value={sequence} onChange={e=>setSequence(e.target.value)} placeholder="ترتیب"/><Input aria-label="برچسب نمایشی اختیاری" value={label} onChange={e=>setLabel(e.target.value)} placeholder="برچسب نمایشی اختیاری"/><Input aria-label="یادداشت اختیاری" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="یادداشت اختیاری"/><Button disabled={!point} onClick={add}>افزودن نقطه موجود</Button></div><div className="grid gap-2">{rows.map(x=>{const activeIndex=rows.filter(row=>row.is_active).findIndex(row=>row.public_id===x.public_id);return <div className="flex flex-wrap items-center gap-2 rounded border p-3" key={x.public_id}><b>{x.display_label||x.logistics_point.fa_name}</b><span className="text-sm text-muted-foreground">{x.logistics_point.fa_name} · {x.project_role} · {x.sequence_number}</span><span className="ms-auto">{x.is_active?"فعال":"غیرفعال"}</span>{x.is_active&&<><Button size="sm" variant="outline" onClick={()=>void move(activeIndex,-1)}>↑</Button><Button size="sm" variant="outline" onClick={()=>void move(activeIndex,1)}>↓</Button></>}<Button size="sm" variant="outline" onClick={async()=>{await setProjectLogisticsPointActive(projectId,x,!x.is_active);await load()}}>{x.is_active?"حذف از پیکربندی":"فعال‌سازی"}</Button></div>})}</div></CardContent></Card>}
