import {useCallback,useEffect,useMemo,useState} from "react";
import ProjectLogisticsNetwork from "@/components/ProjectLogisticsNetwork";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {createProjectConfiguration,listMilestoneTypes,listProjectConfiguration,listProjectDocumentDefinitions,listProjectLogisticsPointSelectors,listProjectServiceTypes,reorderProjectMilestones,setProjectConfigurationActive,updateProjectConfiguration,type ProjectConfigurationItem,type ProjectConfigurationResource} from "@/lib/api";

type Props={projectId:string;canManage?:boolean;locale?:"fa"|"en"};
type Ref={public_id:string;label:string};
const n=(v:string)=>v===""?null:Number(v);
const message=(e:unknown)=>e instanceof Error?e.message:"Request failed";

function Panel({projectId,resource,canManage}:{projectId:string;resource:ProjectConfigurationResource;canManage:boolean}) {
  const [rows,setRows]=useState<ProjectConfigurationItem[]>([]),[refs,setRefs]=useState<Ref[]>([]),[points,setPoints]=useState<Ref[]>([]);
  const [selected,setSelected]=useState(""),[editing,setEditing]=useState<ProjectConfigurationItem|null>(null);
  const [form,setForm]=useState<Record<string,string|boolean>>({requirement_level:"REQUIRED",duration_unit:"HOUR",display_order:"0",sequence:"1",is_primary:false,is_required:false});
  const [loading,setLoading]=useState(true),[selectorLoading,setSelectorLoading]=useState(true),[error,setError]=useState("");
  const active=useMemo(()=>rows.filter(x=>x.is_active),[rows]);
  const load=useCallback(async()=>{setLoading(true);setSelectorLoading(true);setError("");try{
    const listed=await listProjectConfiguration(projectId,resource,{page:1,per_page:100});setRows(listed.items);
    if(resource==="services"){const x=await listProjectServiceTypes({page:1,per_page:100});setRefs(x.items.map(v=>({public_id:v.public_id,label:`${v.fa_name||v.en_name} — ${v.immutable_code}`})))}
    else if(resource==="document-requirements"){const x=await listProjectDocumentDefinitions({page:1,per_page:100});setRefs(x.items.map(v=>({public_id:v.public_id,label:`${v.title} — ${v.code}`})))}
    else {const [types,locations]=await Promise.all([listMilestoneTypes({page:1,per_page:100}),listProjectLogisticsPointSelectors(projectId,{page:1,per_page:100})]);setRefs(types.items.map(v=>({public_id:v.public_id,label:`${v.fa_name||v.en_name} — ${v.immutable_code}`})));setPoints(locations.items.map(v=>({public_id:v.public_id,label:v.display_label||v.project_role||v.public_id})))}
  }catch(e){setError(message(e))}finally{setLoading(false);setSelectorLoading(false)}},[projectId,resource]);
  useEffect(()=>{void load()},[load]);
  const field=(key:string)=>String(form[key]??""); const checked=(key:string)=>form[key]===true;
  const change=(key:string,value:string|boolean)=>setForm(x=>({...x,[key]:value}));
  const payload=()=>resource==="services"?{service_type_public_id:selected,is_primary:checked("is_primary"),is_required:checked("is_required"),display_order:Number(field("display_order")||0),display_label:field("display_label")||null,notes:field("notes")||null}:resource==="document-requirements"?{document_definition_public_id:selected,requirement_level:field("requirement_level"),conditional_description:field("requirement_level")==="CONDITIONAL"?field("conditional_description"):null,display_order:Number(field("display_order")||0),notes:field("notes")||null}:{milestone_type_public_id:selected,sequence:Number(field("sequence")),is_required:checked("is_required"),project_logistics_point_public_id:field("project_logistics_point_public_id")||null,display_label:field("display_label")||null,target_duration_value:n(field("target_duration_value")),warning_duration_value:n(field("warning_duration_value")),duration_unit:(field("target_duration_value")||field("warning_duration_value"))?field("duration_unit"):null,notes:field("notes")||null};
  const validate=()=>{if(resource!=="milestone-definitions")return "";const t=n(field("target_duration_value")),w=n(field("warning_duration_value"));if((t!==null&&t<1)||(w!==null&&w<1))return "Durations must be positive";if(t!==null&&w!==null&&w<t)return "Warning duration must be greater than or equal to target";return ""};
  const save=async()=>{const invalid=validate();if(invalid){setError(invalid);return}try{setError("");const data=payload();if(editing){delete data.service_type_public_id;delete data.document_definition_public_id;delete data.milestone_type_public_id;await updateProjectConfiguration(projectId,resource,editing,data)}else await createProjectConfiguration(projectId,resource,data);setEditing(null);setSelected("");await load()}catch(e){setError(message(e))}};
  const edit=(x:ProjectConfigurationItem)=>{setEditing(x);setSelected(x.service_type_public_id||x.document_definition_public_id||x.milestone_type_public_id||"");setForm({is_primary:!!x.is_primary,is_required:!!x.is_required,display_order:String(x.display_order??0),display_label:x.display_label||"",notes:x.notes||"",requirement_level:x.requirement_level||"REQUIRED",conditional_description:x.conditional_description||"",sequence:String(x.sequence??1),project_logistics_point_public_id:x.project_logistics_point_public_id||"",target_duration_value:String(x.target_duration_value??""),warning_duration_value:String(x.warning_duration_value??""),duration_unit:x.duration_unit||"HOUR"})};
  const move=async(x:ProjectConfigurationItem,d:number)=>{const i=active.indexOf(x),j=i+d;if(j<0||j>=active.length)return;const ordered=[...active];[ordered[i],ordered[j]]=[ordered[j],ordered[i]];try{await reorderProjectMilestones(projectId,ordered);await load()}catch(e){setError(message(e))}};
  const title=resource==="services"?"Services":resource==="document-requirements"?"Documents":"Milestones";
  return <Card><CardHeader><CardTitle>{title}</CardTitle>{resource==="milestone-definitions"&&<p>Project configuration does not create operational milestones.</p>}</CardHeader><CardContent className="min-w-0 space-y-3 overflow-x-hidden">
    {error&&<div role="alert">{error}<Button variant="link" onClick={()=>void load()}>Refresh</Button></div>}
    {loading&&<p role="status">Loading configuration…</p>}
    {!loading&&rows.length===0&&<p>No configured items.</p>}
    {canManage?<fieldset className="grid min-w-0 gap-2 sm:grid-cols-2"><legend>{editing?`Edit ${title}`:`Add ${title}`}</legend>
      <label>Governed type<select aria-label="Governed type" disabled={!!editing||selectorLoading} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{selectorLoading?"Loading options…":refs.length?"Select an option":"No active options"}</option>{refs.map(x=><option key={x.public_id} value={x.public_id}>{x.label}</option>)}</select></label>
      {resource==="services"&&<><label><input type="checkbox" checked={checked("is_primary")} onChange={e=>change("is_primary",e.target.checked)}/> Primary</label><label><input type="checkbox" checked={checked("is_required")} onChange={e=>change("is_required",e.target.checked)}/> Required</label><label>Display order<Input type="number" min="0" value={field("display_order")} onChange={e=>change("display_order",e.target.value)}/></label></>}
      {resource==="document-requirements"&&<><label>Requirement level<select aria-label="Requirement level" value={field("requirement_level")} onChange={e=>change("requirement_level",e.target.value)}><option>REQUIRED</option><option>OPTIONAL</option><option>CONDITIONAL</option></select></label>{field("requirement_level")==="CONDITIONAL"&&<label>Conditional description<Input value={field("conditional_description")} onChange={e=>change("conditional_description",e.target.value)}/></label>}<label>Display order<Input type="number" min="0" value={field("display_order")} onChange={e=>change("display_order",e.target.value)}/></label></>}
      {resource==="milestone-definitions"&&<><label>Sequence<Input type="number" min="1" value={field("sequence")} onChange={e=>change("sequence",e.target.value)}/></label><label><input type="checkbox" checked={checked("is_required")} onChange={e=>change("is_required",e.target.checked)}/> Required</label><label>Project logistics point<select aria-label="Project logistics point" value={field("project_logistics_point_public_id")} onChange={e=>change("project_logistics_point_public_id",e.target.value)}><option value="">None</option>{points.map(x=><option key={x.public_id} value={x.public_id}>{x.label}</option>)}</select></label><label>Target duration<Input type="number" min="1" value={field("target_duration_value")} onChange={e=>change("target_duration_value",e.target.value)}/></label><label>Warning duration<Input type="number" min="1" value={field("warning_duration_value")} onChange={e=>change("warning_duration_value",e.target.value)}/></label><label>Duration unit<select aria-label="Duration unit" value={field("duration_unit")} onChange={e=>change("duration_unit",e.target.value)}><option>MINUTE</option><option>HOUR</option><option>DAY</option></select></label></>}
      {resource!=="document-requirements"&&<label>Display label<Input value={field("display_label")} onChange={e=>change("display_label",e.target.value)}/></label>}<label>Notes<Input value={field("notes")} onChange={e=>change("notes",e.target.value)}/></label>
      <Button disabled={!selected||selectorLoading} onClick={()=>void save()}>{editing?"Save changes":"Add"}</Button>{editing&&<Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button>}
    </fieldset>:<p>Read-only access</p>}
    <div>{rows.map(x=><div key={x.public_id} className="flex min-w-0 flex-wrap items-center gap-2 rounded border p-3"><span>{x.display_label||x.document_definition_title||x.milestone_type_code||x.service_type_public_id}</span><span>{x.is_active?"Active":"Inactive"}</span>{canManage&&<><Button aria-label={`Edit ${title} item`} variant="outline" onClick={()=>edit(x)}>Edit</Button>{resource==="milestone-definitions"&&x.is_active&&<><Button aria-label="Move milestone up" onClick={()=>void move(x,-1)}>↑</Button><Button aria-label="Move milestone down" onClick={()=>void move(x,1)}>↓</Button></>}<Button onClick={async()=>{try{await setProjectConfigurationActive(projectId,resource,x,!x.is_active);await load()}catch(e){setError(message(e))}}}>{x.is_active?"Deactivate":"Activate"}</Button></>}</div>)}</div>
  </CardContent></Card>;
}

export default function ProjectConfiguration({projectId,canManage=true,locale="fa"}:Props){const dir=locale==="fa"?"rtl":"ltr";return <section dir={dir} lang={locale} className="min-w-0 space-y-3 overflow-x-hidden"><h2>Project Configuration</h2><Tabs defaultValue="services"><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="services">Services</TabsTrigger><TabsTrigger value="network">Network</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger><TabsTrigger value="milestones">Milestones</TabsTrigger></TabsList><TabsContent value="services"><Panel projectId={projectId} resource="services" canManage={canManage}/></TabsContent><TabsContent value="network"><ProjectLogisticsNetwork projectId={projectId}/></TabsContent><TabsContent value="documents"><Panel projectId={projectId} resource="document-requirements" canManage={canManage}/></TabsContent><TabsContent value="milestones"><Panel projectId={projectId} resource="milestone-definitions" canManage={canManage}/></TabsContent></Tabs></section>}
