import {useCallback,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import OperationalPermission from "@/components/OperationalPermission";
import {appendEconomicObservation,confirmCommercialEconomics,correctEconomicObservation,createEconomicFx,createEconomicLine,getEconomicProjection,listEconomicLines,previewCommercialEconomics,type EconomicLine,type ShipmentEconomicsProjection} from "@/lib/api";

const show=(money:{amount:string;currency:string}|null)=>money?`${money.amount} ${money.currency}`:"Unknown";
export default function ShipmentEconomicsSection({shipmentPublicId}:{shipmentPublicId:string}){
 const [projection,setProjection]=useState<ShipmentEconomicsProjection>(); const [lines,setLines]=useState<EconomicLine[]>([]); const [preview,setPreview]=useState<Awaited<ReturnType<typeof previewCommercialEconomics>>["data"]>(); const [service,setService]=useState(""); const [authority,setAuthority]=useState(""); const [error,setError]=useState("");
 const [side,setSide]=useState<"REVENUE"|"COST">("COST"); const [stage,setStage]=useState<"ESTIMATE"|"COMMITMENT"|"ACTUAL">("ESTIMATE"); const [lineId,setLineId]=useState(""); const [amount,setAmount]=useState(""); const [currency,setCurrency]=useState("USD"); const [reason,setReason]=useState(""); const [fxId,setFxId]=useState(""); const [evidenceId,setEvidenceId]=useState(""); const [evidenceVersion,setEvidenceVersion]=useState("1"); const [selectedObservation,setSelectedObservation]=useState(""); const [correctionType,setCorrectionType]=useState<"SUPERSESSION"|"REVERSAL">("SUPERSESSION"); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
 const [fxFrom,setFxFrom]=useState("EUR"); const [fxTo,setFxTo]=useState("USD"); const [fxRate,setFxRate]=useState(""); const [fxSource,setFxSource]=useState("");
 const load=useCallback(async()=>{try{setError("");const [p,l,q]=await Promise.all([getEconomicProjection(shipmentPublicId),listEconomicLines(shipmentPublicId),previewCommercialEconomics(shipmentPublicId)]);setProjection(p.data);setLines(l.data);setPreview(q.data)}catch(e){setError(e instanceof Error?e.message:String(e))}},[shipmentPublicId]); useEffect(()=>{void load()},[load]);
 const confirm=async()=>{try{setError("");await confirmCommercialEconomics(shipmentPublicId,service.trim(),authority.trim());await load()}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const evidence=()=>evidenceId.trim()?[{artifact_public_id:evidenceId.trim(),artifact_version:Number(evidenceVersion),role:"SUPPORTING"}]:[];
 const submitFact=async()=>{try{setBusy(true);setError("");setNotice("");const common={stage,money:{amount:amount.trim(),currency:currency.trim().toUpperCase()},effective_at:new Date().toISOString(),authority:authority.trim(),reason:reason.trim(),idempotency_key:crypto.randomUUID(),...(fxId.trim()?{fx_rate_public_id:fxId.trim()}:{}),evidence:evidence()};if(lineId){await appendEconomicObservation(shipmentPublicId,lineId,common)}else{await createEconomicLine(shipmentPublicId,{...common,side,service_public_id:service.trim()})}setNotice(`${side} ${stage} recorded.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const submitCorrection=async()=>{const observation=lines.flatMap(x=>x.observations).find(x=>x.public_id===selectedObservation);if(!observation)return;try{setBusy(true);setError("");setNotice("");await correctEconomicObservation(shipmentPublicId,observation.public_id,{correction_type:correctionType,expected_version:observation.version,money:{amount:amount.trim(),currency:currency.trim().toUpperCase()},effective_at:new Date().toISOString(),authority:authority.trim(),reason:reason.trim(),idempotency_key:crypto.randomUUID(),...(fxId.trim()?{fx_rate_public_id:fxId.trim()}:{}),evidence:evidence()});setNotice(`${correctionType} recorded without changing history.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const submitFx=async()=>{try{setBusy(true);setError("");const result=await createEconomicFx({from_currency:fxFrom.toUpperCase(),to_currency:fxTo.toUpperCase(),rate:fxRate,rate_type:"MANUAL_APPROVED",source:fxSource.trim(),authority:authority.trim(),effective_at:new Date().toISOString()});setFxId(result.data.public_id);setNotice(`Authorized FX fact ${result.data.public_id} created and selected.`)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <section className="space-y-4 rounded border bg-white p-5" aria-label="Shipment Economics">
  <h3 className="font-semibold">Shipment Economics</h3><p className="text-sm text-slate-600">Missing facts remain UNKNOWN or INCOMPLETE. A recorded amount of 0 is displayed as zero and is never treated as missing.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="text-emerald-700">{notice}</p>}
  <div className="grid gap-3 md:grid-cols-3">{(["ESTIMATE","COMMITMENT","ACTUAL"] as const).map(stage=>{const x=projection?.stages[stage];return <article className="rounded border p-3" key={stage}><strong>{stage}</strong><p>Revenue: {show(x?.revenue||null)}</p><p>Cost: {show(x?.cost||null)}</p><p>Margin: {show(x?.margin||null)}</p><p className={x?.completeness==="COMPLETE"?"text-emerald-700":"text-amber-700"}>{x?.completeness||"UNKNOWN"}</p>{x?.missing_inputs.map(reason=><small className="block" key={reason}>{reason}</small>)}</article>})}</div>
  <OperationalPermission permission="economics.commitment.create">{preview&&!preview.already_materialized&&<div className="space-y-2 rounded bg-slate-50 p-3"><strong>Accepted commercial intent: {preview.commercial_intent.amount} {preview.commercial_intent.currency}</strong><p>Preview only—confirmation explicitly creates committed revenue.</p><div className="grid gap-2 sm:grid-cols-3"><Input aria-label="Service public identity" placeholder="Governed service public identity" value={service} onChange={e=>setService(e.target.value)}/><Input aria-label="Revenue authority" placeholder="Authority" value={authority} onChange={e=>setAuthority(e.target.value)}/><Button disabled={!preview.confirmation_allowed||!service.trim()||!authority.trim()} onClick={()=>void confirm()}>Confirm materialization</Button></div></div>}</OperationalPermission>
  <OperationalPermission permission={`economics.${stage.toLowerCase()}.create`}><div className="space-y-3 rounded border p-3"><h4 className="font-medium">Record approved economic fact</h4><div className="grid gap-2 md:grid-cols-3"><select aria-label="Economic side" className="rounded border p-2" value={side} onChange={e=>{setSide(e.target.value as typeof side);setLineId("")}}><option value="REVENUE">Revenue</option><option value="COST">Cost</option></select><select aria-label="Economic stage" className="rounded border p-2" value={stage} onChange={e=>setStage(e.target.value as typeof stage)}><option>ESTIMATE</option><option>COMMITMENT</option><option>ACTUAL</option></select><select aria-label="Existing economic line" className="rounded border p-2" value={lineId} onChange={e=>setLineId(e.target.value)}><option value="">Create a new line</option>{lines.filter(x=>x.side===side).map(x=><option value={x.public_id} key={x.public_id}>{x.service_title} · {x.public_id}</option>)}</select><Input aria-label="Service public identity for new line" placeholder="Service public identity" disabled={!!lineId} value={service} onChange={e=>setService(e.target.value)}/><Input aria-label="Original money amount" placeholder="Original amount (0 is valid)" value={amount} onChange={e=>setAmount(e.target.value)}/><Input aria-label="Original money currency" placeholder="Currency" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value)}/><Input aria-label="Economic authority" placeholder="Authority" value={authority} onChange={e=>setAuthority(e.target.value)}/><Input aria-label="Economic reason" placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><Input aria-label="Applied FX fact identity" placeholder="FX fact public identity (if needed)" value={fxId} onChange={e=>setFxId(e.target.value)}/><Input aria-label="Evidence public identity" placeholder="Evidence public identity (optional)" value={evidenceId} onChange={e=>setEvidenceId(e.target.value)}/><Input aria-label="Evidence version" type="number" min="1" value={evidenceVersion} onChange={e=>setEvidenceVersion(e.target.value)}/></div><Button disabled={busy||!amount.trim()||!currency.trim()||!authority.trim()||!reason.trim()||(!lineId&&!service.trim())} onClick={()=>void submitFact()}>Record {side.toLowerCase()} {stage.toLowerCase()}</Button></div></OperationalPermission>
  <OperationalPermission permission="economics.observation.correct"><div className="space-y-3 rounded border p-3"><h4 className="font-medium">Correction / reversal</h4><div className="grid gap-2 md:grid-cols-2"><select aria-label="Observation to correct" className="rounded border p-2" value={selectedObservation} onChange={e=>setSelectedObservation(e.target.value)}><option value="">Select an authorized observation</option>{lines.flatMap(x=>x.observations).filter(x=>x.status==="AUTHORIZED").map(x=><option value={x.public_id} key={x.public_id}>{x.stage} · {show(x.money)} · {x.public_id}</option>)}</select><select aria-label="Correction type" className="rounded border p-2" value={correctionType} onChange={e=>setCorrectionType(e.target.value as typeof correctionType)}><option value="SUPERSESSION">Correction / supersession</option><option value="REVERSAL">Reversal</option></select></div><p className="text-sm text-slate-600">Uses the amount, currency, authority, reason, FX, and evidence fields above. The original observation remains in history.</p><Button disabled={busy||!selectedObservation||!amount.trim()||!authority.trim()||!reason.trim()} onClick={()=>void submitCorrection()}>Record {correctionType.toLowerCase()}</Button></div></OperationalPermission>
  <OperationalPermission permission="economics.fx.approve"><div className="space-y-3 rounded border p-3"><h4 className="font-medium">Create authorized FX fact</h4><div className="grid gap-2 md:grid-cols-4"><Input aria-label="FX from currency" maxLength={3} value={fxFrom} onChange={e=>setFxFrom(e.target.value)}/><Input aria-label="FX to currency" maxLength={3} value={fxTo} onChange={e=>setFxTo(e.target.value)}/><Input aria-label="FX rate" placeholder="Exact rate" value={fxRate} onChange={e=>setFxRate(e.target.value)}/><Input aria-label="FX source" placeholder="Approved source" value={fxSource} onChange={e=>setFxSource(e.target.value)}/></div><Button disabled={busy||!fxRate||!fxSource.trim()||!authority.trim()} onClick={()=>void submitFx()}>Create and select FX fact</Button></div></OperationalPermission>
  <h4 className="font-medium">Economic Lines / History</h4>{!lines.length&&<p>No economic truth has been recorded. Missing is not zero.</p>}{lines.map(line=><details className="rounded border p-3" key={line.public_id}><summary>{line.side} · {line.service_title} ({line.service_code}) · {line.lifecycle}</summary>{line.observations.map(o=><div className="mt-2 text-sm" key={o.public_id}><p>{o.stage} · {show(o.money)} · {o.status} · effective {new Date(o.effective_at).toLocaleString()} · recorded {new Date(o.recorded_at).toLocaleString()}{o.fx_binding&&<> · FX {o.fx_binding.fx_rate_public_id} @ {o.fx_binding.rate} {o.fx_binding.to_currency}</>}</p>{o.evidence.map(item=><p className="text-slate-600" key={item.public_id}>Evidence {item.artifact_public_id} v{item.artifact_version} · {item.role}</p>)}</div>)}</details>)}
 </section>;
}
