import {useCallback,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import OperationalPermission from "@/components/OperationalPermission";
import {confirmCommercialEconomics,getEconomicProjection,listEconomicLines,previewCommercialEconomics,type EconomicLine,type ShipmentEconomicsProjection} from "@/lib/api";

const show=(money:{amount:string;currency:string}|null)=>money?`${money.amount} ${money.currency}`:"Unknown";
export default function ShipmentEconomicsSection({shipmentPublicId}:{shipmentPublicId:string}){
 const [projection,setProjection]=useState<ShipmentEconomicsProjection>();const [lines,setLines]=useState<EconomicLine[]>([]);const [preview,setPreview]=useState<Awaited<ReturnType<typeof previewCommercialEconomics>>["data"]>();const [service,setService]=useState("");const [authority,setAuthority]=useState("");const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setError("");const [p,l,q]=await Promise.all([getEconomicProjection(shipmentPublicId),listEconomicLines(shipmentPublicId),previewCommercialEconomics(shipmentPublicId)]);setProjection(p.data);setLines(l.data);setPreview(q.data)}catch(e){setError(e instanceof Error?e.message:String(e))}},[shipmentPublicId]);useEffect(()=>{void load()},[load]);
 const confirm=async()=>{try{setError("");await confirmCommercialEconomics(shipmentPublicId,Number(service),authority.trim());await load()}catch(e){setError(e instanceof Error?e.message:String(e))}};
 return <section className="space-y-4 rounded border bg-white p-5" aria-label="Shipment Economics"><h3 className="font-semibold">Shipment Economics</h3>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="grid gap-3 md:grid-cols-3">{(["ESTIMATE","COMMITMENT","ACTUAL"] as const).map(stage=>{const x=projection?.stages[stage];return <article className="rounded border p-3" key={stage}><strong>{stage}</strong><p>Revenue: {show(x?.revenue||null)}</p><p>Cost: {show(x?.cost||null)}</p><p>Margin: {show(x?.margin||null)}</p><p className={x?.completeness==="COMPLETE"?"text-emerald-700":"text-amber-700"}>{x?.completeness||"UNKNOWN"}</p>{x?.missing_inputs.map(reason=><small className="block" key={reason}>{reason}</small>)}</article>})}</div><OperationalPermission permission="economics.commitment.create">{preview&&!preview.already_materialized&&<div className="space-y-2 rounded bg-slate-50 p-3"><strong>Accepted commercial intent: {preview.commercial_intent.amount} {preview.commercial_intent.currency}</strong><p>Preview only—confirmation explicitly creates committed revenue.</p><div className="grid gap-2 sm:grid-cols-3"><Input aria-label="Service type ID" placeholder="Governed service type ID" value={service} onChange={e=>setService(e.target.value)}/><Input aria-label="Revenue authority" placeholder="Authority" value={authority} onChange={e=>setAuthority(e.target.value)}/><Button disabled={!preview.confirmation_allowed||!Number(service)||!authority.trim()} onClick={()=>void confirm()}>Confirm materialization</Button></div></div>}</OperationalPermission><h4 className="font-medium">Economic Lines / History</h4>{!lines.length&&<p>No economic truth has been recorded. Missing is not zero.</p>}{lines.map(line=><details className="rounded border p-3" key={line.public_id}><summary>{line.side} · Service {line.service_type_id} · {line.lifecycle}</summary>{line.observations.map(o=><p className="mt-2 text-sm" key={o.public_id}>{o.stage} · {show(o.money)} · {o.status} · effective {new Date(o.effective_at).toLocaleString()} · recorded {new Date(o.recorded_at).toLocaleString()}</p>)}</details>)}</section>;
}
