import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createShipmentCargoItem, listShipmentCargoItems, request, updateShipmentCargoItem, getCargoTransportAllocations, createCargoTransportAllocation, deleteCargoTransportAllocation, getOperationalTransportTracking, enableOperationalTransportTracking, addOperationalTransportTrackingUpdate, type ShipmentCargoItem, type CargoTransportAllocation, type ShipmentTransportUnitOption, type OperationalTransportTracking } from "@/lib/api";

type Option={public_id:string;code:string;name:string;cargo_type_public_id?:string;default_uom_public_id?:string|null;symbol?:string};
export default function ShipmentCargoItems({shipmentPublicId,legacyDescription}:{shipmentPublicId:string;legacyDescription?:string|null}){
 const [items,setItems]=useState<ShipmentCargoItem[]>([]),[options,setOptions]=useState<{catalog:Option[];cargo_types:Option[];uoms:Option[]}>({catalog:[],cargo_types:[],uoms:[]}),[error,setError]=useState("");
 const [form,setForm]=useState({line_number:"1",catalog_item_public_id:"",display_name:"",cargo_type_public_id:"",quantity:"",uom_public_id:"",part_number:"",customer_item_code:"",hs_code:"",brand:"",model:"",description:""});
 const [edits,setEdits]=useState<Record<string,string>>({});
 const [allocations,setAllocations]=useState<CargoTransportAllocation[]>([]),[units,setUnits]=useState<ShipmentTransportUnitOption[]>([]);
 const [allocation,setAllocation]=useState({cargo_item_public_id:"",transport_unit_id:"",allocated_quantity:""});
 const [tracking,setTracking]=useState<OperationalTransportTracking|null>(null); const [selectedUnit,setSelectedUnit]=useState(""); const [trackingForm,setTrackingForm]=useState({status:"in_transit",location_text:"",customer_message:"",internal_note:"",is_customer_visible:true});
 const load=useCallback(async()=>{try{const [lines,opts,allocationData,trackingData]=await Promise.all([listShipmentCargoItems(shipmentPublicId),request<{catalog:Option[];cargo_types:Option[];uoms:Option[]}>('/api/internal/cargo-options'),getCargoTransportAllocations(shipmentPublicId),getOperationalTransportTracking(shipmentPublicId)]);setItems(lines.items);setOptions(opts);setAllocations(allocationData.allocations);setUnits(allocationData.transport_units);setTracking(trackingData.tracking);setError("");}catch{setError("بارگذاری اقلام انجام نشد / Cargo lines could not be loaded.");}},[shipmentPublicId]);
 useEffect(()=>{void load();},[load]);
 const choose=(id:string)=>{const row=options.catalog.find(x=>x.public_id===id);setForm({...form,catalog_item_public_id:id,cargo_type_public_id:row?.cargo_type_public_id||form.cargo_type_public_id,uom_public_id:row?.default_uom_public_id||form.uom_public_id,display_name:row?.name||form.display_name});};
 const create=async()=>{try{await createShipmentCargoItem(shipmentPublicId,{...form,line_number:Number(form.line_number),quantity:form.quantity,catalog_item_public_id:form.catalog_item_public_id||undefined});setForm({...form,line_number:String(Number(form.line_number)+1),catalog_item_public_id:"",display_name:"",quantity:"",part_number:"",customer_item_code:"",hs_code:"",brand:"",model:"",description:""});await load();}catch{setError("شماره خط، مقدار، نوع کالا و واحد را بررسی کنید / Check line, quantity, CargoType and UOM.");}};
 return <Card dir="auto"><CardHeader><CardTitle>اقلام ساختاریافته / Structured cargo items</CardTitle></CardHeader><CardContent className="space-y-4">
  {error&&<p aria-live="polite" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
  <div className="rounded border bg-amber-50 p-3"><strong>شرح قدیمی کالا / Legacy cargo description (preserved separately)</strong><p className="break-words">{legacyDescription||"ثبت نشده / Not provided"}</p></div>
  <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
   <Input aria-label="Cargo line number" type="number" min="1" value={form.line_number} onChange={e=>setForm({...form,line_number:e.target.value})}/>
   <select aria-label="Catalog item" className="min-h-11 min-w-0 rounded border px-3" value={form.catalog_item_public_id} onChange={e=>choose(e.target.value)}><option value="">ورود دستی / Manual entry</option>{options.catalog.map(x=><option key={x.public_id} value={x.public_id}>{x.code} — {x.name}</option>)}</select>
   <Input aria-label="Cargo display name" placeholder="نام نمایشی / Display name" value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/>
   <select aria-label="Cargo type" className="min-h-11 min-w-0 rounded border px-3" value={form.cargo_type_public_id} onChange={e=>setForm({...form,cargo_type_public_id:e.target.value})}><option value="">نوع کالا / Cargo type</option>{options.cargo_types.map(x=><option key={x.public_id} value={x.public_id}>{x.name}</option>)}</select>
   <Input aria-label="Cargo quantity" type="number" min="0.000001" step="any" placeholder="مقدار / Quantity" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/>
   <select aria-label="Unit of measure" className="min-h-11 min-w-0 rounded border px-3" value={form.uom_public_id} onChange={e=>setForm({...form,uom_public_id:e.target.value})}><option value="">واحد / Unit of measure</option>{options.uoms.map(x=><option key={x.public_id} value={x.public_id}>{x.name} ({x.symbol})</option>)}</select>
   {(["part_number","customer_item_code","hs_code","brand","model","description"] as const).map(name=><Input key={name} aria-label={name.replace(/_/g," ")} placeholder={name.replace(/_/g," ")} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>)}
   <Button className="min-h-11" onClick={()=>void create()}>افزودن / Add cargo line</Button>
  </div>
  <div className="grid gap-3 lg:grid-cols-2">{items.map(x=><article className="min-w-0 rounded border p-3 text-sm" key={x.public_id}>
   <div className="flex flex-wrap justify-between gap-2"><strong className="break-words">#{x.line_number} · {x.display_name_snapshot}</strong><span>{x.source==="catalog"?"پیوندی / Linked":"دستی / Manual"}</span></div>
   <p className="mt-1 break-words">{x.cargo_type_code_snapshot} · {x.cargo_type_fa_snapshot} · {x.uom_code_snapshot} ({x.uom_symbol_snapshot})</p>
   <p className="mt-1 break-words">{x.part_number_snapshot||"—"} / {x.customer_item_code_snapshot||"—"} / {x.hs_code_snapshot||"—"}</p>
   {x.description_snapshot&&<p className="mt-1 break-words">{x.description_snapshot}</p>}
   <div className="mt-3 flex flex-wrap items-center gap-2"><Input aria-label={`Edit quantity line ${x.line_number}`} className="w-28" type="number" min="0.000001" step="any" value={edits[x.public_id]??x.quantity} onChange={e=>setEdits({...edits,[x.public_id]:e.target.value})}/><span>{x.uom_symbol_snapshot} · allocated {x.allocated_quantity||"0"} · remaining {x.remaining_quantity||x.quantity}</span><Button variant="outline" onClick={async()=>{try{await updateShipmentCargoItem(shipmentPublicId,x.public_id,{quantity:edits[x.public_id]??x.quantity,version:x.version});await load();}catch{setError("نسخه تغییر کرده است / Version conflict. Refresh and retry.");}}}>ذخیره / Save</Button><span>v{x.version}</span></div>
  </article>)}</div>
  <section className="rounded border p-3"><h3 className="font-semibold">Cargo ↔ transport allocation</h3><p className="text-sm">Assign an existing cargo line to a transport unit in that line’s UOM.</p><div className="mt-2 flex flex-wrap gap-2"><select aria-label="Allocation cargo" value={allocation.cargo_item_public_id} onChange={e=>setAllocation({...allocation,cargo_item_public_id:e.target.value})}><option value="">Cargo line</option>{items.map(x=><option key={x.public_id} value={x.public_id}>{x.display_name_snapshot}</option>)}</select><select aria-label="Allocation transport" value={allocation.transport_unit_id} onChange={e=>setAllocation({...allocation,transport_unit_id:e.target.value})}><option value="">Transport unit</option>{units.map(x=><option key={x.id} value={x.id}>{x.unit_code} · {x.unit_type}</option>)}</select><Input aria-label="Allocation quantity" className="w-32" type="number" min="0.000001" step="any" value={allocation.allocated_quantity} onChange={e=>setAllocation({...allocation,allocated_quantity:e.target.value})}/><Button onClick={async()=>{try{await createCargoTransportAllocation(shipmentPublicId,{...allocation,transport_unit_id:Number(allocation.transport_unit_id)});setAllocation({cargo_item_public_id:"",transport_unit_id:"",allocated_quantity:""});await load();}catch{setError("Allocation could not be saved. Check the remaining quantity and transport unit.");}}}>Allocate</Button></div><div className="mt-3 space-y-1 text-sm">{allocations.map(a=><div key={a.public_id} className="flex justify-between rounded bg-muted p-2"><span>{a.transport_unit_code}: {a.cargo_name} — {a.allocated_quantity} {a.uom_symbol}</span><Button size="sm" variant="outline" onClick={async()=>{await deleteCargoTransportAllocation(shipmentPublicId,a.public_id);await load();}}>Unassign</Button></div>)}</div></section>
  <section className="rounded border p-3"><h3 className="font-semibold">Transport tracking</h3>{!tracking?<Button className="mt-2" onClick={async()=>{try{setTracking((await enableOperationalTransportTracking(shipmentPublicId)).tracking);await load();}catch{setError("Tracking could not be enabled.");}}}>Enable tracking</Button>:<><div className="mt-2 space-y-2">{tracking.units.map(u=><div key={u.id} className="rounded bg-muted p-2"><strong>{u.unit_code}</strong> · {u.latest_status}<div>{u.allocated_cargo.map(c=><span key={c.cargo_name} className="mr-2">{c.cargo_name} {c.allocated_quantity} {c.uom_symbol}</span>)}</div><div className="text-xs">{u.history.map(h=><div key={h.id}>{h.status} · {h.location.location_name||"—"} · {h.occurred_at}</div>)}</div></div>)}</div><div className="mt-2 flex flex-wrap gap-2"><select aria-label="Tracked transport" value={selectedUnit} onChange={e=>setSelectedUnit(e.target.value)}><option value="">Transport unit</option>{tracking.units.map(u=><option key={u.id} value={u.id}>{u.unit_code}</option>)}</select><select aria-label="Tracking status" value={trackingForm.status} onChange={e=>setTrackingForm({...trackingForm,status:e.target.value})}>{["loading","departed","in_transit","at_checkpoint","delayed","arrived_destination","delivered","cancelled"].map(s=><option key={s}>{s}</option>)}</select><Input aria-label="Tracking location" placeholder="Location" value={trackingForm.location_text} onChange={e=>setTrackingForm({...trackingForm,location_text:e.target.value})}/><Input aria-label="Customer message" placeholder="Customer message" value={trackingForm.customer_message} onChange={e=>setTrackingForm({...trackingForm,customer_message:e.target.value})}/><Button onClick={async()=>{try{if(!selectedUnit)throw new Error();const response=await addOperationalTransportTrackingUpdate(shipmentPublicId,Number(selectedUnit),{...trackingForm,occurred_at:new Date().toISOString()});setTracking(response.tracking);}catch{setError("Tracking update could not be saved.");}}}>Add update</Button></div></>}</section>
 </CardContent></Card>;
}
