import {useCallback,useEffect,useMemo,useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {createShipmentExternalReference,fetchCaseDocuments,listShipmentExternalReferences,transitionShipmentExternalReference,type ExternalOperationalReference,type ExternalReferenceTypeCode,type CaseDocumentFile} from "@/lib/api";
const labels:Record<ExternalReferenceTypeCode,string>={BILL_OF_LADING_NUMBER:"شماره بارنامه دریایی / B/L",AIR_WAYBILL_NUMBER:"شماره بارنامه هوایی / AWB",CMR_NUMBER:"شماره CMR"};
export default function ShipmentExternalReferences({shipmentPublicId,requestId}:{shipmentPublicId:string;requestId?:string|null}){
 const [rows,setRows]=useState<ExternalOperationalReference[]>([]),[files,setFiles]=useState<CaseDocumentFile[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState<{type:ExternalReferenceTypeCode;value:string;issuer_key:string;source_system:string;evidence:string}>({type:"BILL_OF_LADING_NUMBER",value:"",issuer_key:"",source_system:"",evidence:""});
 const [reason,setReason]=useState<Record<string,string>>({}),[replacement,setReplacement]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{const [references,documents]=await Promise.all([listShipmentExternalReferences(shipmentPublicId),requestId?fetchCaseDocuments(requestId):Promise.resolve(null)]);setRows(references.data);setFiles(documents?[...documents.requirements.flatMap(x=>x.active_files),...documents.miscellaneous]:[]);setError("");}catch(e){setError(e instanceof Error?e.message:"رفرنس‌های عملیاتی دریافت نشد.");}},[requestId,shipmentPublicId]);
 useEffect(()=>{void load()},[load]);
 const evidence=useMemo(()=>files.find(x=>x.public_id===form.evidence),[files,form.evidence]);
 const run=async(action:()=>Promise<unknown>)=>{try{setBusy(true);setError("");await action();await load()}catch(e){setError(e instanceof Error?e.message:"عملیات رفرنس انجام نشد.")}finally{setBusy(false)}};
 const create=()=>run(async()=>{await createShipmentExternalReference(shipmentPublicId,{type:form.type,value:form.value,issuer_key:form.issuer_key||undefined,source_system:form.source_system||undefined,evidence_document_public_id:evidence?.public_id,evidence_version:evidence?.version_number},crypto.randomUUID());setForm({...form,value:"",issuer_key:"",source_system:"",evidence:""})});
 return <Card dir="rtl"><CardHeader><CardTitle>رفرنس‌های عملیاتی خارجی</CardTitle><p className="text-sm text-muted-foreground">شماره سند با فایل سند متفاوت است. تاریخچه ابطال و جایگزینی حفظ می‌شود.</p></CardHeader><CardContent className="space-y-4">
  {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
  <div className="grid gap-2 md:grid-cols-2"><select aria-label="نوع رفرنس عملیاتی" className="min-h-10 rounded border px-3" value={form.type} onChange={e=>setForm({...form,type:e.target.value as ExternalReferenceTypeCode})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><Input aria-label="مقدار رفرنس عملیاتی" dir="ltr" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} placeholder="Reference value"/><Input aria-label="صادرکننده رفرنس" value={form.issuer_key} onChange={e=>setForm({...form,issuer_key:e.target.value})} placeholder="صادرکننده (اختیاری)"/><Input aria-label="سامانه منبع" value={form.source_system} onChange={e=>setForm({...form,source_system:e.target.value})} placeholder="سامانه منبع (اختیاری)"/><select aria-label="فایل شاهد رفرنس" className="min-h-10 rounded border px-3" value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}><option value="">بدون فایل شاهد</option>{files.map(file=><option key={file.public_id} value={file.public_id}>{file.original_filename} · نسخه {file.version_number}</option>)}</select><Button disabled={busy||!form.value.trim()} onClick={()=>void create()}>افزودن رفرنس</Button></div>
  {!rows.length?<p className="rounded border border-dashed p-4">هنوز رفرنس عملیاتی برای این محموله ثبت نشده است.</p>:rows.map(row=><article key={row.public_id} className="space-y-2 rounded border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{labels[row.type]}</strong><span>{row.lifecycle_status}</span></div><p dir="ltr" className="font-mono">{row.display_value}</p><p className="text-sm">{row.issuer_key||"صادرکننده ثبت نشده"} · {row.source_system||"منبع ثبت نشده"} · نسخه {row.revision}</p>{row.evidence&&<p className="text-sm">فایل شاهد: <span dir="ltr">{row.evidence.document_public_id}</span> · نسخه {row.evidence.version}</p>}{row.lifecycle_status==="ACTIVE"&&<div className="grid gap-2 sm:grid-cols-2"><Input aria-label={`دلیل تغییر ${row.display_value}`} value={reason[row.public_id]||""} onChange={e=>setReason({...reason,[row.public_id]:e.target.value})} placeholder="دلیل الزامی"/><Input aria-label={`مقدار جایگزین ${row.display_value}`} dir="ltr" value={replacement[row.public_id]||""} onChange={e=>setReplacement({...replacement,[row.public_id]:e.target.value})} placeholder="مقدار جایگزین"/><Button variant="outline" disabled={busy||!reason[row.public_id]?.trim()||!replacement[row.public_id]?.trim()} onClick={()=>void run(()=>transitionShipmentExternalReference(shipmentPublicId,row,"supersede",{reason:reason[row.public_id],value:replacement[row.public_id]},crypto.randomUUID()))}>جایگزینی</Button><Button variant="destructive" disabled={busy||!reason[row.public_id]?.trim()} onClick={()=>void run(()=>transitionShipmentExternalReference(shipmentPublicId,row,"cancel",{reason:reason[row.public_id]},crypto.randomUUID()))}>ابطال</Button></div>}</article>)}
 </CardContent></Card>;
}
