import { useCallback,useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { createTrackingLocation,deactivateTrackingLocation,fetchAdminTrackingLocations,updateTrackingLocation,type TrackingLocationReference } from "@/lib/api";

const types=["origin_city","commercial_hub","seaport","rail_terminal","road_terminal","border_point","transit_city","iran_gateway","destination_city","other"];
export default function TrackingLocationsAdminTab(){
 const [items,setItems]=useState<TrackingLocationReference[]>([]),[q,setQ]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({internal_key:"",name_fa:"",name_en:"",country_code:"CN",location_type:"transit_city",aliases:"",sort_order:"0"});
 const load=useCallback(()=>fetchAdminTrackingLocations(q).then(x=>setItems(x.items)),[q]); useEffect(()=>{load();},[load]);
 const save=async()=>{setBusy(true);try{await createTrackingLocation({...form,aliases:form.aliases.split(",").map(x=>x.trim()).filter(Boolean),sort_order:Number(form.sort_order)});setForm({...form,internal_key:"",name_fa:"",name_en:"",aliases:""});await load();}finally{setBusy(false)}};
 return <div className="space-y-4"><Card><CardHeader><CardTitle>نقاط پرتکرار ردیابی چین–ایران</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="جست‌وجو"/><Button onClick={load}>جست‌وجو</Button></div><div className="grid gap-2 md:grid-cols-4"><Input value={form.internal_key} onChange={e=>setForm({...form,internal_key:e.target.value})} placeholder="internal key"/><Input value={form.name_fa} onChange={e=>setForm({...form,name_fa:e.target.value})} placeholder="نام فارسی"/><Input value={form.name_en} onChange={e=>setForm({...form,name_en:e.target.value})} placeholder="English name"/><Input value={form.country_code} onChange={e=>setForm({...form,country_code:e.target.value.toUpperCase()})} placeholder="Country"/><Select value={form.location_type} onValueChange={v=>setForm({...form,location_type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{types.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Input value={form.aliases} onChange={e=>setForm({...form,aliases:e.target.value})} placeholder="aliases, comma separated"/><Input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})} placeholder="ترتیب"/><Button disabled={busy||!form.internal_key||!form.name_fa} onClick={save}>افزودن</Button></div></CardContent></Card><div className="grid gap-3 md:grid-cols-2">{items.map(x=><Card key={x.id}><CardContent className="space-y-2 p-4"><p className="font-bold">{x.name_fa} / {x.name_en}</p><p className="text-xs text-slate-500">{x.country_code} · {x.location_type} · {x.is_active?"فعال":"غیرفعال"}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={async()=>{const name=window.prompt("نام فارسی",x.name_fa);if(name){await updateTrackingLocation(x.id,{name_fa:name});await load()}}}>ویرایش نام</Button>{x.is_active&&<Button size="sm" variant="destructive" onClick={async()=>{await deactivateTrackingLocation(x.id);await load()}}>غیرفعال‌سازی</Button>}</div></CardContent></Card>)}</div></div>
}
