import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router";
import { beforeEach, describe, expect, it, vi } from "vitest";
import DashboardBuilder from "@/pages/DashboardBuilder";
import { operationsControlTower } from "@/dashboard/control-tower";
import * as api from "@/lib/api";

vi.mock("@/lib/api",async()=>{const actual=await vi.importActual<typeof import("@/lib/api")>("@/lib/api");return {...actual,getDashboard:vi.fn(),getAnalyticsSemanticRegistry:vi.fn(),updateDashboard:vi.fn()}});
vi.mock("@/pages/OperationsControlTower",()=>({default:({definition}:{definition:{widgets:unknown[]}})=><output data-testid="shared-runtime">{definition.widgets.length}</output>}));
const metric=(metric_key:string,supported_dimensions:string[]=[])=>({metric_key,business_name:metric_key,grain:"fact",unit:"count",readiness:"READY" as const,supported_dimensions,supported_filters:["TIME","CUSTOMER","PROJECT"],supported_time_dimensions:["created"],supported_time_grains:["day"],drilldown_type:"shipment_list",drilldown_supported:true,semantic_version:"analytics-semantic-v1"});
const registry:api.AnalyticsSemanticRegistry={semantic_version:"analytics-semantic-v1",metrics:[metric("ACTIVE_SHIPMENT_COUNT"),metric("OPEN_EXCEPTION_COUNT"),metric("OPEN_WORK_ITEM_COUNT"),metric("DOCUMENT_READINESS_COVERAGE"),metric("SHIPMENT_COUNT",["SHIPMENT_STATUS"]),metric("ROUTE_LEG_COUNT",["LEG_STATUS","TRANSPORT_MODE"]),metric("DELAY_CASE_COUNT",["TIME"])],dimensions:["TIME","CUSTOMER","PROJECT","SHIPMENT_STATUS","LEG_STATUS","TRANSPORT_MODE"].map(dimension_key=>({dimension_key,business_name:dimension_key,identity_source:"test",history_policy:"test",readiness:"READY" as const,nullable:true,semantic_version:"analytics-semantic-v1"})),relationships:[],coverage:{},null_semantics:["VALUE","ZERO","NULL_UNKNOWN","NOT_APPLICABLE","NOT_READY","OUT_OF_SCOPE"]};
const dashboard={public_id:"db-1",dashboard_type:"PERSONAL" as const,name:"شخصی",description:"توضیح",visibility:"PRIVATE" as const,status:"ACTIVE" as const,semantic_version:"analytics-semantic-v1",dashboard_schema_version:"dashboard-definition-v1",version:1,definition:operationsControlTower};
const renderRoute=()=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><MemoryRouter initialEntries={["/dashboards/db-1/edit"]}><Routes><Route path="/dashboards/:public_id/edit" element={<DashboardBuilder/>}/><Route path="/dashboards/:public_id" element={<p>detail</p>}/></Routes></MemoryRouter></QueryClientProvider>);
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.getDashboard).mockResolvedValue({data:dashboard});vi.mocked(api.getAnalyticsSemanticRegistry).mockResolvedValue({data:registry});vi.mocked(api.updateDashboard).mockResolvedValue({data:{...dashboard,version:2,name:"جدید"}})});
describe("personal dashboard edit route",()=>{
  it("loads directly, starts clean, and previews through the shared runtime",async()=>{renderRoute();expect(await screen.findByRole("heading",{name:"ویرایش داشبورد"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"ذخیره"})).toBeDisabled();await userEvent.click(screen.getByRole("button",{name:"پیش‌نمایش"}));expect(screen.getByTestId("shared-runtime")).toHaveTextContent("8");expect(api.updateDashboard).not.toHaveBeenCalled()});
  it("saves one explicit patch with the loaded expected version",async()=>{renderRoute();const name=await screen.findByLabelText("نام داشبورد");fireEvent.change(name,{target:{value:"جدید"}});await userEvent.click(screen.getByRole("button",{name:"ذخیره"}));await waitFor(()=>expect(api.updateDashboard).toHaveBeenCalledWith("db-1",expect.objectContaining({expected_version:1,name:"جدید",definition:expect.any(Object)})));expect(await screen.findByText("بدون تغییر")).toBeInTheDocument()});
  it("does not expose archived dashboards to the editor",async()=>{vi.mocked(api.getDashboard).mockResolvedValueOnce({data:{...dashboard,status:"ARCHIVED"}});renderRoute();expect(await screen.findByText(/بایگانی‌شده/)).toBeInTheDocument();expect(screen.queryByRole("button",{name:"ذخیره"})).not.toBeInTheDocument()});
  it("preserves an invalid local draft without calling analytics or PATCH",async()=>{renderRoute();const name=await screen.findByLabelText("نام داشبورد");fireEvent.change(name,{target:{value:""}});expect(screen.getByRole("button",{name:"ذخیره"})).toBeDisabled();expect(api.updateDashboard).not.toHaveBeenCalled()});
});
