import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { BrowserRouter } from "react-router";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { TooltipProvider } from "@/components/ui/tooltip";
import OperationsControlTower from "@/pages/OperationsControlTower";
import * as api from "@/lib/api";
class ResizeObserverMock { observe() {} unobserve() {} disconnect() {} }
vi.stubGlobal("ResizeObserver", ResizeObserverMock);
vi.mock("@/components/OperationsNav", () => ({ default: () => <nav>عملیات</nav> }));
vi.mock("@/lib/api", async () => ({ ...(await vi.importActual<typeof import("@/lib/api")>("@/lib/api")), getOperationalContext:vi.fn(),getAnalyticsSemanticRegistry:vi.fn(),queryAnalytics:vi.fn(),drilldownAnalytics:vi.fn() }));
const metric = (metric_key:string, supported_dimensions:string[] = []) => ({metric_key,business_name:metric_key,grain:"fact",unit:"count",readiness:"READY",supported_dimensions,supported_filters:["TIME","CUSTOMER","PROJECT"],supported_time_dimensions:[metric_key === "DELAY_CASE_COUNT" ? "started" : "created"],supported_time_grains:["day"],drilldown_type:"shipment_list",drilldown_supported:true,semantic_version:"analytics-semantic-v1"});
const registry = {semantic_version:"analytics-semantic-v1",metrics:[metric("ACTIVE_SHIPMENT_COUNT"),metric("OPEN_EXCEPTION_COUNT"),metric("OPEN_WORK_ITEM_COUNT"),metric("DOCUMENT_READINESS_COVERAGE"),metric("SHIPMENT_COUNT",["SHIPMENT_STATUS"]),metric("ROUTE_LEG_COUNT",["LEG_STATUS","TRANSPORT_MODE"]),metric("DELAY_CASE_COUNT",["TIME"])],dimensions:["TIME","CUSTOMER","PROJECT","SHIPMENT_STATUS","LEG_STATUS","TRANSPORT_MODE"].map((dimension_key) => ({dimension_key,business_name:dimension_key,identity_source:"test",history_policy:"test",readiness:"READY",nullable:true,semantic_version:"analytics-semantic-v1"})),relationships:[],coverage:{},null_semantics:["VALUE","ZERO","NULL_UNKNOWN","NOT_APPLICABLE","NOT_READY","OUT_OF_SCOPE"]};
const response = (metricKey:string) => ({data:{semantic_version:"analytics-semantic-v1",normalized_query:{metrics:[metricKey]},query:{metrics:[metricKey]},columns:[{key:metricKey,business_name:metricKey,kind:"metric",data_type:"number"}],rows:[{[metricKey]:{state:"VALUE",value:2}}],coverage:[],warnings:[],pagination:{limit:20,next_cursor:null},execution:{read_only:true,organization_scoped:true}}});
describe("Operations Control Tower", () => {
  beforeEach(() => { vi.clearAllMocks(); (api.getOperationalContext as ReturnType<typeof vi.fn>).mockResolvedValue({data:{organization_id:1,permissions:["operational_shipment.read"]}}); (api.getAnalyticsSemanticRegistry as ReturnType<typeof vi.fn>).mockResolvedValue({data:registry}); (api.queryAnalytics as ReturnType<typeof vi.fn>).mockImplementation((query:{metrics:string[]}) => Promise.resolve(response(query.metrics[0]))); });
  const renderTower = () => render(<TooltipProvider><BrowserRouter><OperationsControlTower /></BrowserRouter></TooltipProvider>);
  it("loads the governed widgets from one registry request and analytics queries", async () => { renderTower(); expect(await screen.findByText("محموله‌های فعال")).toBeInTheDocument(); await waitFor(() => expect(api.queryAnalytics).toHaveBeenCalledTimes(8)); expect(api.getAnalyticsSemanticRegistry).toHaveBeenCalledTimes(1); expect(screen.queryByText(/On Time|Needs Attention/)).not.toBeInTheDocument(); });
  it("propagates a customer filter through analytics queries", async () => { renderTower(); await screen.findByText("محموله‌های فعال"); fireEvent.change(screen.getByLabelText("شناسه مشتری"), {target:{value:"customer:7"}}); await waitFor(() => expect((api.queryAnalytics as ReturnType<typeof vi.fn>).mock.calls.some(([query]) => query.filters.some((item:{dimension:string;value:string}) => item.dimension === "CUSTOMER" && item.value === "customer:7"))).toBe(true)); });
  it("uses POST drilldown with the widget normalized query", async () => { (api.drilldownAnalytics as ReturnType<typeof vi.fn>).mockResolvedValue({data:{items:[],pagination:{limit:20,next_cursor:null}}}); renderTower(); const link = await screen.findAllByText("جزئیات جمعیت"); fireEvent.click(link[0]); await waitFor(() => expect(api.drilldownAnalytics).toHaveBeenCalledWith("ACTIVE_SHIPMENT_COUNT", expect.objectContaining({metrics:["ACTIVE_SHIPMENT_COUNT"]}))); });
});
