"""Add international shipping fields to shipment_request

Revision ID: 20251006_124249
Revises: 20250101_add_crm_hierarchy_system
Create Date: 2025-10-06 12:42:49.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251006_124249'
down_revision = '20250101_add_crm_hierarchy_system'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_type', sa.String(length=20), nullable=False, server_default='domestic'))
        batch_op.add_column(sa.Column('origin_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('origin_city_international', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('origin_address_international', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dest_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dest_city_international', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dest_address_international', sa.Text(), nullable=True))
        batch_op.alter_column('origin_province_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('origin_county_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('origin_city_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('dest_province_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('dest_county_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('dest_city_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_request', schema=None) as batch_op:
        batch_op.alter_column('dest_city_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('dest_county_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('dest_province_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('origin_city_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('origin_county_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('origin_province_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('dest_address_international')
        batch_op.drop_column('dest_city_international')
        batch_op.drop_column('dest_country')
        batch_op.drop_column('origin_address_international')
        batch_op.drop_column('origin_city_international')
        batch_op.drop_column('origin_country')
        batch_op.drop_column('shipping_type')

    # ### end Alembic commands ###
