"""FE-2 Shipment Economics core. Revision: 20260817_shipment_economics_core."""
from alembic import op
import sqlalchemy as sa

revision="20260817_shipment_economics_core"
down_revision="20260816_oip_projection_health"
branch_labels=None
depends_on=None
BIG=sa.BigInteger()

def upgrade():
    op.create_table("economic_line",
        sa.Column("id",BIG,primary_key=True),sa.Column("public_id",sa.String(36),nullable=False),sa.Column("organization_id",BIG,nullable=False),sa.Column("operational_shipment_id",BIG,nullable=False),sa.Column("service_type_id",BIG,nullable=False),sa.Column("side",sa.String(12),nullable=False),sa.Column("counterparty_type",sa.String(32)),sa.Column("counterparty_public_id",sa.String(64)),sa.Column("quantity",sa.Numeric(20,6)),sa.Column("uom_code",sa.String(24)),sa.Column("description",sa.String(240)),sa.Column("lifecycle",sa.String(12),nullable=False,server_default="ACTIVE"),sa.Column("version",sa.Integer,nullable=False,server_default="1"),sa.Column("created_by_user_id",BIG,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),
        sa.UniqueConstraint("public_id",name="uq_economic_line_public_id"),sa.ForeignKeyConstraint(["operational_shipment_id","organization_id"],["operational_shipment.id","operational_shipment.organization_id"],name="fk_economic_line_shipment_org",ondelete="RESTRICT"),sa.ForeignKeyConstraint(["service_type_id"],["service_type.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["created_by_user_id"],["expert_user.id"],ondelete="RESTRICT"),sa.CheckConstraint("side IN ('REVENUE','COST')",name="ck_economic_line_side"),sa.CheckConstraint("lifecycle IN ('ACTIVE','CANCELLED')",name="ck_economic_line_lifecycle"),sa.CheckConstraint("version >= 1",name="ck_economic_line_version"),sa.CheckConstraint("quantity IS NULL OR quantity > 0",name="ck_economic_line_quantity"))
    op.create_index("ix_economic_line_shipment_side","economic_line",["organization_id","operational_shipment_id","side"])
    op.create_table("economic_observation",
        sa.Column("id",BIG,primary_key=True),sa.Column("public_id",sa.String(36),nullable=False),sa.Column("organization_id",BIG,nullable=False),sa.Column("line_id",BIG,nullable=False),sa.Column("stage",sa.String(12),nullable=False),sa.Column("amount",sa.Numeric(24,6),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("effective_at",sa.DateTime(timezone=True),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("actor_user_id",BIG,nullable=False),sa.Column("authority",sa.String(100),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_public_id",sa.String(100)),sa.Column("source_version",sa.String(64)),sa.Column("reason",sa.Text),sa.Column("status",sa.String(16),nullable=False,server_default="AUTHORIZED"),sa.Column("correction_type",sa.String(16)),sa.Column("corrects_observation_id",BIG),sa.Column("version",sa.Integer,nullable=False,server_default="1"),sa.Column("idempotency_key",sa.String(100),nullable=False),sa.Column("request_hash",sa.String(64),nullable=False),sa.Column("correlation_id",sa.String(100)),
        sa.UniqueConstraint("public_id",name="uq_economic_observation_public_id"),sa.UniqueConstraint("organization_id","idempotency_key",name="uq_economic_observation_idempotency"),sa.ForeignKeyConstraint(["organization_id"],["operational_organization.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["line_id"],["economic_line.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["actor_user_id"],["expert_user.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["corrects_observation_id"],["economic_observation.id"],ondelete="RESTRICT"),sa.CheckConstraint("stage IN ('ESTIMATE','COMMITMENT','ACTUAL')",name="ck_economic_observation_stage"),sa.CheckConstraint("status IN ('AUTHORIZED','SUPERSEDED','REVERSED')",name="ck_economic_observation_status"),sa.CheckConstraint("correction_type IS NULL OR correction_type IN ('SUPERSESSION','ADJUSTMENT','REVERSAL')",name="ck_economic_observation_correction"),sa.CheckConstraint("amount >= 0",name="ck_economic_observation_amount"),sa.CheckConstraint("length(currency)=3 AND currency=upper(currency)",name="ck_economic_observation_currency"),sa.CheckConstraint("version >= 1",name="ck_economic_observation_version"))
    op.create_index("ix_economic_observation_current","economic_observation",["line_id","stage","status","effective_at"])
    op.create_table("economic_evidence_association",sa.Column("id",BIG,primary_key=True),sa.Column("public_id",sa.String(36),nullable=False,unique=True),sa.Column("organization_id",BIG,nullable=False),sa.Column("observation_id",BIG,nullable=False),sa.Column("document_file_id",BIG,nullable=False),sa.Column("artifact_public_id",sa.String(36),nullable=False),sa.Column("artifact_version",sa.Integer,nullable=False),sa.Column("evidence_role",sa.String(40),nullable=False),sa.Column("associated_by_user_id",BIG,nullable=False),sa.Column("associated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["organization_id"],["operational_organization.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["observation_id"],["economic_observation.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["document_file_id"],["case_document_file.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["associated_by_user_id"],["expert_user.id"],ondelete="RESTRICT"),sa.UniqueConstraint("observation_id","document_file_id","artifact_version",name="uq_economic_evidence_exact_version"))
    op.create_table("economic_fx_rate",sa.Column("id",BIG,primary_key=True),sa.Column("public_id",sa.String(36),nullable=False),sa.Column("organization_id",BIG,nullable=False),sa.Column("from_currency",sa.String(3),nullable=False),sa.Column("to_currency",sa.String(3),nullable=False),sa.Column("rate",sa.Numeric(24,12),nullable=False),sa.Column("rate_type",sa.String(24),nullable=False),sa.Column("source",sa.String(120),nullable=False),sa.Column("authority",sa.String(120),nullable=False),sa.Column("effective_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("actor_user_id",BIG,nullable=False),sa.Column("status",sa.String(16),nullable=False,server_default="AUTHORIZED"),sa.Column("supersedes_rate_id",BIG),sa.Column("version",sa.Integer,nullable=False,server_default="1"),sa.UniqueConstraint("public_id",name="uq_economic_fx_rate_public_id"),sa.ForeignKeyConstraint(["organization_id"],["operational_organization.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["actor_user_id"],["expert_user.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["supersedes_rate_id"],["economic_fx_rate.id"],ondelete="RESTRICT"),sa.CheckConstraint("rate_type IN ('CONTRACTUAL','MANUAL_APPROVED')",name="ck_economic_fx_rate_type"),sa.CheckConstraint("status IN ('AUTHORIZED','SUPERSEDED')",name="ck_economic_fx_rate_status"),sa.CheckConstraint("rate > 0",name="ck_economic_fx_rate_positive"),sa.CheckConstraint("from_currency <> to_currency",name="ck_economic_fx_rate_pair"))
    op.create_table("economic_audit",sa.Column("id",BIG,primary_key=True),sa.Column("public_id",sa.String(36),nullable=False,unique=True),sa.Column("organization_id",BIG,nullable=False),sa.Column("operational_shipment_id",BIG,nullable=False),sa.Column("event_type",sa.String(64),nullable=False),sa.Column("actor_user_id",BIG,nullable=False),sa.Column("entity_public_id",sa.String(36),nullable=False),sa.Column("correlation_id",sa.String(100)),sa.Column("details",sa.JSON,nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["actor_user_id"],["expert_user.id"],ondelete="RESTRICT"))
    op.create_index("ix_economic_audit_organization_id","economic_audit",["organization_id"])
    op.create_index("ix_economic_audit_operational_shipment_id","economic_audit",["operational_shipment_id"])

def downgrade():
    raise RuntimeError("Fail-closed: FE-2 economic history cannot be dropped; restore a pre-FE-2 backup.")
