"""Add the Phase 1A operational shipment vertical slice.

Revision ID: 20260729_operational_vertical_slice
Revises: 20260728_add_quote_customer_response
"""
from alembic import op
import sqlalchemy as sa


revision = "20260729_operational_vertical_slice"
down_revision = "20260728_add_quote_customer_response"
branch_labels = None
depends_on = None

BIGINT = sa.BigInteger().with_variant(sa.Integer(), "sqlite")


def upgrade():
    op.create_table("operational_organization", sa.Column("id", BIGINT, primary_key=True), sa.Column("public_id", sa.String(36), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("public_id", name="uq_operational_organization_public_id"))
    op.create_table("canonical_location", sa.Column("id", BIGINT, primary_key=True), sa.Column("public_id", sa.String(36), nullable=False), sa.Column("source_type", sa.String(32), nullable=False), sa.Column("source_id", BIGINT, nullable=False), sa.Column("location_type", sa.String(32), nullable=False), sa.Column("display_name", sa.String(200), nullable=False), sa.Column("country_code", sa.String(3)), sa.Column("verification_state", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("public_id", name="uq_canonical_location_public_id"), sa.UniqueConstraint("source_type", "source_id", name="uq_canonical_location_source"), sa.CheckConstraint("source_type IN ('province','city','country','international_city','iran_port','customs_office')", name="ck_canonical_location_source_type"))
    op.create_table("operational_membership", sa.Column("id", BIGINT, primary_key=True), sa.Column("organization_id", BIGINT, nullable=False), sa.Column("user_id", BIGINT, nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("permissions", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["operational_organization.id"], name="fk_operational_membership_organization_id", ondelete="CASCADE"), sa.ForeignKeyConstraint(["user_id"], ["expert_user.id"], name="fk_operational_membership_user_id", ondelete="CASCADE"), sa.UniqueConstraint("organization_id", "user_id", name="uq_operational_membership_org_user"))
    op.create_index("ix_operational_membership_organization_id", "operational_membership", ["organization_id"])
    op.create_index("ix_operational_membership_user_id", "operational_membership", ["user_id"])
    op.add_column("expert_quote", sa.Column("operational_organization_id", BIGINT, nullable=True))
    op.create_foreign_key("fk_expert_quote_operational_organization_id", "expert_quote", "operational_organization", ["operational_organization_id"], ["id"], ondelete="RESTRICT")
    op.create_index("ix_expert_quote_operational_organization_id", "expert_quote", ["operational_organization_id"])
    op.create_table("operational_shipment", sa.Column("id", BIGINT, primary_key=True), sa.Column("public_id", sa.String(36), nullable=False), sa.Column("organization_id", BIGINT, nullable=False), sa.Column("shipment_request_id", BIGINT, nullable=False), sa.Column("accepted_quote_id", BIGINT, nullable=False), sa.Column("lifecycle_status", sa.String(20), nullable=False), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_by_user_id", BIGINT, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["operational_organization.id"], name="fk_operational_shipment_organization_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["shipment_request_id"], ["shipment_request.id"], name="fk_operational_shipment_request_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["accepted_quote_id"], ["expert_quote.id"], name="fk_operational_shipment_quote_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["created_by_user_id"], ["expert_user.id"], name="fk_operational_shipment_created_by", ondelete="RESTRICT"), sa.UniqueConstraint("public_id", name="uq_operational_shipment_public_id"), sa.UniqueConstraint("accepted_quote_id", name="uq_operational_shipment_accepted_quote"), sa.CheckConstraint("lifecycle_status IN ('planned','in_progress','completed','cancelled')", name="ck_operational_shipment_status"))
    op.create_index("ix_operational_shipment_org_status", "operational_shipment", ["organization_id", "lifecycle_status"])
    op.create_index("ix_operational_shipment_shipment_request_id", "operational_shipment", ["shipment_request_id"])
    op.create_table("route_plan", sa.Column("id", BIGINT, primary_key=True), sa.Column("operational_shipment_id", BIGINT, nullable=False), sa.Column("revision", sa.Integer(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_by_user_id", BIGINT, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["operational_shipment_id"], ["operational_shipment.id"], name="fk_route_plan_shipment_id", ondelete="CASCADE"), sa.ForeignKeyConstraint(["created_by_user_id"], ["expert_user.id"], name="fk_route_plan_created_by", ondelete="RESTRICT"), sa.UniqueConstraint("operational_shipment_id", "revision", name="uq_route_plan_shipment_revision"))
    op.create_index("ix_route_plan_operational_shipment_id", "route_plan", ["operational_shipment_id"])
    op.create_index("uq_route_plan_one_active", "route_plan", ["operational_shipment_id"], unique=True, postgresql_where=sa.text("is_active"), sqlite_where=sa.text("is_active = 1"))
    op.create_table("route_leg", sa.Column("id", BIGINT, primary_key=True), sa.Column("route_plan_id", BIGINT, nullable=False), sa.Column("sequence_number", sa.Integer(), nullable=False), sa.Column("origin_location_id", BIGINT, nullable=False), sa.Column("destination_location_id", BIGINT, nullable=False), sa.Column("origin_snapshot", sa.JSON(), nullable=False), sa.Column("destination_snapshot", sa.JSON(), nullable=False), sa.Column("transport_mode", sa.String(32), nullable=False), sa.Column("planned_departure", sa.DateTime(timezone=True), nullable=False), sa.Column("planned_arrival", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["route_plan_id"], ["route_plan.id"], name="fk_route_leg_plan_id", ondelete="CASCADE"), sa.ForeignKeyConstraint(["origin_location_id"], ["canonical_location.id"], name="fk_route_leg_origin_location_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["destination_location_id"], ["canonical_location.id"], name="fk_route_leg_destination_location_id", ondelete="RESTRICT"), sa.UniqueConstraint("route_plan_id", "sequence_number", name="uq_route_leg_plan_sequence"), sa.CheckConstraint("sequence_number >= 1", name="ck_route_leg_sequence_positive"), sa.CheckConstraint("origin_location_id <> destination_location_id", name="ck_route_leg_distinct_locations"), sa.CheckConstraint("planned_arrival >= planned_departure", name="ck_route_leg_timeline"), sa.CheckConstraint("status IN ('planned','in_progress','completed','cancelled')", name="ck_route_leg_status"))
    op.create_table("operational_milestone", sa.Column("id", BIGINT, primary_key=True), sa.Column("route_leg_id", BIGINT, nullable=False), sa.Column("milestone_type", sa.String(20), nullable=False), sa.Column("planned_at", sa.DateTime(timezone=True), nullable=False), sa.Column("projected_state", sa.String(20), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True)), sa.Column("verification_state", sa.String(20), nullable=False), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["route_leg_id"], ["route_leg.id"], name="fk_operational_milestone_leg_id", ondelete="CASCADE"), sa.UniqueConstraint("route_leg_id", "milestone_type", name="uq_operational_milestone_leg_type"), sa.CheckConstraint("milestone_type IN ('departure','arrival')", name="ck_operational_milestone_type"), sa.CheckConstraint("verification_state IN ('planned','reported','verified')", name="ck_operational_milestone_verification"))
    op.create_index("ix_operational_milestone_route_leg_id", "operational_milestone", ["route_leg_id"])
    op.create_index("ix_operational_milestone_planned_at", "operational_milestone", ["planned_at"])
    op.create_table("milestone_event", sa.Column("id", BIGINT, primary_key=True), sa.Column("milestone_id", BIGINT, nullable=False), sa.Column("event_type", sa.String(20), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.Column("actor_user_id", BIGINT, nullable=False), sa.Column("reason", sa.Text()), sa.Column("supersedes_event_id", BIGINT), sa.Column("idempotency_key", sa.String(100), nullable=False), sa.Column("request_hash", sa.String(64), nullable=False), sa.ForeignKeyConstraint(["milestone_id"], ["operational_milestone.id"], name="fk_milestone_event_milestone_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["actor_user_id"], ["expert_user.id"], name="fk_milestone_event_actor_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["supersedes_event_id"], ["milestone_event.id"], name="fk_milestone_event_supersedes_id", ondelete="RESTRICT"), sa.UniqueConstraint("milestone_id", "idempotency_key", name="uq_milestone_event_idempotency"), sa.CheckConstraint("event_type IN ('reported','verified','corrected')", name="ck_milestone_event_type"), sa.CheckConstraint("event_type <> 'corrected' OR (reason IS NOT NULL AND length(trim(reason)) > 0 AND supersedes_event_id IS NOT NULL)", name="ck_milestone_event_correction"))
    op.create_index("ix_milestone_event_milestone_recorded", "milestone_event", ["milestone_id", "recorded_at", "id"])
    op.create_table("operational_work_item", sa.Column("id", BIGINT, primary_key=True), sa.Column("organization_id", BIGINT, nullable=False), sa.Column("operational_shipment_id", BIGINT, nullable=False), sa.Column("milestone_id", BIGINT, nullable=False), sa.Column("work_type", sa.String(40), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("due_at", sa.DateTime(timezone=True), nullable=False), sa.Column("assignee_user_id", BIGINT), sa.Column("reason", sa.Text(), nullable=False), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.Column("resolved_by_user_id", BIGINT), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["operational_organization.id"], name="fk_operational_work_item_organization_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["operational_shipment_id"], ["operational_shipment.id"], name="fk_operational_work_item_shipment_id", ondelete="CASCADE"), sa.ForeignKeyConstraint(["milestone_id"], ["operational_milestone.id"], name="fk_operational_work_item_milestone_id", ondelete="CASCADE"), sa.ForeignKeyConstraint(["assignee_user_id"], ["expert_user.id"], name="fk_operational_work_item_assignee_id", ondelete="SET NULL"), sa.ForeignKeyConstraint(["resolved_by_user_id"], ["expert_user.id"], name="fk_operational_work_item_resolved_by_id", ondelete="SET NULL"), sa.CheckConstraint("work_type IN ('OVERDUE_MILESTONE')", name="ck_operational_work_item_type"), sa.CheckConstraint("status IN ('open','resolved')", name="ck_operational_work_item_status"))
    op.create_index("ix_operational_work_item_operational_shipment_id", "operational_work_item", ["operational_shipment_id"])
    op.create_index("uq_operational_work_item_open", "operational_work_item", ["milestone_id", "work_type"], unique=True, postgresql_where=sa.text("status = 'open'"), sqlite_where=sa.text("status = 'open'"))
    op.create_index("ix_operational_work_item_queue", "operational_work_item", ["organization_id", "work_type", "status", "due_at"])
    op.create_table("operational_audit", sa.Column("id", BIGINT, primary_key=True), sa.Column("organization_id", BIGINT, nullable=False), sa.Column("actor_user_id", BIGINT, nullable=False), sa.Column("action", sa.String(80), nullable=False), sa.Column("entity_type", sa.String(50), nullable=False), sa.Column("entity_id", BIGINT, nullable=False), sa.Column("metadata_json", sa.JSON(), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["operational_organization.id"], name="fk_operational_audit_organization_id", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["actor_user_id"], ["expert_user.id"], name="fk_operational_audit_actor_id", ondelete="RESTRICT"))
    op.create_index("ix_operational_audit_organization_id", "operational_audit", ["organization_id"])
    op.create_table("operational_outbox", sa.Column("id", BIGINT, primary_key=True), sa.Column("organization_id", BIGINT, nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("aggregate_type", sa.String(50), nullable=False), sa.Column("aggregate_id", BIGINT, nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)), sa.ForeignKeyConstraint(["organization_id"], ["operational_organization.id"], name="fk_operational_outbox_organization_id", ondelete="RESTRICT"))
    op.create_index("ix_operational_outbox_unpublished", "operational_outbox", ["published_at", "created_at"])
    op.create_table("operational_idempotency", sa.Column("id", BIGINT, primary_key=True), sa.Column("organization_id", BIGINT, nullable=False), sa.Column("operation", sa.String(60), nullable=False), sa.Column("idempotency_key", sa.String(100), nullable=False), sa.Column("request_hash", sa.String(64), nullable=False), sa.Column("resource_id", BIGINT), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["organization_id"], ["operational_organization.id"], name="fk_operational_idempotency_organization_id", ondelete="CASCADE"), sa.UniqueConstraint("organization_id", "operation", "idempotency_key", name="uq_operational_idempotency_key"))
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""CREATE FUNCTION public.phase1a_reject_milestone_event_mutation_v1() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'milestone_event is append-only' USING ERRCODE = '55000'; END; $$""")
        op.execute("""CREATE TRIGGER trg_milestone_event_append_only BEFORE UPDATE OR DELETE ON milestone_event FOR EACH ROW EXECUTE FUNCTION public.phase1a_reject_milestone_event_mutation_v1()""")
        op.execute("""CREATE FUNCTION public.phase1a_validate_milestone_event_correction_v1() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.supersedes_event_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM milestone_event e WHERE e.id = NEW.supersedes_event_id AND e.milestone_id = NEW.milestone_id) THEN RAISE EXCEPTION 'superseded event must belong to the same milestone' USING ERRCODE = '23514'; END IF; RETURN NEW; END; $$""")
        op.execute("""CREATE TRIGGER trg_milestone_event_correction_scope BEFORE INSERT ON milestone_event FOR EACH ROW EXECUTE FUNCTION public.phase1a_validate_milestone_event_correction_v1()""")
        op.execute("""CREATE FUNCTION public.phase1a_validate_work_item_scope_v1() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT EXISTS (SELECT 1 FROM operational_shipment s WHERE s.id=NEW.operational_shipment_id AND s.organization_id=NEW.organization_id) OR NOT EXISTS (SELECT 1 FROM operational_milestone m JOIN route_leg l ON l.id=m.route_leg_id JOIN route_plan p ON p.id=l.route_plan_id WHERE m.id=NEW.milestone_id AND p.operational_shipment_id=NEW.operational_shipment_id) THEN RAISE EXCEPTION 'work item scope mismatch' USING ERRCODE = '23514'; END IF; RETURN NEW; END; $$""")
        op.execute("""CREATE TRIGGER trg_operational_work_item_scope BEFORE INSERT OR UPDATE ON operational_work_item FOR EACH ROW EXECUTE FUNCTION public.phase1a_validate_work_item_scope_v1()""")


def downgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_operational_work_item_scope ON operational_work_item")
        op.execute("DROP FUNCTION IF EXISTS public.phase1a_validate_work_item_scope_v1()")
        op.execute("DROP TRIGGER IF EXISTS trg_milestone_event_correction_scope ON milestone_event")
        op.execute("DROP FUNCTION IF EXISTS public.phase1a_validate_milestone_event_correction_v1()")
        op.execute("DROP TRIGGER IF EXISTS trg_milestone_event_append_only ON milestone_event")
        op.execute("DROP FUNCTION IF EXISTS public.phase1a_reject_milestone_event_mutation_v1()")
    for table in ["operational_idempotency", "operational_outbox", "operational_audit", "operational_work_item", "milestone_event", "operational_milestone", "route_leg", "route_plan", "operational_shipment", "operational_membership", "canonical_location"]:
        op.drop_table(table)
    op.drop_index("ix_expert_quote_operational_organization_id", table_name="expert_quote")
    op.drop_constraint("fk_expert_quote_operational_organization_id", "expert_quote", type_="foreignkey")
    op.drop_column("expert_quote", "operational_organization_id")
    op.drop_table("operational_organization")
