"""Personal dashboard persistence; source-controlled system templates have no rows."""
from alembic import op
import sqlalchemy as sa
revision="20260913_dashboard_persistence"
down_revision="20260912_execution_authority"
branch_labels=None
depends_on=None
def upgrade():
    op.create_table("dashboard",sa.Column("id",sa.BigInteger(),primary_key=True),sa.Column("public_id",sa.String(36),nullable=False,unique=True),sa.Column("organization_id",sa.BigInteger(),sa.ForeignKey("operational_organization.id",ondelete="RESTRICT"),nullable=False),sa.Column("owner_user_id",sa.BigInteger(),sa.ForeignKey("expert_user.id",ondelete="RESTRICT"),nullable=False),sa.Column("dashboard_type",sa.String(16),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("description",sa.String(1000),nullable=False),sa.Column("visibility",sa.String(16),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("semantic_version",sa.String(64),nullable=False),sa.Column("dashboard_schema_version",sa.String(64),nullable=False),sa.Column("definition_json",sa.JSON(),nullable=False),sa.Column("source_dashboard_public_id",sa.String(128)),sa.Column("source_version",sa.Integer()),sa.Column("source_type",sa.String(16)),sa.Column("cloned_at",sa.DateTime(timezone=True)),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_by",sa.BigInteger(),sa.ForeignKey("expert_user.id",ondelete="RESTRICT"),nullable=False),sa.Column("updated_by",sa.BigInteger(),sa.ForeignKey("expert_user.id",ondelete="RESTRICT"),nullable=False),sa.CheckConstraint("dashboard_type = 'PERSONAL'",name="ck_dashboard_personal_only"),sa.CheckConstraint("visibility = 'PRIVATE'",name="ck_dashboard_private_only"),sa.CheckConstraint("status IN ('ACTIVE','ARCHIVED')",name="ck_dashboard_status"),sa.CheckConstraint("version >= 1",name="ck_dashboard_version_positive"))
    op.create_index("ix_dashboard_org_owner_status","dashboard",["organization_id","owner_user_id","status"])
    op.create_table("dashboard_revision",sa.Column("id",sa.BigInteger(),primary_key=True),sa.Column("dashboard_id",sa.BigInteger(),sa.ForeignKey("dashboard.id",ondelete="RESTRICT"),nullable=False),sa.Column("revision_number",sa.Integer(),nullable=False),sa.Column("definition_json",sa.JSON(),nullable=False),sa.Column("semantic_version",sa.String(64),nullable=False),sa.Column("dashboard_schema_version",sa.String(64),nullable=False),sa.Column("name_snapshot",sa.String(120),nullable=False),sa.Column("description_snapshot",sa.String(1000),nullable=False),sa.Column("changed_by",sa.BigInteger(),sa.ForeignKey("expert_user.id",ondelete="RESTRICT"),nullable=False),sa.Column("changed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("change_reason",sa.String(255)),sa.UniqueConstraint("dashboard_id","revision_number",name="uq_dashboard_revision_number"))
def downgrade():
    op.drop_table("dashboard_revision");op.drop_index("ix_dashboard_org_owner_status",table_name="dashboard");op.drop_table("dashboard")
